### ISSUE TITLE
 Showing Recent Messages Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData

### ISSUE THREAD

**Issue by Bavon101** [rafaelsetragni/awesome_notifications#115]
I'm building ios in Xcode and i keep getting this error from the Target extensions:
`
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData

`
`
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_FlutterError

`
`
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel

`

I've been having trouble with the package continuously, for any solution I
 would really appreciate it,
![Screenshot 2021-02-07 at 14 11 35](https://user-images.githubusercontent.com/47344665/107144784-84203180-694e-11eb-81db-9053d10c73f8.png)

**Comment by rafaelsetragni** [comment]
That happens because your ios folder was created on a older flutter version and now it will not work on new one. You unfortunally need to do the following steps:

* Update your Cocoa pod instalation with `sudo gem install cocoapods`
* Update your Flutter directory with `flutter upgrade`
* Save every modification inside your iOS folder and delete it
* Recreate the iOS folder using the command `flutter create .`
* Clean your project with `flutter clean`
* Redo all the steps for iOS inside from [iOS Extra Configuration's Readme topic](https://github.com/rafaelsetragni/awesome_notifications#ios-extra-configurations)

Yes, is pretty bad. But that happens offen while were working with iOS products because they are Apple and do Apple things. They constantely keep the effort to make the "non native developers" lives worst, every day.

**Comment by efraespada** [comment]
I'm having the same problem. I did all the steps you say and after recreating de `ios` folder, I'm getting the same error.

**Comment by Tuxilero** [comment]
@rafaelsetragni Hey, we are getting the exact same error. We are trying to fix this for over a week now! I can't even count how many times I already deleted the 'ios' folder and recreated the project from scratch. Would be really glad for any other help anyone can provide. Sadly those steps does not work. 🙏  Sadly this rendering the lib completely useless and unusable.

**Comment by Bavon101** [comment]
> @rafaelsetragni Hey, we are getting the exact same error. We are trying to fix this for over a week now! I can't even count how many times I already deleted the 'ios' folder and recreated the project from scratch. Would be really glad for any other help anyone can provide. Sadly those steps does not work. 🙏 Sadly this rendering the lib completely useless and unusable.

Did you recently change your flutter channel from a previous one that you we're developing in? I experienced the same issue doing what your doing never helped, I had to stop shifting channels and running code on the my previous channel.

**Comment by rafaelsetragni** [comment]
This is not an exclusive problem from this plugin. This is happen quite often with flutter and XCode.

[Error linking flutter plugins in configuration other than 'Debug' #32806](https://github.com/flutter/flutter/issues/32806)

The steps worked for me, while i was developing using XCode directly. But when i came back to Android Studio, these errors came back too.

Im trying to discovery how to fix it, but until now i havent found a definetly solution.

**Comment by rafaelsetragni** [comment]
Try to do the following steps:

- Remove the `AwesomeContentExtension`, `AwesomeServiceExtension` targets from XCode
- Remove all the PodFile editions
- Run `pod install` again

Of course this will kill the FCM support from this plugin. But it will be removed anyway. Use `firebase_messaging` instead.

Is necessary to find a better way to share the `awesome_notifications` library with the target extensions in the pod files. But i even don't know if it worth the effort.

**Comment by efraespada** [comment]
It is not a bug of this plugin. I think the problem is the wrong framework linking with the new Flutter version (at least in the iOS part).
I'm having similar issues with all the old Flutter projects where I try to run the app in iOS.

Creating a new project and copying everything from the old dart code seems to be the best solution (not the faster). 😅

**Comment by sebalaursen** [comment]
Having the same issue. 
First I was building project without adding `AwesomeContentExtension` and `AwesomeServiceExtension` and the issue
```
Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData

Undefined symbol: _OBJC_CLASS_$_FlutterError

Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel
```
was appearing in my ShareExtension for ios. So I followed the advice here and replaced my ios folder.
I had replaced my ios folder with a new one from a new `flutter create` project and everything seemed to work, after adding `AwesomeServiceExtension` extension to the project the same issue started again but in `AwesomeServiceExtension` instead of the other extension I had.

**Comment by rafaelsetragni** [comment]
To fix this issue, we have two solutions:

1 - Remove `AwesomeContentExtension`,` AwesomeServiceExtension` and disable the push notifications feature for this plugin.
2 - Rewrite the `Pod file` modification to share the `awesome_notification` library with the target extensions without these errors. I haven't been able to do that so far and I'm totally open to suggestions.

What we have until now is:

```pod
target 'AwesomeServiceExtension' do
  use_frameworks!
  use_modular_headers!

  pod 'awesome_notifications', :path => '.symlinks/plugins/awesome_notifications/ios'
end

target 'AwesomeContentExtension' do
  use_frameworks!
  use_modular_headers!

  pod 'awesome_notifications', :path => '.symlinks/plugins/awesome_notifications/ios'
end
`

I know it's possible to share the `awesome notification` library, but the only way that I could do it was using the code above.

**Comment by bysano** [comment]
hi! i've updated Flutter to Channel stable, 2.0.3, and decided to check this issue : added all targets as in readme, 
from Xcode build was successful for IOS emulator  and real device, but if do it from intellij IDE i get smae errors application works fine

**Comment by robinbonnes** [comment]
I've put a bounty on this to get this fixed: https://www.bountysource.com/issues/97517543-showing-recent-messages-undefined-symbol-_objc_class_-_flutterstandardtypeddata

**Comment by Holofox** [comment]
@robinbonnes, I left a solution to the problem on `bountysource`, let me know if you need a sample project where this works. With your permission, I can share the solution with other participants in the problem.

**Comment by robinbonnes** [comment]
Tried to resolve this issue with @Holofox, but unfortunately we didn't find a solution yet.

For anyone trying to resolve this, here is a basic Flutter project with `awesome_notifications` installed and thus this issue: https://github.com/robinbonnes/awesome_notifications_example

@rafaelsetragni If we remove Firebase from this package and are able to install this together with `firebase_messaging` for both Android and iOS, are those extensions still needed?

**Comment by rafaelsetragni** [comment]
No, they arent need anymore.
