### ISSUE TITLE
Ability to customize Action Button's response to app state on user interaction

### ISSUE THREAD

**Issue by ashishbeck** [rafaelsetragni/awesome_notifications#125]
I wanted to know if it is possible to have the ability to decide if the user input launches the app or not in the future. I know that the readme has mentioned what each button does. I just needed the user to reply to a message from the notification tray without  launching my app.
Great plugin btw

**Comment by ashishbeck** [comment]
Is there an update on this?

**Comment by rafaelsetragni** [comment]
Yes, but is not live yet.

**Comment by ashishbeck** [comment]
Thanks a lot, I'm glad that it's been done. Should I be expecting it in the next release then?

**Comment by rafaelsetragni** [comment]
Its gonna take some time, because im only capable to process it without open the app if it runs dart code in background. That function already exists, but is being integrating with silent push data as well.
As soon as this integration will be achieved, i gonna release in a new version.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of awesome_notifications and awesome_notifications_fcm and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
