### ISSUE TITLE
iOS: recieved invalid notification content When clicking on notification

### ISSUE THREAD

**Issue by razmik-gharibyan** [rafaelsetragni/awesome_notifications#132]
I am sending push notification from fcm to device. Using 0.0.5+7 version of package and when i click on notification actionStream is not fired and i see this message printed "recieved invalid notification content".
If i use version 0.0.5+5 and i click on notification i get NOTIFICATION RECEIVED printed but my app is getting freezed in loading state in native splash screen.

**Comment by rafaelsetragni** [comment]
I´ve commented for test the FCM remove service and i forgot to put it back. Sorry.
I gonna release a new version to fix it today.

**Comment by razmik-gharibyan** [comment]
No it's not fixed, still actionStream is not fired, none of streams is fired. And same message recieved invalid notification content

**Comment by rafaelsetragni** [comment]
Can you debug it for me? Use XCode directly to do it.

**Comment by razmik-gharibyan** [comment]
What should i do in order to debug it? Run via xcode?

**Comment by razmik-gharibyan** [comment]
This is what console shows when notification appears on screen and I tap it

2021-03-09 19:11:58.624252+0400 Runner[5294:334023] [ProcessSuspension] 0x28198a1c0 - WKProcessAssertionBackgroundTaskManager: Ignored request to start a new background task because RunningBoard has already started the expiration timer
2021-03-09 19:12:03.668631+0400 Runner[5294:334023] [ProcessSuspension] 0x28198a1c0 - WKProcessAssertionBackgroundTaskManager: Ignored request to start a new background task because RunningBoard has already started the expiration timer
Received an invalid notification content

**Comment by rafaelsetragni** [comment]
I cant discovery whats goin on with your application with this log. At least you need to tell me what line are this error occurring. Otherwise only you with your project can discovery it.

**Comment by razmik-gharibyan** [comment]
That is all i have it doesn't show a line. What should i do in order to see error line?

**Comment by rafaelsetragni** [comment]
You need to debug natively, using XCode or try to debug using Android Studio to capture dart errors. One or another are capable to capture the error. Unfortunely, there is no way to debug both things on iOS (thanks Apple!)

**Comment by razmik-gharibyan** [comment]
Well i can tell one thing for sure, even createdStream is not fired when notification is created, if that info will help of course. I will try to debug it later.

**Comment by Amareis** [comment]
I think it's related to https://github.com/FirebaseExtended/flutterfire/issues/5417
Firebase getInitialMessage is not fired on iOS currently.

**Comment by rafaelsetragni** [comment]
Please, try to use the 0.0.6+1 version to see if the problem persists.

**Comment by ParadiseFallen** [comment]
this issue stil exsist on 0.0.6+7. Any ideas to fix it? It will fire *recieved invalid notification content* even if ypu dont use this package. to reproduce it u enough to add package in pubspec and build app. is there any solutions?

**Comment by rafaelsetragni** [comment]
Guys, this plugin is entirely open source. Any one can open it, debug, change and send back your improvements.

Im the only person projecting and building this plugin today, and obviously im limited of what i can do each time.

If you know there is a issue and you are urgent to fix it, fork this project, put your hands in the dirt, debug, fix it and send it back to us. I never refused a third party improvement.

**Comment by rafaelsetragni** [comment]
I did a test branch to check if the problem could be solved with a little change. Try to put the declaration bellow inside your `pubspec.yaml` file:

```yaml
  awesome_notifications: #^0.0.6+7
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: c968836
```

Also, put the code bellow inside your `pubspec.yaml`, to allow to use direrctely GitHub repositories in your project, bellow the tag `description`:

```yaml
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
```

And finally run `pub get` to check if the problem is solved with this fix.

**Comment by jonas-zebari** [comment]
@rafaelsetragni Hello! First of all, thank you for creating and maintaining this wonderful package.

I am currently on 0.0.6+10 and have started to encounter this issue on iOS. I would be investigating our backend which is sending the FCM for invalid formatting, but the notifications are working just fine on Android. So, are there any logs or tests I can run to help you figure out this issue? I have tried to debug in xcode but I can't seem to get it to actually hit a breakpoint (I am an xcode noobie).

**Comment by rafaelsetragni** [comment]
I understand that could be some different behaviors while converting the json content values in iOS and Android platforms, this is possible.

Unfortunaly, i havent had wrote any unit test to cover the FCM values conversion, but im writing a new plugin to be complementary to this one called `awesome_notifications_fcm`. So, if you wanna help me some way, you can write the unit tests there.

**Comment by jonas-zebari** [comment]
I attempted to use `awesome_notifications_fcm` in order to get an understanding of it but unfortunately I cannot get past calling `initialize` before getting a "String is not a subtype of bool" error from the method channel.

I shifted my attention to trying to debug where `Received an invalid notification content` message is occurring. After some tests notifications I can see that on line `132` of `SwiftAwesomeNotificationsPlugin.swift` the receiver is trying to parse the `userInfo` dictionary with key `"notificationJson"`, but the dictionary does not contain that key. The conditional cast to `String` then fails and the function exits without updating the action stream. Interestingly, the `userInfo` dict does contain many other values related to FCM and has values from the `payload` sent by FCM.

Also, I've realized that on iOS, `FirebaseMessaging.onBackgroundMessage` is not being called when `awesome_notifications` is also running. I'm not sure if those are related but they are definitely both very functionality-breaking bugs for iOS users.

I tried to find where the function `userNotificationCenter` is being used but I'm not experienced enough in Xcode to find out why these things are happening. Please let me know if there's anything else that would help you.

**Comment by rafaelsetragni** [comment]
> 
> 
> I attempted to use `awesome_notifications_fcm` in order to get an understanding of it but unfortunately I cannot get past calling `initialize` before getting a "String is not a subtype of bool" error from the method channel.

Im developing it yet. Is not ready to use. It will gonna be ready to use soon with 0.0.7 release.

> 
> I shifted my attention to trying to debug where `Received an invalid notification content` message is occurring. After some tests notifications I can see that on line `132` of `SwiftAwesomeNotificationsPlugin.swift` the receiver is trying to parse the `userInfo` dictionary with key `"notificationJson"`, but the dictionary does not contain that key. The conditional cast to `String` then fails and the function exits without updating the action stream. Interestingly, the `userInfo` dict does contain many other values related to FCM and has values from the `payload` sent by FCM.

Interesting! I gonna inspectorate it later on.

> 
> Also, I've realized that on iOS, `FirebaseMessaging.onBackgroundMessage` is not being called when `awesome_notifications` is also running. I'm not sure if those are related but they are definitely both very functionality-breaking bugs for iOS users.

Integrate firebase_messaging with `awesome_notifications` is not fully possible. Thats why i had to created the new `awesome_notifications_fcm` plugin.

> 
> I tried to find where the function `userNotificationCenter` is being used but I'm not experienced enough in Xcode to find out why these things are happening. Please let me know if there's anything else that would help you.

I'll keep you informed by posting the news here as I release them.

**Comment by furkankurt** [comment]
I fixed it, you should try this: https://github.com/rafaelsetragni/awesome_notifications/issues/175#issuecomment-901440949

**Comment by rafaelsetragni** [comment]
Be careful! `onBackgroundMessage` and data-only push notifications don't always work on iOS, because of their background processing policies. If their algorithm (which no one knows the rules) decides that your app is consuming too many resources, your app will be temporarily suspended in the background until the next time the user manually brings the app to the foreground.

**Comment by adrianvintu** [comment]
I also receive "Received an invalid notification content"

I have tried updating the libraries and sending different message formats - all show this text inside the app.

But! the notification is displayed! It's just that on the flutter dart code I receive that text - and no code is ran, of course.

No logs, sorry.

**Comment by wiktoriasobczyk** [comment]
I have the same error as @adrianvintu  said

**Comment by furkankurt** [comment]
I fixed it, you should try this: #175 (comment) @wiktoriasobczyk  @adrianvintu

**Comment by arbyazra123** [comment]
Hi, i ended up with creating Native Channel in `didFinisihLaunch` function on `AppDelegate.swift`.

In my case, i already had log when fcm payload came, but when i tried to click the push notification, it prints "received an invalid notification content".

With a little approach, i implemented firebase guidance in iOS app (https://firebase.google.com/docs/cloud-messaging/ios/client).

Here's the code : 

1. Put following code in a state that you want to listen when push notification will be clicked. 
Lets say ```"HomePage"```

```
class _HomeState extends State<Home> with SingleTickerProviderStateMixin {

  MethodChannel _channel =
  const MethodChannel('com.arby.app/backgroundNotifications');

  @override
  void initState() {
    super.initState();
    .
    .
    .
    _channel.setMethodCallHandler(setupNotification);
  }
  
  Future<dynamic> setupNotification(MethodCall call) async {
    print("init state setMethodCallHandler ${call.method}"); // Never comes here
    switch (call.method) {
      case 'manuallyInterceptNotification':
      
        // variable contains data model obtained from native iOS
        // call.arguments would be like {id:1,title:...,body:...,screen:...}
        
        var payload = Map<String,dynamic>.from(call.arguments as Map)
        
        // your navigation code or something goes here...
        // Navigate.of(context).pushNamed(payload['screen']);
        
      default:
        throw MissingPluginException('notImplemented');
    }
  }
```
3. Add `FlutterMethodChannel` inside didFinisihLaunch in `AppDelegate.swift`

```
...
var manualNotificationChannel : FlutterMethodChannel!

override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
  
  ....
  
  let controller : FlutterViewController = window?.rootViewController as! FlutterViewController
  
  manualNotificationChannel = FlutterMethodChannel.init(name: "com.arby.app/backgroundNotifications", binaryMessenger: controller.binaryMessenger)
  
  ....
  
  }
```

4. Add function `sendMessageToFlutter` below didFinishLaunch in `AppDelegate.swift`, it will fires state in home.dart when this function get invoked 

```
private func sendMessageToFlutter(result : Dictionary <String, String>){
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now()) {
            self.manualNotificationChannel.invokeMethod("manuallyInterceptNotification", arguments: result)
        }
    }
```

5.  Add overriding function based on FCM documentation (https://firebase.google.com/docs/cloud-messaging/ios/client), inside the override function, we'll put the following codes :
```
@available(iOS 10, *)
  override func userNotificationCenter(_ center: UNUserNotificationCenter,
                              didReceive response: UNNotificationResponse,
                              withCompletionHandler completionHandler: @escaping () -> Void) {
    let userInfo = response.notification.request.content.userInfo
    Messaging.messaging().appDidReceiveMessage(userInfo)
    var payload: [String: String] = [:]
   
     // this is the example of key:value data inside your payload
 
    if let id = userInfo["id"] {
      payload["id"] = "\(id)"
    }
    if let body = userInfo["body"] {
      payload["body"] = "\(body)"
    }
    if let title = userInfo["title"] {
      payload["title"] = "\(title)"
    }
    if let screen= userInfo["screen"] {
      payload["screen"] = "\(screen)"
    }
    
    sendMessageToFlutter(result:payload);
    completionHandler()
    
  }  
  ```
  
i didnt know whats the best practice to convert `AnyHashable` to `Dictionary` (we are using `Dictionary` due to dart received data-type rules https://docs.flutter.dev/development/platform-integration/platform-channels?tab=type-mappings-swift-tab#codec)

yet, we still waiting for the firebase (i thought) to solve the problem, idk how long ive been strolling to solve it, i tried with various way but had not trying for this one, and its worked for me now, at least.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
