### ISSUE TITLE
Please add an example of how to schedule repeated Notifications.

### ISSUE THREAD

**Issue by Wizzel1** [rafaelsetragni/awesome_notifications#151]
Apparently I have to create a NotificationCalendar() Object for the schedule parameter but I have no idea what "era" means or how to get it. Can you please add an example to the Readme?

**Comment by Wizzel1** [comment]
Ok I read in the documentation that _Is necessary at least one *required attribute_ , so I am assuming 

```
AwesomeNotifications().createNotification(
        schedule:
            NotificationCalendar(day: 1, hour: 13, minute: 40, repeats: true),
        content: NotificationContent(
            id: 10,
            channelKey: 'basic_channel',
            title: 'Simple Notification',
            body: 'Simple body'));
```
will fire a notification every Monday at 13:40, is that correct?

**Comment by Wizzel1** [comment]
Never mind, I found the example methods in utils/notification_util.dart. Thanks for this awesome package!

**Comment by madd-project** [comment]
@Wizzel1  Can you Provide a  Snippet, Please, I was not able to Find in there

**Comment by Wizzel1** [comment]
@madd-project What kind of notification do you want to schedule?

**Comment by madd-project** [comment]
Hey @Wizzel1, 👋🏼 ,
I want to Schedule a Daily Notification that will be sounding in every specific time,
🤔 .. Can we have something for this?

I do Found about, 
NotificationInterval(),
but i needed to merge, NotificationInterval() and NoticationCalender(),
Like except using Interval, What if I could use, hour and minute, that i was using....

**Comment by madd-project** [comment]
@Wizzel1 💡 
Will there be Errors if I do this,

```
  AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: 30,
          channelKey: 'streakNotific',
          title: "$name $emoji",
          body: "Save the Streak, its $hour:$minute"),
      schedule: NotificationInterval(
        // hour: hour,
        // minute: minute,
        interval: 86400,
        allowWhileIdle: true,
        repeats: true,
        timeZone: AwesomeNotifications.localTimeZoneIdentifier,
      ));
```

I am using NotificationInterval() here I am Firing up the Notification in every 24 hours, as the NotificationInterval() was taking, seconds as his mate, so....
I used this and used 86400 secs, which is exactly 24 hours..
thus, 
Will there be errors..


Also So thankful, to the most beloving @Wizzel1 
You Approached me, I told you the issue, and when I wrote the Issue the Issue is Resolved, you are Really Great. Thanks for helping, I was pulling every hing from my body from 3 hours 😆 ,

But You really hellped ❤️ 
Thanks alot 👍🏼 

Also Do tell me, weather i am doing it nice, will there be any complications?
Thanks.. Cheers 🧀

**Comment by Wizzel1** [comment]
@madd-project I personally would prefer to use the other available properties and set days/hours instead of seconds. Other than that I don't see why this should not work

**Comment by madd-project** [comment]
Sup  👋🏼 ,
Thank you as you Replied.

I am not Sure, How can I manage to Make Daily Notifications (yet repeating)
If you have any Example Can You drop one, @Wizzel1
