### ISSUE TITLE
How to convert the current time for scheduling?

### ISSUE THREAD

**Issue by Wizzel1** [rafaelsetragni/awesome_notifications#159]
I want to schedule a Notification with 

```
await AwesomeNotifications().createNotification(
        content: NotificationContent(
          id: 2,
          channelKey: 'scheduled',
          title: "",
          body: "",
        ),
        schedule: NotificationCalendar(
            minute: 19,
            second: 0,
            repeats: true));
```

but as soon as I specify the hour it doesn't work. 

I have tried to convert the desired time to UTC and use that "hour" value, didn't work. 
I have tried to convert this UTC back to local and use its "hour", also didn't work. 

So how do I convert the time in order to get it shown at the desired time?

**Comment by Wizzel1** [comment]
Ok so the problem is that the conversion to UTC doesn't take daylight saving time into account. Is there a way around it?

**Comment by rafaelsetragni** [comment]
We use UTC for internal system processment just because it doesnt take daylight saving into account.
Time zones are political and very complex to deal. Take a look at this video to see where the rabbit hole ends:

[The Problem with Time & Timezones - Computerphile](https://www.youtube.com/watch?v=-5wpm-gesOY)

Convert your local date into utc and extract the date components from it.

**Comment by Wizzel1** [comment]
That video is pretty accurate 😆 Ok I'll dig into it.
