### ISSUE TITLE
Notification Reply without bringing app to foreground

### ISSUE THREAD

**Issue by luckycreationsindia** [rafaelsetragni/awesome_notifications#171]
Is it possible to keep app in background after a user reply via notification?

Edit:
I'm trying to create chat app like whatsapp where user can reply from notification. It would be good to handle that reply in background.

Also, How to handle that notification reply?

**Comment by rafaelsetragni** [comment]
Unfortunately is not possible, because flutter works mainly over dart, and to deal with this reply in background you need to handle it and do everything in native layer.

Also, on iOS background process are very limited. Even creating a method similar to firebase's onBackgroundHandle method, i cannot ensure its execution all the times.

**Comment by ryanatev** [comment]
Interesting.   It worked for me on my galaxy s10 but haven't checked an
iPhone or other android devices yet.  I will try to record from my device.
 Not testing on a simulator or emulator.

**Comment by Paradoxu** [comment]
> Unfortunately is not possible, because flutter works mainly over dart, and to deal with this reply in background you need to handle it and do everything in native layer.
> 
> Also, on iOS background process are very limited. Even creating a method similar to firebase's onBackgroundHandle method, i cannot ensure its execution all the times.

Doesn't flutter support background processes now? It would be nice if we could pass a callback function to be executed when the user interacts with the notification and run that code on background instead of bringing the app to foreground just to perform "simple" actions.

**Comment by tek08** [comment]
[Local Notifications](https://github.com/mitchhymel/local_notifications)  used to be able to handle this, so I'm guessing it's still possible?  Am trying to see what I can learn about how it's done, but I'm no expert in Swift/Android background processes.

**Comment by rafaelsetragni** [comment]
Im working on it right now on [Notification's isolates git branch](https://github.com/rafaelsetragni/awesome_notifications/tree/notifications-isolates).

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
