### ISSUE TITLE
App crashed in iOS

### ISSUE THREAD

**Issue by ghost** [rafaelsetragni/awesome_notifications#182]
app crashed when swipe left to right on notification in iOS. i received response **null**.

```
iOS: 12.4.9

  awesome_notifications: #^0.0.6+7
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: fbee982

Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
Dart version 2.13.0
Xcode 12.3, Build version 12C33
CocoaPods version 1.10.1
```
///////////////////////////////////

 ```
 line no: 130
  
@available(iOS 10.0, *)
    public func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        
        guard let jsonData:String = response.notification.request.content.userInfo[Definitions.NOTIFICATION_JSON] as? String else {
                
            if(SwiftAwesomeNotificationsPlugin.debug){
                debugPrint("Received an invalid awesome notification action content. Notification action ignored.")
            }
            
            
            if(originalUserCenterDelegate != nil && originalDelegateHasDidReceive){
                originalUserCenterDelegate!.userNotificationCenter!(center, didReceive: response, withCompletionHandler: completionHandler)
            }
            else {
                completionHandler()
            }
            return;
        }
        
        var userText:String?
        if let textResponse =  response as? UNTextInputNotificationResponse {
            userText =  textResponse.userText
        }
        
        receiveAction(
            jsonData: jsonData,
            actionKey: response.actionIdentifier,
            userText: userText
        )
        
        completionHandler()
    }
```

**Comment by jonas-zebari** [comment]
I am encountering the same thing. @hardik-weenggs Have you found any solution? :)

**Comment by Jeffy503** [comment]
me too facing that same problem, did any one got any solution... :/ ?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
