### ISSUE TITLE
Daily notification with different title and body

### ISSUE THREAD

**Issue by marekmasek** [rafaelsetragni/awesome_notifications#190]
Is it possible to have daily notifications at the same time with different title and body?
Now I'm sending notifications from FCM every day with random title and body, but I would like to switch to local notifications, because they will be shown when the device is offline. I have a list of possible titles and bodies, which should be selected randomly.

**Comment by rafaelsetragni** [comment]
Unfortunately not, especially on iOS.
What you can do is to create a new notification with same ID. The old one will be replaced, even a scheduled.

**Comment by madd-project** [comment]
You have to take time to understand IDs and Also Please use them, 

I also had those issues. But The Community of Awesome Notification is so awesome, they told me to use IDS, when I used IDs, I never had the problem with anything..

![ce0ad6338005d3b4637f2c98cf96fdf7a89fc5ae230c3153e0e682c9d2dd0c15.0.png](https://user-images.githubusercontent.com/64954854/121455541-472e7f00-c9c2-11eb-9b8f-9eda67ce839f.png)

**Comment by PhilipPurwoko** [comment]
> Unfortunately not, especially on iOS.
> What you can do is to create a new notification with same ID. The old one will be replaced, even a scheduled.

@rafaelsetragni So, does this mean I must create a background process that create a new notification daily ?

**Comment by rafaelsetragni** [comment]
Is an valid solution. But keep in mind that you cannot ensure the time execution on iOS for background process. So i suggest to you to schedule a least a week in the future to certify the correct updates in case Apple put your app in background suspended mode.

**Comment by PhilipPurwoko** [comment]
Understood. This library is very easy and simple to use, and I loved it. But, may I ask, can [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) library able to create daily notifications at the same time with different title and body and overcome this problem ?

**Comment by PhilipPurwoko** [comment]
Understood. This library is very easy and simple to use, and I loved it. But, may I ask, can [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) library able to create daily notifications at the same time with different title and body and overcome this problem ?

**Comment by rafaelsetragni** [comment]
No. flutter_local_notifications definitely can't do it, since it's a more limited library than awesome_notifications.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
