### ISSUE TITLE
Can't initialize Awesome Notifications

### ISSUE THREAD

**Issue by Surk217** [rafaelsetragni/awesome_notifications#195]
hello,
i get this error when building my app:

> E/flutter (11249): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: **'package:awesome_notifications/src/awesome_notifications_core.dart': Failed assertion: line 142 pos 14:'BitmapUtils().getMediaSource(defaultIcon) == MediaSource.Resource': is not true.**
> E/flutter (11249): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (11249): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (11249): #2      AwesomeNotifications.initialize (package:awesome_notifications/src/awesome_notifications_core.dart:142:14)
> E/flutter (11249): #3      main (package:snozzy/main.dart:19:26)
> E/flutter (11249): <asynchronous suspension>

Then when i try add scheduled notification it wont let me.

pls help

**Comment by burakcbdn** [comment]
Did you supplied the icon when initializing?
Can you share your initialization code please.

**Comment by Surk217** [comment]
@burakcbdn I did it, I don't know if I'm doing it right though...

`AwesomeNotifications().initialize("C:/src/snozzy/android/app/src/main/res/drawable/notification_icon.png", [
    NotificationChannel(
        channelKey: 'snoozy_notifications',
        channelName: 'Snoozy notifications',
        channelDescription: 'Notification channel for Snoozy app',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white)
  ]);`

**Comment by nietsmmar** [comment]
I think you can't set your icon like that.

you should do it like this `resource://drawable/ic_notifications`

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
