### ISSUE TITLE
Does this package support Android FOREGROUND_SERVICE?

### ISSUE THREAD

**Issue by bagintz** [rafaelsetragni/awesome_notifications#197]
I am looking for a mature library that also supports the foreground service use of notifications as shown here:

https://developer.android.com/guide/components/foreground-services

**Comment by EPNW** [comment]
Have you found a solution to this? I also need a foreground service and it would be nice to combine it with this package instead of using an other package that also does the notificaiton stuff, I don't want to end up with 2 API's for the "same" (or related) things.

**Comment by EPNW** [comment]
We decided to write an own plugin for android forground services whichs API is based on that of awesome_notifications, maybe you want to take a look [here](https://pub.dev/packages/android_foreground_service_with_awesome_notifications).

**Comment by rafaelsetragni** [comment]
Why do not fork this project and send me a new version with this feature implemented?

**Comment by EPNW** [comment]
The reason for making an own package and not an PR in the first place is the following:
An Android foreground service inherently depends on notifications and can not exist wihtout a notification, but notifications can exist without a foreground service.
So I thought you might not like the thought of "bloating" this plugin with a functionallity that is not necessary for notifcations.
But If that's fine for you I will gladly make a PR 😄 (I guess it will arrive on monday).

**Comment by rafaelsetragni** [comment]
No problem! Your strategy makes sense. I agree with you.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
