### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by itssidhere** [rafaelsetragni/awesome_notifications#2]
Can we have an option like flutter_local_notification that if the channel doesn't exist create new one?

**Comment by rafaelsetragni** [comment]
The channels appears on android´s page configuration as you created it. Do you really want to your clients to go to your app configuration page and read some default message channel on it? Just to not describe it typing 5 lines on your app?

And if the plugin creates a channel on the fly, in case you miss the notification channel before create the notification itself, that could open a breach to mess up your app, and even worst, at the eyes of your users.

Let´s supose you send a notification with a different channel name, that does not exists programaticaly on your app, because you commited a mistake, or even because you do not called the correct method previously. If the pluggin creates the respective channel on the fly, you could end with a lot of messy channels, without description, on your application, and that will be completely openned to everyone sees it on your app page, inside Android´s config.

![Screenshot_1599769722](https://user-images.githubusercontent.com/40064496/92800566-2ed5f900-f38b-11ea-9400-d6106b0fc50e.png)
![Screenshot_1599769707](https://user-images.githubusercontent.com/40064496/92800570-30072600-f38b-11ea-94b9-9be65af6df1d.png)


The programaticaly creation of  a channel forces a good pratice to know at project level, all the channels that your app may use.

But its not limited to create all the channels only on initialization method. You can create a new channel, erase it or even update all of then, at any momment of your app, using the command bellow:


```
  AwesomeNotifications().setChannel(
      NotificationChannel(
        channelKey: 'channel_on_the_fly',
        channelName: 'A new fresh notification channel',
        channelDescription: 'This channel could be created at any moment of your app',
        channelShowBadge: false
      )
  );
```
