### ISSUE TITLE
 DefaultRingtoneType.Ringtone is not working.

### ISSUE THREAD

**Issue by muneebahmad0600** [rafaelsetragni/awesome_notifications#209]
I am trying to make a incoming call like UI. when I receive a call from FCM i wanna show a notification which will play the default ringtone of the user so the user realizes he is receiving a call. 
Please tell me that this package can do that.  right now its not working. There is not a single sound when I receive the notification.
also can we not dismiss a notification after a certain amount of time?

**Comment by muneebahmad0600** [comment]
This is the Notification Channel that i am using.

`
NotificationChannel(
            channelKey: 'call_channel',
            channelName: 'Call notifications',
            channelDescription: 'Notification channel for Call',
            defaultColor: primaryColor,
            ledColor: Colors.red,
            enableVibration: true,
            playSound: true,
            importance: NotificationImportance.Max,
            soundSource: 'resource://raw/res_morph_power_rangers',
            defaultRingtoneType: DefaultRingtoneType.Ringtone,
            vibrationPattern: highVibrationPattern,
            enableLights: true,
          )`

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
