### ISSUE TITLE
How to use MediaPlayer layout and control with notification?

### ISSUE THREAD

**Issue by YashMakan** [rafaelsetragni/awesome_notifications#216]
Kindly help! I am using [audioplayers](https://pub.dev/packages/audioplayers) flutter package to play audio but the package does not support notification for both android and ios. I want to implement the media player using `awesome_notifications`. Kindly help me with how to do that? unable to find any documentation related to that...
Thanks

**Comment by YashMakan** [comment]
in short, how can I implement this media player notification and integrate it with audioplayers package. 
![Screenshot 2021-06-30 023720](https://user-images.githubusercontent.com/70023200/123867663-40a18080-d94c-11eb-9c74-99a0194e838a.png)

**Comment by quikbeam** [comment]
@YashMakan I second this would like to see an example of NotificationLayout.MediaPlayer, if you figure this out please share.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
