### ISSUE TITLE
IOS: APNS device token not set before retrieving FCM Token for Sender ID '<>'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

### ISSUE THREAD

**Issue by dhruv048** [rafaelsetragni/awesome_notifications#219]
Hey, thanks for the awesome package.
Works like a charm in android, but i am getting this issue on IOS. 

> APNS device token not set before retrieving FCM Token for Sender ID '458258671137'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

when trying to retrieve APNS token through 
`FirebaseMessaging.instance.getAPNSToken().then((String token) {
        print(token);
      });`
it returns null.
i have followed all steps shown in [https://firebase.flutter.dev/docs/messaging/apple-integration](url).

what exactly am i missing, can you please look into this matter.
Thanks,

**Comment by rafaelsetragni** [comment]
I recommen you to go on `firebase_messaging` github’s plugin to search a solution to your problem.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
