### ISSUE TITLE
Scheduled local notification were not fired when app is force closed

### ISSUE THREAD

**Issue by ericta** [rafaelsetragni/awesome_notifications#221]
I tried the example app from my Android device(One Plus), I schedule a notification by next 5 mins base on local timezone. Then I force close the app, and the notification never came(it worked on IOS in the same case). I don't know if the library is covering this case for the Android version, or I just missed any required setup step?
Thanks sir!

**Comment by rafaelsetragni** [comment]
How do you forced the app to close?

**Comment by ericta** [comment]
![206714000_169062988482599_8149944755143776049_n](https://user-images.githubusercontent.com/1949158/124856180-45150b80-dfd4-11eb-88de-4b1873a1749f.jpg)

I "Clear all" app stacks, or just swipe up only "Awesome Notification" example app

**Comment by ericta** [comment]
do u have any ideas about it, @rafaelsetragni ?

**Comment by rafaelsetragni** [comment]
I guess is because of something like that:

[Alarm Manager SetRepeating is not working in background and app got killed](https://social.msdn.microsoft.com/Forums/en-US/6e0d306d-7cbc-4085-9524-afcc4532e82c/alarm-manager-setrepeating-is-not-working-in-background-and-app-got-killed?forum=xamarinforms)

But I didn't have time yet to verify this. That error could happens depending of what android distribution are running `Alarm Manager`

**Comment by kociubin** [comment]
I'm seeing the same behavior.  It only happens on Android--iOS is OK. 

As a workaround, I'm saving my notifications to SharedPrefs and re-creating them on startup if I detect that they've been cancelled by the OS.  You can examine AwesomeNotifications().listScheduledNotifications() to see if your notifications are still scheduled. 

This behavior should be added to the readme as it can lead to some difficult-to-find bugs.  It's not uncommon for people to FC their apps.

**Comment by mzl1988** [comment]
I'm seeing the same behavior     huawei

**Comment by rafaelsetragni** [comment]
I tested it on version 0.6.19 with this simple example and it scheduled perfectly.
I've shared the example on github so you can clone and test it yourself:

https://github.com/rafaelsetragni/issue_285

**Comment by mzl1988** [comment]
> 我用这个简单的例子在0.6.19版本上测试了它，它完美地安排好了。我已经在github上分享了这个例子，所以你可以自己克隆和测试它：
> 
> https://github.com/rafaelsetragni/issue_285

Tested for many times, android can't receive notification when kill app
![image](https://user-images.githubusercontent.com/11645762/145511589-d9183c7e-27bc-4ab7-b642-63bce4c0cf2d.png)

**Comment by rafaelsetragni** [comment]
> Tested for many times, android can't receive notification when kill app
> 
> ![image](https://user-images.githubusercontent.com/11645762/145511589-d9183c7e-27bc-4ab7-b642-63bce4c0cf2d.png)
> 
> 

Please, set the debug option to true on the initialization method and send me here your logcat (the log of your device)

**Comment by mzl1988** [comment]
> > 经过多次测试，Android在杀死应用程序时无法收到通知
> > ![image](https://user-images.githubusercontent.com/11645762/145511589-d9183c7e-27bc-4ab7-b642-63bce4c0cf2d.png)
> 
> 请在初始化方法上将调试选项设置为true，并将您的logcat（您设备的日志）发送到此处。

After testing Huawei many times, Xiaomi has the same problem

**Comment by mzl1988** [comment]
> logcat
[logcat.txt](https://github.com/rafaelsetragni/awesome_notifications/files/7709390/logcat.txt)

**Comment by mzl1988** [comment]
> > 经过多次测试，Android在杀死应用程序时无法收到通知
> > ![image](https://user-images.githubusercontent.com/11645762/145511589-d9183c7e-27bc-4ab7-b642-63bce4c0cf2d.png)
> 
> 请在初始化方法上将调试选项设置为true，并将您的logcat（您设备的日志）发送到此处。
[logcat.txt](https://github.com/rafaelsetragni/awesome_notifications/files/7709392/logcat.txt)

**Comment by anil-sookshum** [comment]
We are facing similar issue on **OnePlus 5**. 

Tested with other devices i.e "Mi Note 5 pro", "Moto E4 Plus" and "Samsung note 9"  and it is working fine on them in all states i.e Foreground, background and Killed. Only issues seems to be in OnePlus 5.

**Example App test results screen recordings**

[RedMi Note 5 Pro Test screen recording ](https://drive.google.com/file/d/1zX6dBSlYb6TGIMhcr2aKpAG0zmEBq-Cr/view?usp=sharing)
[OnePlus Test screen recording]( https://drive.google.com/file/d/1CEwy1jlxUrZegPSLb30uaExrc4sS5Vlg/view?usp=sharing)

OnePlus Android version **9**
RedMi Note 5 Pro Android version **9**
Samsung Note 9 Android version **10**
Moto E4 Plus Android version: **7.1.1**


Flutter version: **Channel stable, 2.8.1** 
Machine:  **macOS 11.5.1 20G80 darwin-x64**

**iOS**: Working fine on all three states Foreground, Background and Killed.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
