### ISSUE TITLE
Showing notification until user do something

### ISSUE THREAD

**Issue by benyaminbeyzaie** [rafaelsetragni/awesome_notifications#222]
Hey
I want to make a notification for incoming call using this library I can add to action button for handling accept or reject call but I want to show this notification on screen until user accept or reject the call but normally user can see the notification if he opens the notification bar... how can I implement this? Is there any feature to do that?

**Comment by mapacheverdugo** [comment]
According to [`awesome_notifications/lib/src/awesome_notifications_core.dart` ](https://github.com/rafaelsetragni/awesome_notifications/blob/888c957f306bd0234c5a808f872ed03569464762/lib/src/awesome_notifications_core.dart), you can `dismiss` a notification by ID. Also you can check `cancelSchedule`, `dismissAllNotifications`, `cancelAllSchedules` and `cancelAll` method. 

https://github.com/rafaelsetragni/awesome_notifications/blob/888c957f306bd0234c5a808f872ed03569464762/lib/src/awesome_notifications_core.dart#L419-L443

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
