### ISSUE TITLE
[iOS] Action buttons are removed when app is killed and reopened.

### ISSUE THREAD

**Issue by flytosowmya** [rafaelsetragni/awesome_notifications#227]
Hi, I found this issue yesterday and I would like to know is there anybody who faced the same. 

iOS -  I scheduled the notification and notification is created with action buttons. After killing the app, button remains but when reopening the app, the notification is present but the buttons are removed for all notifications. 

Attached the video for reference - [click_here](https://drive.google.com/file/d/169QHH8CyYMzVUOlsMnx15AGnaea4et0R/view?usp=sharing)

I found this issue in iOS only and I checked in Android , it is working fine.

Thank you so much for the Awesome notifications and I am amazed by its features.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
