### ISSUE TITLE
Crashes on Android SDK 23 and below because of Guava

### ISSUE THREAD

**Issue by alcrus** [rafaelsetragni/awesome_notifications#230]
If awesome_notification is used together with other packages which use Guava library internally on Android, for example BetterPlayer / ExoPlayer / etc., App will crash on Android devices with SDK 23 and below when BetterPlayer is initialized.

The reason is awesome_notifications uses wrong Guava flavor.
```
dependencies {
    implementation "com.google.guava:guava:30.1-jre"
```

According to Guava documentation https://github.com/google/guava "**com.google.guava:guava:##.#-android**" should be used instead.

> Guava comes in two flavors.
>
>The JRE flavor requires JDK 1.8 or higher.
>If you need support for JDK 1.7 or Android, use the Android flavor. You can find the Android Guava source in the android directory.

Replacing Guava solves the problem.

Stack traces can be different, exception always NoClassDefFoundError, one of the examples:

Fatal Exception: java.lang.NoClassDefFoundError
com.google.common.base.CharMatcher

com.google.common.base.Splitter.on (Splitter.java:127)
com.google.android.exoplayer2.extractor.mp4.SefReader.<clinit> (SefReader.java:92)
com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.<init> (Mp4Extractor.java:186)
com.google.android.exoplayer2.extractor.DefaultExtractorsFactory.addExtractorsForFileType (DefaultExtractorsFactory.java:376)
com.google.android.exoplayer2.extractor.DefaultExtractorsFactory.createExtractors (DefaultExtractorsFactory.java:312)
com.google.android.exoplayer2.source.BundledExtractorsAdapter.init (BundledExtractorsAdapter.java:70)
com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load (ProgressiveMediaPeriod.java:1027)
com.google.android.exoplayer2.upstream.Loader$LoadTask.run (Loader.java:417)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)

**Comment by rafaelsetragni** [comment]
Thank you so much for this tip. I'm totally agree with you.

Do you wanna fork this project and send me this fix? Otherwise, don't worry. I gonna fix it by myself later.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
