### ISSUE TITLE
Compatibility awesome_notification and workmanager - Not Working

### ISSUE THREAD

**Issue by Abhis33** [rafaelsetragni/awesome_notifications#231]
Works in iOS but not on android -

Error -
W/FlutterJNI(17550): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: awesome_notifications. Response ID: 0

Package Versions -
awesome_notifications: ^0.0.6+9
workmanager: ^0.4.1

@rafaelsetragni 
Similar to https://github.com/rafaelsetragni/awesome_notifications/issues/174 - Issue#174

**Comment by niypoo** [comment]
I'm facing this issue too , did you find what's wrong ?

**Comment by Bes79** [comment]
Same issue

**Comment by duyhuynh258** [comment]
I also have this issue with package versions:
awesome_notifications: ^0.6.19
workmanager: ^0.4.1

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
