### ISSUE TITLE
Feature Request: Execute action on Default button type but leave app in background / terminated 

### ISSUE THREAD

**Issue by timosturm** [rafaelsetragni/awesome_notifications#236]
It would be nice to be able to handle the actions specified for ActionButtons without bringing the app to foreground.

**Comment by rafaelsetragni** [comment]
Im working on it right now on [Notification's isolates git branch](https://github.com/rafaelsetragni/awesome_notifications/tree/notifications-isolates).

**Comment by siiger** [comment]
And for tapping on notification also!!!  It would be nice to be able to handle  without bringing the app to foreground

**Comment by omarsherifz** [comment]
is this issue solved now?

**Comment by rafaelsetragni** [comment]
Version 0.7.0

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
