### ISSUE TITLE
[iOS] Notifications not displayed iOS 14.7.1

### ISSUE THREAD

**Issue by Glexium** [rafaelsetragni/awesome_notifications#239]
The notifications are not displayed on an iPhone with iOS 14.7.1, on an Android (physical device) and simulator are working fine, no error message, except:
[connection] nw_endpoint_handler_set_adaptive_read_handler [C2.1
142.250.68.106:443 ready channel-flow (satisfied (Path is satisfied), viable,
interface: en0, ipv4, dns)] unregister notification for read_timeout failed
But I don't know if it's related or not, I tried debug and release mode.

**Comment by Glexium** [comment]
Yes, I already tried that, I found something weird, if I receive a notification from firebase, Awesome Notifications works as expected.

**Comment by rafaelsetragni** [comment]
> 
> 
> The notifications are not displayed on an iPhone with iOS 14.7.1, on an Android (physical device) and simulator are working fine, no error message, except:
> [connection] nw_endpoint_handler_set_adaptive_read_handler [C2.1
> 142.250.68.106:443 ready channel-flow (satisfied (Path is satisfied), viable,
> interface: en0, ipv4, dns)] unregister notification for read_timeout failed
> But I don't know if it's related or not, I tried debug and release mode.

This error is an network error.

> 
> 
> Yes, I already tried that, I found something weird, if I receive a notification from firebase, Awesome Notifications works as expected.

I have no idea of what you did. Can you share with us a simple app example with this issue?

**Comment by Glexium** [comment]
This inside onTap:
AwesomeNotifications().createNotification(
    content: NotificationContent(
        id: Random().nextInt(2147483647),
        channelKey: 'default',
        notificationLayout: NotificationLayout.BigText,
        title: 'title',
        body: 'body',
    ),
);
This is not displayed on my iPhone 8 Plus iOS 14.7.1 but it worked before, I have a similar code to display notification from firebase using FirebaseMessaging.onBackgroundMessage and FirebaseMessaging.onMessage, I followed all the instructions to set this up, and it works correctly each time that I receive a push notification but not when I use onTap for a local notification, but only in that iOS version.

**Comment by rish07** [comment]
I am facing a similar error, @Glexium were you able to solve it?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
