### ISSUE TITLE
How to catch button action in notification

### ISSUE THREAD

**Issue by Dan-Crane** [rafaelsetragni/awesome_notifications#244]
Hi! Thanks for the great library ☺️

What are you think, how to catch button intent in the native side, when user tap on notification button?

(in Android)
When user tap on notification button, i want to execute dart code, even when app is off 
With the stream (`AwesomeNotifications().actionStream`) it is impossible to implement when the application is closed.

I have an idea: for this i need to create a receiver that will catch button intent, [and run flutterEngine](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124), but i don't understand how to catch

**Comment by saharvx9** [comment]
> Hi! Thanks for the great library ☺️
> 
> What are you think, how to catch button intent in the native side, when user tap on notification button?
> 
> (in Android)
> When user tap on notification button, i want to execute dart code, even when app is off
> With the stream (`AwesomeNotifications().actionStream`) it is impossible to implement when the application is closed.
> 
> I have an idea: for this i need to create a receiver that will catch button intent, [and run flutterEngine](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124), but i don't understand how to catch

https://github.com/rafaelsetragni/awesome_notifications/issues/242

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
