### ISSUE TITLE
on iOS repeating notifications get cancelled if displayed with app Paused

### ISSUE THREAD

**Issue by kociubin** [rafaelsetragni/awesome_notifications#246]
This issue only occurs on iOS.  It works properly in Android.  This makes repeating calendar notifications unusable for common purposes on iOS. 

ISSUE:
-if a repeating Calendar notification is displayed while the app is in a paused state (i.e. minimized) the notification gets cancelled.  I expect the notification to be kept and repeated on subsequent day (which doesn't happen).  Note that if the notification is displayed while the app is in the foreground then it is kept and repeated.  

TO REPRODUCE: (on iOS) 
-Create a repeating calendar notification like this:
AwesomeNotifications().createNotification(
        content: NotificationContent(
          id: 1
          channelKey: 'basic_channel',
          title: 'some title'
          body: 'notification body'
        ),
        schedule: NotificationCalendar(repeats: true, hour: 11, minute: 10));
 
-Minimize the app (i.e. launch another app or go to the launcher)
-Examine the contents of AwesomeNotifications().listScheduledNotifications().  Notice that the previously scheduled repeating notification is no longer scheduled.  

Is there a workaround?  My goal is to schedule a daily notification that fires at the same, predetermined time every day.

**Comment by prjmax** [comment]
I'm having the same issue... any solution?

**Comment by kociubin** [comment]
As a workaround, every time I schedule a notification using awesome_notifications I also save the info in Shared Preferences.  Then, every time the app starts or is resumed, I recheck to make sure all of the notifications are still enabled in awesome_notifications and recreated them if they got cancelled for some reason.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
