### ISSUE TITLE
Minimize app and keep foreground service running when user swipes up to remove app.

### ISSUE THREAD

**Issue by am2074** [rafaelsetragni/awesome_notifications#248]
In other packages, I have noticed that when a foreground service is running and the user swipes up to close it, the android apps are minimized, and once a user opens the app manually or clicks on the notification for the foreground service they are brought back to where they previously were. However, in this package, when the user swipes up on the app the service is terminated and the foreground service notification is removed, which does not happen with other packages. 

Is there a way to prevent the closing of the foreground service on swipe like the other foreground service packages? 

This is how I've seen it done with other packages: 

1. Wrap this  widget around the pertinent scaffold 
```
/// A widget that prevents the app from closing when a foreground task is running.
/// Declare on top of the [Scaffold] widget.
class WithForegroundTask extends StatefulWidget {
  /// A child widget that contains the [Scaffold] widget.
  final Widget child;

  const WithForegroundTask({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  _WithForegroundTaskState createState() => _WithForegroundTaskState();
}

class _WithForegroundTaskState extends State<WithForegroundTask> {
  Future<bool> _onWillPop() async {
    if (await FlutterForegroundTask.isRunningTask) {
      FlutterForegroundTask.minimizeApp();
      return false;
    }

    return true;
  }

  @override
  Widget build(BuildContext context) =>
      WillPopScope(onWillPop: _onWillPop, child: widget.child);
}


  /// Minimize the app to the background.
  static void minimizeApp() {
    // This function only works on Android.
    if (!Platform.isAndroid) return;

    _methodChannel.invokeMethod('minimizeApp');
  }

  /// Returns whether the foreground task is running.
  static Future<bool> get isRunningTask async {
    // It always returns false on non-Android platforms.
    if (!Platform.isAndroid) return false;

    return await _methodChannel.invokeMethod('isRunningService');
  }

```
2. When starting the foreground service it will invoke a `MethodChannel('foobar).invokeMethod('startForegroundService', options);`. So now that the foreground service has started no matter if the user swipes up on the app, the foreground service is still running. 

The problem appears that this package's  doesn't  perform the '.invokeMethod('startForegroundService' therefore closing the foreground service if the user swipes to close the app.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
