### ISSUE TITLE
Can I change the notification priority/importance?

### ISSUE THREAD

**Issue by purplecandy** [rafaelsetragni/awesome_notifications#25]
First of all thanks for this amazing simple notification package, the local_notification looks way too overcomplicated for my simple use case. Anyways is there any support to change notification property? My notifications aren't that important I was thinking if I could give them the lowest priority so they just silently slide into the notification tray.

**Comment by rafaelsetragni** [comment]
Thank you so much!

That's the idea. Offers a simple to learn and really flexible solution to send notifications on Flutter, which abstracts the complexity to send notification in different platforms and allows the developers  to think more on "what to do" than on "how to do".

**A**: Yes, you can. And the priority is converted automaticaly between the platforms and operational versions without you need to worry about whats the name of it in iOS, or if on web is different, etc.

Those configurations are applied over the notification's channel and there is two properties that i believe will be intersting to you:

1. Importance: is the importance to delivery and alert the user about a new notification. When the importance is higher, the OS will delivery your notification in any case, playing sounds and plays even if your device is low battery.

- **Default**: shows everywhere, makes noise, but does not visually intrude.
- **Higher**: shows everywhere, makes noise and peeks. May use full screen intents.
- **Low**: Shows in the shade, and potentially in the status bar (see shouldHideSilentStatusBarIcons()), but is not audibly intrusive.
- **Min**: only shows in the shade, below the fold. This should not be used with Service#startForeground(int, Notification) since a foreground service is supposed to be something the user cares about so it does not make semantic sense to mark its notification as minimum importance. If you do this as of Android version Build.VERSION_CODES.O, the system will show a higher-priority notification about your app running in the background.
- **None**: A notification with no importance: does not show in the shade.

2. Privacy: is the privacy level of your notifications in cases when your device is on lock screen, etc:

- **Public**: Show this notification in its entirety on all lockscreens
- **Secret**: Do not reveal any part of this notification on a secure lockscreen
- **Private**: Show this notification on all lockscreens, but conceal sensitive or private information on secure lockscreens

Example of how to define those two parameters in a NotificationChannel object:

```Dart
      NotificationChannel(
          channelKey: 'basic_channel',
          channelName: 'Basic notifications',
          channelDescription: 'Just a basic notification channel',
          defaultColor: Color(0xFF9D50DD),
          ledColor: Colors.white,
          defaultPrivacy: NotificationPrivacy.Private,
          importance: NotificationImportance.Max
      )
```

**Comment by NTA-trongpq** [comment]
@rafaelsetragni Although I was set importance: NotificationImportance.Max but alert not shows, only shows the icon on status bar.

**Comment by rafaelsetragni** [comment]
You need to reinstall your app to test new channels configuration.
