### ISSUE TITLE
iOS badge always increament from previous value

### ISSUE THREAD

**Issue by kishangohel** [rafaelsetragni/awesome_notifications#254]
If we set in NotificationChannel
`channelShowBadge: true`
in iOS if user tab on notification and badge is not removed automatically and for every new notification counts goes high and high.

`NotificationChannel(
      channelKey: CH_KEY_GENERAL,
      channelName: CH_NAME_GENERAL,
      channelDescription: CH_DESC_GENERAL,
      importance: NotificationImportance.Default,
      playSound: true,
      enableLights: true,
      groupKey: GRP_KEY_GENERAL,
      channelShowBadge: true,
    )`

`
AwesomeNotifications().createNotification(
      content: NotificationContent(
        title: payload.title,
        body: payload.content.replaceAll('\n', '<br>'),
        notificationLayout: NotificationLayout.BigText,
        payload: payload.toJson(),
        id: (DateTime.now().millisecondsSinceEpoch / 1000).round(),
        channelKey: CH_KEY_GENERAL,
        autoCancel: true,
        color: ColorValues.primaryColor,
      ),
    );
`

**Comment by rafaelsetragni** [comment]
Of course. You need to reset or decrement the value of the badge by yourself, because you can adopt many different strategies to use the badge counter.

You can just want to call the user, like the netflix app wich does clear the badge only when the user goes to the app. Or you can do it only when it goes to the notification page, or when the user opens the notification details page, etc.

The only thing that the badge does automaticaly is to increment the counter for notifications on channels with badges activated, because throung Flutter is impossible to do it when the notification arives while your app is terminated / killed.

**Comment by kishangohel** [comment]
Ok got it.
i used flutter_app_badger package to clear notifications. after reset badge is cleared but when new notification created again badge count not start from zero it's increament count from last badge count.
e.g last count was 10 and i reset using 'flutter_app_badger' so badge is clear and now if new notification created then it shows count 11 instead of 1.

Can you please confirm this behaviour is default?

Can you please suggest a way to reset badge?

**Comment by kishangohel** [comment]
@rafaelsetragni 
I tried badge handing with reference of your example.
Thanks it's really a good package with less code.
