### ISSUE TITLE
InputField button generate a new notification after tapping on "SEND"

### ISSUE THREAD

**Issue by gbaccetta** [rafaelsetragni/awesome_notifications#255]
Hello,

first of all thank you for the great work on this package ! It made me save a lot of time and the result is beautiful!

I've a small issue with the inputField button. When I click on the send button, the actio callback is called just fine and the action and content retrieved correctly. However as soon as I click on the notification (testing on android for now) the notification get dismissed, but a new equivalent one is generate as soon as the first one is dismissed.
The new one is generated before any of the stream callback is called.

Here it is the notification payload generated trough FCM Admin sdk:

```typescript
const payload = {
    data: {
      type: type,
      content: JSON.stringify({
        payload: {
          type: type,
        },
        id: notificationId,
        channelKey: 'team_updates',
        title: title,
        body: body,
        largeIcon: largeIcon,
        notificationLayout: 'Messaging',
        displayOnForeground: true,
        displayOnBackground: true,
        showWhen: true,
        autoCancel: true,
      }),
      // add a reply button only if the message was a text (spread operatior)
      ...(type == 'TEXT' && {
        actionButtons: JSON.stringify([
          {
            key: 'REPLY',
            label: 'REPLY',
            autoCancel: true,
            buttonType: 'InputField',
          },
        ]),
      }),
    },
  };
```
If I tap on the notification instead, it get dismissed alright.

**Comment by Dalinar651** [comment]
I have now tested my code on three different devices but only getting this issue on my Samsung device.

**Comment by gbaccetta** [comment]
Hello, somehow one answer I gave few days ago didn't get posted.
I'm indeed using a Samsung too.
Also the problem is coming from the parameter debug = true. Once you init awesome_notification without that, it worked fine for me. @rafaelsetragni I tried to understand where the problem is coming from but couldn't pinpoint something. So I'm not 100% sure either

**Comment by rafaelsetragni** [comment]
> 
> 
> I have now tested my code on three different devices but only getting this issue on my Samsung device.

This is very interesting!! I guess i know whats going on.

Since Android 9 (API 29), the remote input on notifications was modified to not be dismissible. Instead, a dialog box is displayed on screen, as bellow:

![image](https://user-images.githubusercontent.com/40064496/133328343-171be546-784b-41be-8250-48ef51f0ff0f.png)

As soon this form appears, the notification became programaticaly undismissible. The only workarround is to update the notification and after some milisseconds to dismiss it, as described on the topic bellow:
https://stackoverflow.com/questions/54219914/cancel-notification-with-remoteinput-not-working/56867575#56867575

It seems that some Android devices, which modifies the S.O., also modifies this strange reply behavior. Because of that, instead of update the notification and after that dismiss it, the first one is successfuly dismissed, but the update creates a new notification that become lost.

So, i gonna need to rethink how to deal with these undismissible replies, that not only change the default behavior between Android versions, but between brands and devices.

**Comment by gbaccetta** [comment]
Anyway, I encountered this issue only when the debug option is true.

**Comment by gbaccetta** [comment]
Hi @ralphvmo in the action Listener your `ReceivedAction` has two keys:
buttonKeyInput ↔ String --> The input received for exemple from the edit text
buttonKeyPressed ↔ String --> The key you have set in your notification payload for the button being pressed

Source: https://pub.dev/documentation/awesome_notifications/latest/awesome_notifications/ReceivedAction-class.html

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
