### ISSUE TITLE
notification as like whatsapp

### ISSUE THREAD

**Issue by ZeeshanJelani** [rafaelsetragni/awesome_notifications#256]
hi
i just want to know is their any way to show notification as like whatsapp. like when we get notification we get a stack or list on status bar(on lunch) or in app(on message)??

**Comment by rafaelsetragni** [comment]
Yes. Use the option to group notifications and sort then as you wish.

**Comment by ZeeshanJelani** [comment]
please provide me the source.

**Comment by rafaelsetragni** [comment]
In the project folder, there is a folder called example. There i put an complete example app of how to implement every notification type available.

**Comment by BlackStriker99** [comment]
![image](https://user-images.githubusercontent.com/40071991/132300585-a9683609-10d3-48a4-8ad9-546bfb95e19b.png)

I have tried to implement your code for group notification. But it is not grouping as whatsapp.

**Comment by rafaelsetragni** [comment]
But it seems exactly how whatsaap notifications works. Can you send to us an whatsapp example to demonstrate to us what you are looking for?

![image](https://user-images.githubusercontent.com/40064496/132749945-79af2670-4022-495d-bc41-e5ef16c8ab41.png)

**Comment by BlackStriker99** [comment]
Hii @rafaelsetragni  !! Thanks for the quick response. 
I was looking for something like this if the same conversation has multiple messages then it should group those messages into one conversation but in your example, **Little Jhonny** has sent multiple messages but all are having different notifications.

![processed (4)](https://user-images.githubusercontent.com/40071991/132805449-47420cf5-ed8c-48a0-8534-1a0bf56a1ae6.jpeg)

![processed (3)](https://user-images.githubusercontent.com/40071991/132805467-9f39e0b7-b932-4e81-b117-f3e36b93d8cc.jpeg)

**Comment by rafaelsetragni** [comment]
What you are looking for is something like this?

![image](https://user-images.githubusercontent.com/40064496/133694096-f36b8d27-8c9a-4a4d-be05-fa23bdca2675.png)

**Comment by ZeeshanJelani** [comment]
yes same like that.which package are you using

**Comment by BlackStriker99** [comment]
yes i am looking something like this !!

**Comment by LOCKEDFILE** [comment]
what's ETA?

**Comment by jrwenigma** [comment]
> What you are looking for is something like this?
> 
> ![image](https://user-images.githubusercontent.com/40064496/133694239-3c35e21a-bcd8-4941-b76f-b2f5da346791.png)

Hi there, great project you've made, are you able to share the source on how you achieved that?

**Comment by rafaelsetragni** [comment]
The full example app is inside the folder example. You can open it Nd run as any other flutter app.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
