### ISSUE TITLE
Add ability to add the subText to the notification

### ISSUE THREAD

**Issue by Pato05** [rafaelsetragni/awesome_notifications#258]
In the `flutter_local_notifications` package, you can add a subText label which is shown right after the app's title in the notification panel, it would be nice to be able to achieve the same with this plugin.

I saw in the Android code and that is possible by calling `builder.setSubText(...)`.

**Comment by rafaelsetragni** [comment]
Can you show me a print of this feature? I had never seen this.

**Comment by Pato05** [comment]
![immagine](https://user-images.githubusercontent.com/20874747/130324474-2991d642-8ca8-4bf1-a550-95eabafe6760.png)
Here, it is the "10 secs left" text here.

**Comment by rafaelsetragni** [comment]
Now i see it!
I gonna implement it and will be available on next release! Thank you so much for the tip!!

**Comment by Pato05** [comment]
> 
> 
> Now i see it!
> I gonna implement it and will be available on next release! Thank you so much for the tip!!

Thank you for that and thank you for such a quick answer!

**Comment by Pato05** [comment]
I'm sorry, I must've clicked the wrong button and I didn't notice

**Comment by Shadman12345** [comment]
Is it implemented now?

**Comment by rafaelsetragni** [comment]
Yes, it is since a long time ago. Use summary field.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
