### ISSUE TITLE
vibration pattern issue

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#26]
- Vibration pattern does not work. It always uses default patterns. plz check this.

- Code:
vibrationPattern:  Int64List.fromList([0, 1000, 500, 1000, 500, 1000])

/////
Device: Samsung m30s
Version: Android 10 (Q) 
/////

**Comment by rafaelsetragni** [comment]
After you create a notification channel, the only thing that could be updated is the name and the description.

Anything else (including the vibration pattern) only will be updated if you reinstall the app or if you destroy the original channel and creates a copy with a different channel key. Unfortunately this rule was defined by Android OS since Oreo version.

Try to do any of this alternatives and tell me if they change the vibration pattern.

**Comment by rafaelsetragni** [comment]
THere is a bug related to vibration patters.

In somehow dart cannot compare propertly a Type reference and a runtime from object. Because of that, the vibration pattern was discarted as invalid.

This bug will be fixed in the next release.

**Comment by rafaelsetragni** [comment]
Version 0.0.5 finally released! The vibration patter was finally fixed.

But you gonna need to protect your native resources against minification inserting the prefix "res_" in your image or sound file names. You can see more about it [here in the README file](https://github.com/rafaelsetragni/awesome_notifications#media-source-types).

Also i simplified the iOS installation. Please, update it if you pretend to use iOS too.

Call me here if you continue with issues on this new version.

**Comment by hardik-weenggs** [comment]
Thanks. 
i will check.
