### ISSUE TITLE
Progress bar not display on iOS (simulator)

### ISSUE THREAD

**Issue by ryanatev** [rafaelsetragni/awesome_notifications#260]
I am trying to execute the following notification but the notification just continuously pops up without a progress bar.  There is a new notification for each iteration of the progress.  Are progress bar notifications supported on iOS?  I used the same channel configuration in the example with the following create statement when a file is being uploaded.  I have not yet tested on an actual iOS device nor have I tested using the Android emulator or an Android device yet.

```
AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: event.taskId.hashCode,
            channelKey: 'progress_bar',
            title: 'Uploading in Background',
            body: 'Upload in progress...',
            progress: event.progress,
            notificationLayout: NotificationLayout.ProgressBar,
            locked: true,
            payload: {
              'file': 'filename.txt',
              'path': '-rmdir c://ruwindows/system32/huehuehue'
            },
          ),
        );
```

**Comment by rafaelsetragni** [comment]
I was unable to get the progress bar, media player, and inbox layouts to work on iOS because there is no such feature available at this time. What I plan to do (but honestly I'm not having enough time to) is create custom notification layouts to mimic these features on iOS.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by Ladeed** [comment]
so we don't able to show progress bar in ios?
