### ISSUE TITLE
Improve documentation about integrating `Firebase FCM` with this package

### ISSUE THREAD

**Issue by raulmabe** [rafaelsetragni/awesome_notifications#261]
First of all, very nice package! I love it and it was much needed for the flutter community, so really thank you! :heart:

## Problem
I was having trouble integrating `Firebase FCM` because of the documentation:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  AwesomeNotifications().initialize(
    'resource://drawable/res_app_icon',
    [
        // Your notification channels go here
    ]
  );

  // Create the initialization for your desired push service here
  FirebaseApp firebaseApp = await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(App());
}

// Declared as global, outside of any class
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {

  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print("Handling a background message: ${message.messageId}");

  // Use this method to automatically convert the push data, in case you gonna use our data standard
  AwesomeNotifications().createNotificationFromJsonData(message.data);
}
```
Afterwards the doc says

> Now, firebase messaging should work at any application lifecycle, for any supported platform

But after implementing these steps it didn't work at **every app lifecycle**; it did just work `onBackgroundMessage`. I had to include these two lines to include `onForeground` and `onActionReceived`:

   ```dart
 FirebaseMessaging.onMessage
        .listen((noti) => createNotificationFromJsonData(noti.data));
    FirebaseMessaging.onMessageOpenedApp
        .listen((noti) => createNotificationFromJsonData(noti.data));
```

Without these both lines the service wasn't full integrated. Even now I am doubtful about if I missed something. 

## Bonus question
I have implemented a `Repository` to be able to test the domain logic, but how could I test this repository? Do you have an idea?

**Comment by rafaelsetragni** [comment]
I'm going to drop `firebase_messaing` support because it's impossible to do full integration just using DART code.

I'm creating a new plugin to complement this one and receive notification events from Firebase. The new plugin is [awesome_notifications_fcm] (https://pub.dev/packages/awesome_notifications_fcm). But it's not over yet.

I'll follow your advice for creating the new README documentation, but since I don't have time to build the plugin, it will take a while to finish.

**Comment by gronka** [comment]
@rafaelsetragni
I'm working on an app where a core component is delivering notifications. It seems to me like `onMessage` and `onBackgroundMessage` capture most all of the use cases. Background policies can't really be modified, right? What use case does @raulmabe's solution fail to capture?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
