### ISSUE TITLE
Customizing notification

### ISSUE THREAD

**Issue by Dariusz-Pluta** [rafaelsetragni/awesome_notifications#262]
Add possibility to have notificationActionButton without label, i tried to make button with only icons inside and i cant cuz label cannot be null or empty :/ And it would be great if there was a possibility to position button like in Row with mainAxisAlignment, i mean center, spaceAround, spaceBetween etc, because i dunno how to move these buttons from left side of notification :/

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
