### ISSUE TITLE
getNextDate always parses data string as utc

### ISSUE THREAD

**Issue by marklester** [rafaelsetragni/awesome_notifications#263]
`awesome.AwesomeNotifications().getNextDate(schedule)` always parses the datestring returned as utc.

Say the schedules is 6am New york timezone. if you call that function it will return a Date in 6am utc time instead of new york time. and if you convert to toLocal it will be 2am New York time.

My guess is the string should be checked to see if it ends in a Z then parse to utc if not parse to a local time.

**Comment by rafaelsetragni** [comment]
It is not necessary to change the date format as the timestamp has already been passed with the calendar object. The problem is the priority, as you can convert the timestamp to dart or use another plugin to do the conversion.

Unfortunately, I won't have time to do this in the near future. But I agree with you that the ideal is datetime be converted.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
