### ISSUE TITLE
[Question] Android Alarm manager plus plugin

### ISSUE THREAD

**Issue by TheCarpetMerchant** [rafaelsetragni/awesome_notifications#264]
Is there any problem with using the android_alarm_manager_plus plugin and awesome_notifications together ?
All notifications will be created from the android_alarm_manager_plus Isolate ; Do i need to initialize awesome_notifications from this Isolate ? Will the callback on tap of a notification be called once the app is opened if it was closed ?
Any other stuff I need to know on this topic ?

Thanks.

**Comment by rafaelsetragni** [comment]
No, is not necessary to initialize it on isolate if you initialize the awesome inside the `main()` method. But i recommend you to wait for 0.7.0 version, because it will be 100% compatible with isolates.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
