### ISSUE TITLE
Why AwesomeNotifications().actionStream.listen called twice when trying replaying text on terminated FCM notification?

### ISSUE THREAD

**Issue by husen-hn** [rafaelsetragni/awesome_notifications#266]
when I replay some text in terminated app FCM notification that streamed contents twice.

(these codes worked without any problem when the app was in foreground or background but this happens when it is terminated)

```Dart
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
 
    showNotificationByAwesome(
        1, message.data['userName'], message.data['message']);

  await Firebase.initializeApp();
}
```

```Dart
Future<void> showNotificationByAwesome(
    int id, String username, String message) async {
  await AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: id,
        channelKey: 'foreground_notification',
        ticker: username,
        title: username,
        body: message,
        color: AppColors.primaryColor,
      ),
      actionButtons: [
        NotificationActionButton(
          key: 'REPLY',
          label: 'Reply',
          autoCancel: true,
          buttonType: ActionButtonType.InputField,
        ),
      ]);
}
```

```Dart
AwesomeNotifications()
        .actionStream
        .listen((ReceivedAction receivedNotification) async {
      if (!StringUtils.isNullOrEmpty(receivedNotification.buttonKeyInput)) {
        
        sendMessage(receivedNotification.buttonKeyInput) // here, I receive two message with same content 
        
      } 
});
```

**Comment by rafaelsetragni** [comment]
Unfortunately, is not possible to do a perfect integration with `firebase_messaging` throught Dart code. Is necessary to implement the firebase receive method and integrate it from scratch in native language. Since the begining of this plugin i try to integrate with oficial firebase plugin, trying by many ways, but is not possible.

Probably you are receiving twice because `firebase_messaging` also has a notification creation and receive method.

Im developing a complementary plugin to perfectly integrate firebase clound messaging services with Awesome Notifications, saving at most the device resources and allowing remotely to use all Awesome Notifications features, such as scheduling, action buttons, etc.

This new plugin will be finally release right after `awesome_notifications 0.0.7`
