### ISSUE TITLE
Can I set repeated-notification with start time?

### ISSUE THREAD

**Issue by sejun2** [rafaelsetragni/awesome_notifications#267]
I want repeated notification runs after start time. 
After I read the guideline, I can't find for this solution but schedule notification on exact time only once.
Is there any solution for this? 

Thank you

**Comment by rafaelsetragni** [comment]
Unfortunately not, because of iOS notifications that do not allow that kind of feature feature.
On the firsts iOS versions was possible to do this, but they took of that functionality by no reason.

But for Android you can fork this project and enable it by yourself. I already did all the implementations on native code to do this feature and even more. But because i need to delivery the same experience for both platforms, i had to disable it.

**Comment by sejun2** [comment]
Ooh that's a bad news. I got it.
Thank you for your kind reply!
