### ISSUE TITLE
Bad explanation

### ISSUE THREAD

**Issue by hekhy** [rafaelsetragni/awesome_notifications#268]
The whole problem comes because I was trying to implement my own function to the action buttons, but the surprise is that they do not even have an onTap property, and the buttonType property only receives an ActionButtonType that although if it executes an action anywhere it explains how to configure what you want me to do.
Nor what are the channelKey that we should put or if we can put what we want, nor what type of information to put in the payload (or how to use it or what it is for) or if it can also be what we want.
At least the only thing I've seen is a section where it tells you to look in the example project, as if it were so easy to find it ... Only in the home_page.dart there are 957 lines of code with which you can go crazy to find what what are you looking for.

At least they could explain a little each thing, since not all of us have 10 years as programmers to understand everything so easily.

I would like you to at least explain to me how to put the action that I want in each button.

Also say that in the example application, the button that says to show a notification with buttons and icons, does not work well since the String that is supposed to contain the path of the icon is not set. Nor does it explain if that path is from our assets or from the package itself or what.

That said, saying that the package is still good, it implements the notifications very easily, which Flutter could have done by default, but thanks to the creators. Too bad it is not so well explained, or at least in the way it is explained I do not understand.

**Comment by rafaelsetragni** [comment]
> The whole problem comes because I was trying to implement my own function to the action buttons, but the surprise is that they do not even have an onTap property, and the buttonType property only receives an ActionButtonType that although if it executes an action anywhere it explains how to configure what you want me to do.

The action handle and the other events are implemented with streams because im using the [Observer Pattern](https://en.wikipedia.org/wiki/Observer_pattern). But don't worry, im migrating right now to static methods to handle these events. It will be available on 0.0.7 version.

> Nor what are the channelKey that we should put or if we can put what we want, nor what type of information to put in the payload (or how to use it or what it is for) or if it can also be what we want.

I created the Channels based on the Android standard to create a kind of "pre-configured notifications groups". And i translate this behaviour to iOS to make it more easy, simple and fast to use by a library how target on make multiplatforms apps. This is one of the main philosofies of awesome_notifications: You don't need to adapt your business logic to each platform, the Awesome Notifications plugin creates a middle layer to make a simple view of everything, to you worry more about on "what to do" and not on "how to do".

> At least the only thing I've seen is a section where it tells you to look in the example project, as if it were so easy to find it ... Only in the home_page.dart there are 957 lines of code with which you can go crazy to find what what are you looking for.

![Hahahahahaha](https://c.tenor.com/_LkOeCdvgWoAAAAM/laughing-best.gif)

Hahahahahaha! I agree, but i did it to leave at least one real life example available to the community, and there is a LOT of features available for notifications. That way i believe you always have at least one example of how to do what youre planing to do with you Application, and you not gonna need to go outside on the internet find for answers or spend days of work to figure out how to do.

> At least they could explain a little each thing, since not all of us have 10 years as programmers to understand everything so easily.

Sorry for that. Maybe, because i had worked with programming for so long, i've became a little blind to understand how the other people, (that are starting right now) are going to see and intuitive understand how everything works. One of my goals with this plugin is to make everything simple to use by someone who are not a native developer. But sometimes i need to translate how the things works under the hood, and i understand that it can not be so easly by first time. I gonna try to do my best to improve the documentation on next time and i invite you to help me on that, if possible.
 
> I would like you to at least explain to me how to put the action that I want in each button.
> 
> Also say that in the example application, the button that says to show a notification with buttons and icons, does not work well since the String that is supposed to contain the path of the icon is not set. Nor does it explain if that path is from our assets or from the package itself or what.

Try to check out this incredible tutorial made by Ashley Novik, from [ResoCoder team](https://resocoder.com/). This tutorial cover the most common features available for Awesome Notifications. I believe that its gonna answer all your questions:

[![Flutter Awesome Notifications - Create Local Notifications With Ease](https://img.youtube.com/vi/JAq9fVn3X7U/0.jpg)](https://www.youtube.com/watch?v=JAq9fVn3X7U)

> That said, saying that the package is still good, it implements the notifications very easily, which Flutter could have done by default, but thanks to the creators. Too bad it is not so well explained, or at least in the way it is explained I do not understand.

Thanks! That's my goal!

![Chuck norris approves it](https://i.pinimg.com/originals/b4/d0/bc/b4d0bc7a0a9a9d6f34274e7be5eabfe1.gif)

**Comment by hekhy** [comment]
Hello again, I am glad of your response so mature accepting the constructive criticism that I tried to give you. Again I say that the package is a marvel, since before yours I was using another that could not put buttons, nor could put photos, or anything, just a simple notification, in addition to a lot of previous and post-project configuration so that it would not fail in the production phase, but your package is wonderful or better said awesome, as its name says, since it is only to initialize it and create the notification and voila it is perfect, and that is something that I love and admire, since it must have It has been difficult or at least I think so because I have looked for information on how to create these notifications by myself without using a package and the flutter documentation itself tells you to use firebase_messaging (in part I understand it since flutter is from google the same as firebase), but not all people want to make an application that uses firebase or in general that connects to the network, and that is very bad on its part, but your package helped a lot in that sense and I appreciate it.

After saying that the documentation actually what is explained is fine, it is simply what I comment, that there is not enough, as you say you have to understand that there are people who are new, and taking me as an example this is the The first programming language that I use and the first framework, so for me there are many new concepts and things that I get lost with. So I thought that at least I could tell you that it had to improve but just as I said the bad I said how good the package has.
But if you want my help for the documentation I can give it to you, but all you have to do is explain each function a little, that is, how it is initialized, how the notification is created (those first two are already there, but as a script to follow) , what properties the initialization has, and how to apply them, what properties the notification has and how to apply them as well, but above all to say that all this does not have to be so much in the readme of pub.dev which would also be good but in the documentation of the package itself putting the comments with the three bars "///" that are used and so when you put the mouse over each function it explains its use a little.

Really, if you need it, I offer you my help, just tell me in what, but you are the one who understands the package perfectly since you have created it, you should not have problems with it.

By the way, thanks for the video, I will watch it without a doubt, in fact the other day when I wrote you the error ticket I was looking for it and I found it, but I had not seen it yet because these days I have been busy, you know weekend and family . XD

Again I thank you and I repeat that the package is very good and do not think that I said it with bad intention if not with the intention of improving it.
