### ISSUE TITLE
Alarm clock

### ISSUE THREAD

**Issue by spacekestrel** [rafaelsetragni/awesome_notifications#269]
Is there any way to create full-screen notification like in alarm clocks?

**Comment by rafaelsetragni** [comment]
Can you provide me with an example of what this full screen notification is?

**Comment by spacekestrel** [comment]
Yes, sorry. What i meant is when the alarm is activated, the application and a specific screen are launched. 
Just like in regular alarm clock apps.

**Comment by sejun2** [comment]
> Yes, sorry. What i meant is when the alarm is activated, the application and a specific screen are launched.
> Just like in regular alarm clock apps.

It is possible, but it depends on OS which OEM provides.
Some phones can but others not.

**Comment by spacekestrel** [comment]
> 
> 
> > Yes, sorry. What i meant is when the alarm is activated, the application and a specific screen are launched.
> > Just like in regular alarm clock apps.
> 
> It is possible, but it depends on OS which OEM provides.
> Some phones can but others not.

Well...what is the implementation?

**Comment by rafaelsetragni** [comment]
Guys, i'm still don't know what a full-screen notification looks like. Do you have any screenshot or example to give to me?

**Comment by sejun2** [comment]
> Guys, i'm still don't know what a full-screen notification looks like. Do you have any screenshot or example to give to me?

You can find fullscreenintent from android developers. I think he want it but it can't now

**Comment by xennygrimmato** [comment]
@rafaelsetragni I think what @spacekestrel is trying to say is something like the following:
- Let's say you set an alarm using an alarm clock application to wake up the next morning.
- As soon as the time of the alarm hits, you are shown the current time and a few buttons like snooze / cancel alarm etc.

Would it be possible to achieve this behaviour using awesome_notifications?

[Notification image](https://forums-images.oneplus.net/attachments/558/558874-56dc9160a26d6d801bd18873152298ec.jpg)

**Comment by LogicNg** [comment]
Any updates?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
