### ISSUE TITLE
WebSockets Usage/Compatibility

### ISSUE THREAD

**Issue by tomassasovsky** [rafaelsetragni/awesome_notifications#272]
Hello, I wanted to ask if there is any way of running this plugin to connect to a WebSocket, keep it running on background, and show notifications on a socket instance. I was thinking about using Socket.io for this.

**Comment by rafaelsetragni** [comment]
Websockets increase network traffic a lot, because of heart beat packets.

Is it a good idea to apply this type of strategy to notifications? Firebase Cloud Message is always free and saves a lot of device traffic because it's Google's service that triggers the packet only when it's needed.

But it's totally possible to implement and integrate it easily with awesome notifications. Can you build a java method to handle websocket? I can do the integration.

**Comment by tomassasovsky** [comment]
I thought Push Notifications were based around WebSockets, but I guess I'll have to investigate a bit more about that.

What alternatives would you recommend for a NodeJS Server that'll have to send the notifications down to the Flutter app?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
