### ISSUE TITLE
Click on the notification when you app killed does not work at some times (local notification without fcm)

### ISSUE THREAD

**Issue by HassanBalousha** [rafaelsetragni/awesome_notifications#278]
Click on the notification when you app killed does not called actionStream , why?
note : not use fcm

**Comment by rafaelsetragni** [comment]
Im working with it right now. Take a look at https://github.com/rafaelsetragni/awesome_notifications/pull/257

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
