### ISSUE TITLE
Notification not getting

### ISSUE THREAD

**Issue by ghost** [rafaelsetragni/awesome_notifications#286]
after update version push notification not getting in android

**Comment by rafaelsetragni** [comment]
How did you implemented your push notifications?

**Comment by kcs-rahuljoshi** [comment]
I have used android platform and not getting push notifications in any device.

**Comment by rafaelsetragni** [comment]
And how did you implemented your push notifications? What version you used on last time that has worked?

**Comment by kcs-rahuljoshi** [comment]
every time i am getting when received push "D/FLTFireMsgReceiver(22245): broadcast received for message" but not received push notification. and i am using awesome_notifications:

**Comment by rafaelsetragni** [comment]
And how did you implemented your push notifications? What version you used on last time that has worked?

**Comment by kcs-rahuljoshi** [comment]
using awesome notification with firebase token and used version is awesome_notifications:

**Comment by rafaelsetragni** [comment]
I have a better idea. Create a small example project with the way that you implemented push notifications with awesome_notifications and share here on GitHub with us.

With only these few informations im not able to help you. Is too vague to figure out whats going on.

**Comment by kcs-rahuljoshi** [comment]
[flutter_awesome_notification.zip](https://github.com/rafaelsetragni/awesome_notifications/files/7207533/flutter_awesome_notification.zip)

I have created a small demo but still not getting push notifications I have added an attachment file so please check and give an update.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
