### ISSUE TITLE
Migrating from flutter_local_notifications to this plugin

### ISSUE THREAD

**Issue by th8m0z** [rafaelsetragni/awesome_notifications#287]
First of all, amazing work with the development of this plugin!
Currently my app is running with the flutter_local_notifications plugin and I was wondering if anybody has experience with migrating a live app to the awesome_notifications plugin. 

Is it as simple as just keeping the notification channel ID's the same or are there other things I have to keep in mind?

Thank you!

**Comment by serkanince** [comment]
> Everything is automatically managed by plugin, but under the hood there is a lot of changes that make awesome_notifications not being able to work at same time with flutter_local_notifications, and the Android channel's managment is one of then.
> 
> These changes make it possible for awesome_notifications to have much more features than flutter_local_notifications.
> 
> To migrate the plugins, i believe there is no much thing to do, taking in note that awesome_notifications is pretty more simple and easly to use than flutter_local_notifications, since awesome_notifications act like a middleware, and flutter_local_notifications act like a native code translator.

Maybe a migration guide could be made from **flutter_local_notifications** to **awesome_notifications**
. In this way, it becomes a guide for facilitating the transition of people.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
