### ISSUE TITLE
Only one local notification is displayed in OS tray

### ISSUE THREAD

**Issue by scalz** [rafaelsetragni/awesome_notifications#294]
Hello,

I just noticed recently I only get the last local notification in the OS tray. Actually I don't remember if it was like this before..

This is a part of the payload I send from postman (of course I change notification id each time I send one)
![Capture2](https://user-images.githubusercontent.com/12609100/135996585-c037669d-b417-470e-869e-665d83b87bb1.PNG)

And this is what I get in android emulator, when I use both notification+data keys (for debugging)
![Capture](https://user-images.githubusercontent.com/12609100/135999063-b9bf73ac-a57c-4b0a-bff9-3f4002d0781a.PNG)
Two fcm notif are displayed but only one local.

I'm not cancelling any notification in my test, and in firebaseMessagingBackgroundHandler, I simply call 
await AwesomeNotifications().createNotificationFromJsonData(message.data);

I'm probably doing something wrong.. gonna dig a bit more.
Any ideas please or is it the right behaviour (only one local notification displayed) ? 

Edit: I just ran your example, and if I send two "large icon notification". Only one is displayed (probably the latest). But if I send two different, large icon, then a big picture, it displays both.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
