### ISSUE TITLE
Notification coming without custom Sound in Samsung A30 and Oneplus 7T

### ISSUE THREAD

**Issue by ghost** [rafaelsetragni/awesome_notifications#298]
Notification coming without custom Sound in Samsung A30 and Oneplus 7T

**Comment by kcs-rahuljoshi** [comment]
Using Android Platform
keep.xml 
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/res_alert,@raw/res_visitor_ringtone" />

After adding this file issue is resolved in the **Oneplus 7T** device but not resolve in the **Samsung A30** device

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
