### ISSUE TITLE
Repeating scheduled daily notification not repeating

### ISSUE THREAD

**Issue by ultrasandbox** [rafaelsetragni/awesome_notifications#303]
Hello,

 I tried to setup a daily repeating notification but it only fires the first time. Here is my code:

```
String localTimeZone =
    await AwesomeNotifications().getLocalTimeZoneIdentifier();
    await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 123456789,
            channelKey: 'scheduled',
            title: "Sample title",
            body: "sample body",
            autoCancel: false),
        schedule: NotificationCalendar(
          hour: 8,
            minute: 0,
            second: 0,
            second: 0,
            millisecond: 0,
            timeZone: localTimeZone,
            allowWhileIdle: true,
            repeats: true));
```

**Comment by hammadpervez** [comment]
> What platform are you found this issue?

https://github.com/rafaelsetragni/awesome_notifications/issues/408#issue-1119923031

**Comment by prjmax** [comment]
Same issue on iOS, any solution? 
`schedule:
          NotificationCalendar(
              hour: 10,
              minute: 45,
              second: 0,
              allowWhileIdle: true,
              repeats: true,
              timeZone: AwesomeNotifications.localTimeZoneIdentifier
          ),`

**Comment by hammadpervez** [comment]
> Same issue on iOS, any solution? `schedule: NotificationCalendar( hour: 10, minute: 45, second: 0, allowWhileIdle: true, repeats: true, timeZone: AwesomeNotifications.localTimeZoneIdentifier ),`

I have got a solutation, 

first try with schedule: NotificationCalendar.fromDate() constructor and pass it Datetime now with like this DateTime.now().add(Duration(seconds:30); try this out . then let me know . if you are still having trouble

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
