### ISSUE TITLE
runtime type should not be used as a type checking mechanism

### ISSUE THREAD

**Issue by cedvdb** [rafaelsetragni/awesome_notifications#308]
I saw that runtimeType is used by the library:

```dart
mapData[NOTIFICATION_CONTENT].runtimeType == String
```

runtimeType should not be used and instead should be 

```dart
mapData[NOTIFICATION_CONTENT] is String
```

From a dart-lang dev:

>  It's best to not rely on runtimeType for almost anything. In addition, its important to be cautious about .runtimeType.toString() - the resulting String is allowed to change and dart2js will use a different string under minification.

I believe this could lead to bugs once the web side of things is implemented

https://github.com/dart-lang/sdk/issues/35052

**Comment by rafaelsetragni** [comment]
@cedvdb ive made important changes on the last versions. Please take a look at the v 0.6.14.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
