### ISSUE TITLE
Can we customise firebase push notification with action Button?

### ISSUE THREAD

**Issue by mohanhari** [rafaelsetragni/awesome_notifications#31]
Hi, It's more like a question. Can we customize the firebase push notification with awesome_notifcations? if so, how? 
Also, the example in the repo is not working for IOS. it's asking for GoolgeService-Info.plist even though firebase is optional
Thanks for help

**Comment by rafaelsetragni** [comment]
On iOS, i needed to change the request a bit. The json request is almost the same as in the README end file. I gonna release a new version with iOS FcM complete function soon. 

In this new version, will be possible to do almost every customization that you could do with local notifications, except the schedule functions, because Apple decides to treat the schedule for push different than local one. Unfortunately, there is nothing that i could do about it.

**Comment by mohanhari** [comment]
Thanks a lot for your help. The package is really awesome

**Comment by rafaelsetragni** [comment]
Do not close yet.
Let me launch the new version and, if everything works fine to your project, we close this topic.

**Comment by rafaelsetragni** [comment]
Version 0.0.5 finally released!

Call me here if you continue with issues on this new version.

**Comment by rafaelsetragni** [comment]
I gonna close this topic just to help me to organize the issues.
If you pretend to continue with this request, just reopen it.
