### ISSUE TITLE
NotificationInterval does not work with short intervals in iOS

### ISSUE THREAD

**Issue by khari998** [rafaelsetragni/awesome_notifications#316]
I am currently creating a notification with a delay and every time I run the application, the simulator crashes whenever the notification is created. 

```dart
await AwesomeNotifications().createNotification(
          content: NotificationContent(
              id: _id,
              channelKey: "example_channel",
              title:
                  "Example title", 
              body:
                  "Example body",
              notificationLayout: NotificationLayout.Default
              ),
          actionButtons: [
            NotificationActionButton(
              key: "complete_survey",
              label: "Complete Survey",
            )
          ]
          schedule: NotificationInterval(
            interval: 5,
           timeZone: localTimeZone,
             repeats: true,
           )
          );
 ```
          
 When removing this section, everything works fine: 
 
```
schedule: NotificationInterval(
            interval: 5,
           timeZone: localTimeZone,
             repeats: true,
           )
          );
 ```

Issue is present in both Flutter 2.2.3 and 2.5.3.

**Comment by rafaelsetragni** [comment]
## [0.6.14]

* **Added validation to prevent scheduling with repeating intervals smaller than 60 seconds (iOS restriction)**
* Added crontab schedule to allow complex schedules based on initial and expiration date, a list of precise dates, or a crontab expression, and all four options can be combined together (only for Android)
* Defined the final standard to replace negative IDs by random values
* Minimum Android requirements increased to SDK 23 (Android 6.0 Marshmallow) due to new cancellation methods with unsecure procedures on API prior 23

Now this issue will not happen again. Thank you so much for your help.
