### ISSUE TITLE
Android scheduled notification doesn't work when screen is off

### ISSUE THREAD

**Issue by t1ooo** [rafaelsetragni/awesome_notifications#330]
I noticed that schedule notification doesn't work on my device with AlarmManagerCompat.setExactAndAllowWhileIdle and AlarmManagerCompat.setExact, but work with AlarmManagerCompat.setAlarmClock.

Additional reading: https://stackoverflow.com/questions/34729966/alarmmanager-not-working-in-several-devices

**Comment by rafaelsetragni** [comment]
We are working with it right now. Take a look at:
https://github.com/rafaelsetragni/awesome_notifications/issues/322

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
