### ISSUE TITLE
Compile error - awesome_notifications-dummy.o does not contain bitcode

### ISSUE THREAD

**Issue by adrianvintu** [rafaelsetragni/awesome_notifications#339]
I am a flutter noob, and know nothing of iOS builds. I have enabled Bitcode as presented here:
https://medium.com/flutter-clan/firebase-crashlytics-with-flutter-7fe869f24bac
and now the project does not build anymore.

`awesome_notifications: ^0.6.17`

Can you please explain what am I supposed to do?

```'/Users/XXX/Library/Developer/Xcode/DerivedData/Runner-ffqkghgrvsdebhfrfcmrulrxioca/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/awesome_notifications/awesome_notifications.framework/awesome_notifications(awesome_notifications-dummy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/XXX/Library/Developer/Xcode/DerivedData/Runner-ffqkghgrvsdebhfrfcmrulrxioca/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/awesome_notifications/awesome_notifications.framework/awesome_notifications' for architecture arm64```

**Comment by rafaelsetragni** [comment]
There is a option on XCode to enable or disable bitcode  inside the app "runner" or the package project. You can change this value there.

![](https://raw.githubusercontent.com/rafaelsetragni/awesome_notifications/master/example/assets/readme/disable-bitcode.jpg)

**Comment by felixgabler** [comment]
Can we somehow enable it for this plugin? I can't find where to do that exactly. It is disabled in the pod under `Development Pods/awesome_notifications/Support Files/awesome_notifications.release.xcconfig`. Do we have to change it there?

**Comment by cselti** [comment]
Is it possible to make it enabled by default in Release profile? I have created a PR for this: https://github.com/rafaelsetragni/awesome_notifications/pull/479

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
