### ISSUE TITLE
Can i show a notification in a duration time?

### ISSUE THREAD

**Issue by vantangst** [rafaelsetragni/awesome_notifications#350]
i am implementing incoming call notification and the incoming notification should expire (missing call notification) after a period of time?

Something like the notification will dismiss after a period of time or any callback action to update, etc.

Do you have any idea to reach it?

**Comment by rafaelsetragni** [comment]
Also, there is another options that you could try too:

- Set priority to max
- Set locked
- Set category to call
- Set visibility to public
- Set wake up screen
- Set full screen intent
- Set default ringtone type to ringtone

**Comment by rafaelsetragni** [comment]
I got this!

![image](https://user-images.githubusercontent.com/40064496/143989780-52f01700-9ca8-4f0e-8839-9c5558b95a65.png)

Is not pretty yet, but will be available at next release!

**Comment by rafaelsetragni** [comment]
Since its a foreground notification, you gonna need to manually stop it. As soon you stop your notification, create a new with the missing call details.

**Comment by vantangst** [comment]
thank you, will try

**Comment by rafaelsetragni** [comment]
This feature is already live on 0.6.19. Please check it out.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by sagnik-sanyal** [comment]
Hi @vantangst did you find any way to show missed call notification after call notification ?
