### ISSUE TITLE
  /Package.swift has no Package.swift manifest in https://github.com/rafaelsetragni/awesome_notifications.git

### ISSUE THREAD

**Issue by shruthia123** [rafaelsetragni/awesome_notifications#352]
After the recent release when I try to build using XCode, I see this error. I am not sure whether I am missing something here. Please advise @rafaelsetragni .

**Comment by ShruAlekha** [comment]
Can anyone help with this please?

**Comment by ShruAlekha** [comment]
@rafaelsetragni any updates on this?

**Comment by rafaelsetragni** [comment]
Check this post on stack overflow:

https://stackoverflow.com/questions/58094765/xcode-11-swift-package-manager-cant-find-manifest

**Comment by ShruAlekha** [comment]
I already tried the reset package caches. I am using a few other plugins. Getting this error just for awesome notifications.

**Comment by rafaelsetragni** [comment]
When you build your app with Android Studio or Visual Studio does the same error occur?

**Comment by ShruAlekha** [comment]
On the mac yes I get this error when I use Android Studio or XCode. I have not tried Visual Studio Code

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
