### ISSUE TITLE
Create a scheduled notification from date with specific interval

### ISSUE THREAD

**Issue by S-ecki** [rafaelsetragni/awesome_notifications#360]
My goal is to create a notification that fires (eg) on the first day of every third month.
I am aware that I can create a scheduled notification from a date, and also set to repeat itself. However, I cannot set the interval for it to repeat as far as I can tell.

Using cron unfortunately is no option, as we deploy to iOS.

**Comment by rafaelsetragni** [comment]
On the same NotificationCalendar, which you created a scheduled based on a specific date, you can specify individualy each time parameters as you wish. Every time that the current time matches the parameters that you setted, the notification will be displayed. Parameters with null are considered as "all values are valid" in this verification process.

**Comment by S-ecki** [comment]
@rafaelsetragni thanks for the answer!

But as I understand it, it is not possible to send a notification eg. on the 15. January, 15. April, 15. July, 15. October?
At least not without `AndroidCronTab`, which is not working for iOS right now, correct?

**Comment by rafaelsetragni** [comment]
Yes. You're correct.

**Comment by S-ecki** [comment]
Are there plans to implement something similar like `AndroidCronTab` for iOS in the near future?

**Comment by S-ecki** [comment]
As a follow-up question: is there a possibility to set a scheduled notification to the last day of every month? (31. January, 28. Feb, 31. March, 30. April, ...)?

**Comment by rafaelsetragni** [comment]
Only if you set it manually. These schedule options are very limited.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
