### ISSUE TITLE
Feature request notification layout with dynamic image on the left and second image on right at the same time.

### ISSUE THREAD

**Issue by Albertbol** [rafaelsetragni/awesome_notifications#362]
Hey,
Thanks a lot for a great package, I wonder if it's possible to fulfill 2 requests for notification layout:
1. In messengers like "WhatsApp" and "Telegram", it's possible to use the dynamic image on the left instead of the app logo, currently, the app logo is shown always + you can display the image under (on IOS  you can only show app logo with this package).
2. It's not possible to show 2 images at the same time, user avatar + attached image, currently you have to choose to show either on the left or right.

Would be great to achieve this result on IOS and Android:

Android:
![android](https://user-images.githubusercontent.com/43991741/145625446-93013152-9b19-4361-904e-683404730b72.jpeg)
IOS:
![ios](https://user-images.githubusercontent.com/43991741/145625448-1c5f488b-b907-485f-922d-3cbb6bc446fd.jpeg)

**Layout**: User avatar(instead of app logo), user name, message, and image attachment on the right.
At least if it's hard to replace the app logo, it's ok to show it, but at least allow 2 images shown at once on the left and right to show the user profile image.

Thanks again.

**Comment by rafaelsetragni** [comment]
Use largeIcon and bigPicture property. You can use then simultaneously in many layouts.

**Comment by Albertbol** [comment]
Hey, thanks for the reply.
I have tried **messaging group** and **messaging** layouts.
But problem is that it's either one of them, so while not expanded big image showed, but the user icon is not. Only the application icon cannot be changed to the user icon. And when expanded only user icon showed, but not big image anymore. I have tried to set hideLargeIconOnExpand to false, but it should be by default equal to it, so it did not help.

Thas how it looks like if I use messaging and messaging group layouts with this package:

App icon on the left and big image on the right, user icon hidden:
![photo_2021-12-11 17 44 30](https://user-images.githubusercontent.com/43991741/145684789-9478fb39-bc91-4333-8912-f478e9381a84.jpeg)

On expanded user icon showed, but now big image is hidden:
![photo_2021-12-11 17 44 35](https://user-images.githubusercontent.com/43991741/145684788-3bd55034-e785-4994-a261-03c67823995d.jpeg)

Would be great to show only the user avatar on the left and then the image attached on the right in not expanded and expanded views, like I attached telegram examples above.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
