### ISSUE TITLE
IOS ProgressBar Notifications are creating repeatedly

### ISSUE THREAD

**Issue by Chetan-3110** [rafaelsetragni/awesome_notifications#371]
I am showing the download progress with following implementation:
```
AwesomeNotifications().createNotification(
              content: NotificationContent(
                id: 5,
                channelKey: 'download_status',
                progress: ((count / total) * 100).toInt(),
                title: "Downloading Video",
                notificationLayout: NotificationLayout.ProgressBar,
                locked: true,
              ),
            );
```

Everytime progress updates, it is showing notification again. It is only happening in IOS but working properly in android.

**Comment by rafaelsetragni** [comment]
This is the current behavior for iOS, because iOS does not have a native progres bar notification.

**Comment by Chetan-3110** [comment]
I think it would be better to avoid showing repeating notifications in IOS and instead, show some message in debug console regarding it.
The reason is that, I didn't knew about this behavior in iOS and spent hours thinking about implementing it incorrectly.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
