### ISSUE TITLE
Notification is not triggered

### ISSUE THREAD

**Issue by dmrcierhn** [rafaelsetragni/awesome_notifications#374]
first of all thanks for this great package. I'm trying to create a simple repetitive notification, but I get an error when the time I set expires. the error is "Interval is required and must be greater than zero". I don't know exactly what to do about it. I have included the code below. Thanks for help.

I am testing with real device and platform is android.

`String localTimeZone = await AwesomeNotifications().getLocalTimeZoneIdentifier();
    String utcTimeZone = await AwesomeNotifications().getLocalTimeZoneIdentifier();

    await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 1,
            channelKey: 'basic_channel',
            title: 'Repeated',
            body:
            'Repeated notification',
            ),
        schedule: NotificationInterval(interval: 60, timeZone: localTimeZone, repeats: true));`

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
