### ISSUE TITLE
Where do I put my custom Foreground Service's continuously running code? 

### ISSUE THREAD

**Issue by irjayjay** [rafaelsetragni/awesome_notifications#375]
I've looked through the example code, the docs and searched all the issues here.
I can't find where this library mentions where to put my foreground service code. 

I can start a foreground service and display the notification fine, but there aren't any callbacks for my actual custom foreground service logic, it's only a notification being shown, which isn't useful to me without an actual service running.

I'd like to keep running custom code, eg. every 60s in the foreground service, like how one would do it in Kotlin, but it's not very obvious how to do so. 
Has anyone been able to figure this out?

**Comment by rafaelsetragni** [comment]
There is a actual service running, but only with a notification. To implement what are you desiring, there is no way to do it in flutter, because flutter runs in a Virtual Machine/Engine. But there is no difference at all in the global perspective if you run your dart code using `compute()` while the notification service is on live.

But, if you really desire to run your methods inside a foreground service, i suggest you to implement it native on Android and reuse the awesome notification builder to create the android notification object.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
