### ISSUE TITLE
Can use the app on lock screen

### ISSUE THREAD

**Issue by vantangst** [rafaelsetragni/awesome_notifications#376]
hi, My Android app can use on the lock screen after i setup `showWhenLocked="true"` and `turnScreenOn="true"`

I expect on the lock screen we can't use the app. 

I am testing on android 12.

Everyone can help me to confirm that is true logic or that is a bug? Thanks

![image](https://user-images.githubusercontent.com/13620155/147919672-86d792b2-14ac-445f-97ac-f47eefa6356a.png)

**Comment by sgshubham98** [comment]
Hi @vantangst 

It's not a bug! If you don't wish to use the app from notification when the device is locked, you can simply remove **android:showWhenLocked="true"**

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
