### ISSUE TITLE
listScheduledNotifications always returning empty list

### ISSUE THREAD

**Issue by proczak1** [rafaelsetragni/awesome_notifications#379]
Hey. It sounds like listScheduledNotifications() returns alwasy empty list.  There must be an error in NotificationModel -> fromMap

**Comment by proczak1** [comment]
Did a little digging and got AwesomeNotificationsException:  autoDismissible id is requried

**Comment by amuelle** [comment]
I had the same issue with an empty list. In my case it failed with exception while deserialization and then returned an empty list. Should be fixed with PR #373

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
