### ISSUE TITLE
Android - Auto Open the App when at the time of the reminder (Wake Up Screen Notifications)

### ISSUE THREAD

**Issue by mzl1988** [rafaelsetragni/awesome_notifications#380]
Wake Up Screen Notifications

Android - Auto Open the App when at the time of the reminder
![image](https://user-images.githubusercontent.com/11645762/148346336-d5cec98a-c301-41ba-b63e-9e4d7d281d67.png)
![image](https://user-images.githubusercontent.com/11645762/148346275-11fa2706-a706-4c8c-affe-eba27be12902.png)

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
