### ISSUE TITLE
NOTIFICATION_WAKE_UP_SCREEN not working

### ISSUE THREAD

**Issue by hasnainusti** [rafaelsetragni/awesome_notifications#384]
I'm handling firebase onBackgroundMessage with awesome notification.

Here is my code: 

Future<void> backgroundHandler(RemoteMessage message) async {
  if (!AwesomeStringUtils.isNullOrEmpty(message.notification?.title,
          considerWhiteSpaceAsEmpty: true) ||
      !AwesomeStringUtils.isNullOrEmpty(message.notification?.body,
          considerWhiteSpaceAsEmpty: true)) {
    Map<String, dynamic> notificationAdapter = {
      NOTIFICATION_CHANNEL_KEY: 'mychannel',
      NOTIFICATION_ID: DateTime.now().millisecondsSinceEpoch ~/ 1000,
      NOTIFICATION_WAKE_UP_SCREEN: true,
      NOTIFICATION_TITLE: message.notification!.title,
      NOTIFICATION_BODY: message.notification!.body,
    };
    log(notificationAdapter.toString());
    AwesomeNotifications().createNotificationFromJsonData(notificationAdapter);
  } else {
    AwesomeNotifications().createNotificationFromJsonData(message.data);
  }
}

Everything works fine but fone screen does not wake up but when I use createNotification method instead of createNotificationFromJsonData fone screen wakes up but I get duplicate notification. Here's the code with createNotification

Future<void> backgroundHandler(RemoteMessage message) async {
   AwesomeNotifications().createNotification(
       content: NotificationContent(
           id: DateTime.now().millisecondsSinceEpoch ~/ 1000,
           channelKey: 'mychannel',
           wakeUpScreen: true,
           title: message.notification!.title,
           body: message.notification!.body));
}

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
