### ISSUE TITLE
HTML Text is not showing in the samsung devices.

### ISSUE THREAD

**Issue by AhemadAbbasVagh** [rafaelsetragni/awesome_notifications#386]
I tried to add HTML text for title and body with BigText Style to display notification and for all the android devices, it's working as expected but when I use same code for the samsung devices then It's showing as a normal text even if I add HTML text in it.

**Comment by mezzarfani** [comment]
I have the same problem.
Like \t is not working on Samsung

**Comment by rafaelsetragni** [comment]
Maybe the Samsungs do not allow to use HTML as others Android distributions does, and for this case there is nothing to do about (and in fact you don't need to do anything, always respect the platform standards, it's always the better way to go).

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
