### ISSUE TITLE
Can't get data in actionStream app background

### ISSUE THREAD

**Issue by tarja77** [rafaelsetragni/awesome_notifications#387]
hello, I've been using the library for a week, everything is fine, but I can't receive data in the background of the actionStream application. I need to run a code so that the close part does not receive notifications. It works when the application is open, but I cannot run it when the application is dead. I am sending the content via FCM data message

![Ekran Resmi 2022-01-13 13 29 00](https://user-images.githubusercontent.com/7052223/149313230-698c7485-0e81-4493-bac1-2f9c5c3b48a2.png)

![2022-01-13 13 05 44](https://user-images.githubusercontent.com/7052223/149312836-dd1a4f2e-f1f8-4e87-aac2-119e743fb1bd.jpg)
![Ekran Resmi 2022-01-13 12 56 04](https://user-images.githubusercontent.com/7052223/149312839-d16d7347-e9fa-48a1-b5dd-cca5e9714665.png)

**Comment by GundeepSingh** [comment]
I am also facing the same issue. Can you please provide some solution for this?

**Comment by tarja77** [comment]
> Ben de aynı sorunla karşı karşıyayım. Lütfen bunun için bir çözüm sunabilir misiniz?

I couldn't find a solution for this, we are waiting for the developer to reply :)

**Comment by GundeepSingh** [comment]
@tarja77 I appreciate your feedback. It will be really awesome if you guys can provide a solution for this as soon as possible.

**Comment by saharvx9** [comment]
https://github.com/saharvx9/awesome_notifications/tree/background_click

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
