### ISSUE TITLE
Notification sound settings default disabled o Android 11

### ISSUE THREAD

**Issue by Mex978** [rafaelsetragni/awesome_notifications#388]
I'm trying to send scheduled notifications but all works fine except the notification sound (Smartphone isn't in silent mode). I have tried to re-install Android Studio but didn't work. The weird behavior is that I have tested release build in smartphone with Android 9 version and sound worked. In the emulator with Android 10 worked too but on my device, with Android 11 (Poco X3 Pro - Xiaomi), the notifications only vibrate, when the device is in silent mode, but in the other case (no silent mode), vibration and sound didn't work.....

I checked the allowed permissions and all seems to be ok `Allowed permissions: [NotificationPermission.Badge, NotificationPermission.Alert, NotificationPermission.Sound, NotificationPermission.Vibration, NotificationPermission.Light]`, but in my device, the notification sound settings look by default like that doesn't matter what I do:

![image](https://user-images.githubusercontent.com/31356610/149636769-4b24a63d-b4c7-42b4-80d5-c4bf4d24ccfa.png)

I tried creating different channels and NOTHING. 

PS: I am not trying, nor do I intend, to use custom sounds, but the default system notification sound.

**Comment by mahesh-hegde** [comment]
Hey,

Requesting the FullscreenIntent permission in main() fixed this in my case.

```dart
  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      // I dont think it explicitly asks user for fullscreenIntent permission
      // Mine was a class project so I didnt have to care about showing
      // user friendly dialogue about permissions
      AwesomeNotifications().requestPermissionToSendNotifications(
		permissions: [NotificationPermission.Sound, NotificationPermission.Alert, NotificationPermission.FullScreenIntent],
	  );
    }
  });
```

**Comment by Mex978** [comment]
Didn't work :(. I already tried to allow all NotificationPermissions but still doesn't work

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
