### ISSUE TITLE
incrementGlobalBadgeCounter() and decrementGlobalBadgeCounter() details are incorrect

### ISSUE THREAD

**Issue by tomnerp** [rafaelsetragni/awesome_notifications#390]
<img width="511" alt="Screen Shot 2022-01-17 at 10 49 08 AM" src="https://user-images.githubusercontent.com/55699225/149705294-6778a52c-d76b-4694-a36d-ce9e158150f9.png">

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
