### ISSUE TITLE
roundedLargeIcon doesn't work properly on images that have a non 1:1 aspect ratio

### ISSUE THREAD

**Issue by frogman1189** [rafaelsetragni/awesome_notifications#393]
setting rounded large icons on when the specified large icon is not 1:1 aspect ratio causes it to be incorrectly rounded.

# code
(500x400 space image)
```
await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: message.hashCode,
            channelKey: channelKey,
            title: 'Big picture title',
            body: 'ASDASDASDASDASDASDASDASD',
            largeIcon: 'https://www.eiseverywhere.com/file_uploads/2604d347c13d08cbbbcf4b1d377b736d_SolarSystem.jpg',
            roundedLargeIcon: true,
            notificationLayout: NotificationLayout.BigPicture,
            payload: {'uuid': 'uuid-test'}));
```
![Screen Shot 2022-01-21 at 12 24 23 PM](https://user-images.githubusercontent.com/20494957/150438258-983f55b2-728f-463d-a90a-48cf8bb2c8ff.png)

(800x800 space image)
```
await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: message.hashCode,
            channelKey: channelKey,
            title: 'Big picture title',
            body: 'ASDASDASDASDASDASDASDASD',
            largeIcon: 'https://images.squarespace-cdn.com/content/59306e092994cad2710a3318/1594252153957-9LNA46Y0WHB6B5IEB4ND/GMP+JULY+20+15.png?content-type=image%2Fpng',
            roundedLargeIcon: true,
            notificationLayout: NotificationLayout.BigPicture,
            payload: {'uuid': 'uuid-test'}));
```
![Screen Shot 2022-01-21 at 12 27 21 PM](https://user-images.githubusercontent.com/20494957/150438301-82056ea4-fb95-440e-856e-d0f52fea95bc.png)

# expected behaviour
I think ideally it should attempt to take a 1:1 ratio section from the center and round that. The alternative is to document this feature so that no one else has to spend a while trying to figure out why it won't round their image correctly. (Especially as on larger aspect ratio differences it becomes unnoticeable that its even attempting to round it)

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
