### ISSUE TITLE
Error when calling initialize:  Atempt to invoke virtual method

### ISSUE THREAD

**Issue by TimeLord2010** [rafaelsetragni/awesome_notifications#397]
<img width="880" alt="Screen Shot 2022-01-24 at 15 01 02" src="https://user-images.githubusercontent.com/50129092/150839079-bf559bc0-002c-435f-9a31-250ef50240db.png">

There is this error I keep getting that only happen sometimes. When I face this issue, I this keep trying to start my app, and it eventually starts without errors.

I dont know what has been cause this. The notification icon resource exists.

```
 final AwesomeNotifications _awesomeNotifications = AwesomeNotifications();

  final Channel _queueChannel = Channel(
    channelKey: 'Queues',
    channelName: 'Filas',
    channelDescription: 'Filas',
  );

  final Channel _chatChannel = Channel(
    channelKey: 'Chats',
    channelName: 'Conversas',
    channelDescription: 'Conversas',
  );

  final Channel _internalChatChannel = Channel(
    channelKey: 'Internal-Chat',
    channelName: 'Chat Interno',
    channelDescription: 'ChatInterno',
  );

  Future<bool> create() async {
    await _awesomeNotifications.initialize(
      'resource://drawable/res_g4_logo',
      [
        NotificationChannel(
          channelKey: _chatChannel.channelKey,
          channelName: _chatChannel.channelName,
          channelDescription: _chatChannel.channelDescription,
          importance: NotificationImportance.Max,
          defaultPrivacy: NotificationPrivacy.Public,
        ),
        NotificationChannel(
          channelKey: _queueChannel.channelKey,
          channelName: _queueChannel.channelName,
          channelDescription: _queueChannel.channelDescription,
          importance: NotificationImportance.Max,
          defaultPrivacy: NotificationPrivacy.Public,
        ),
        NotificationChannel(
          channelKey: _internalChatChannel.channelKey,
          channelName: _internalChatChannel.channelName,
          channelDescription: _internalChatChannel.channelDescription,
          importance: NotificationImportance.Max,
          defaultPrivacy: NotificationPrivacy.Public,
        )
      ],
    );
    final isAllowed = await _awesomeNotifications.isNotificationAllowed();
    if (!isAllowed) {
      return await AwesomeNotifications().requestPermissionToSendNotifications();
    }
    return true;
  }
// CODE
}
```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
