### ISSUE TITLE
InputField Not Working on android 6 and 5.1and maybe more

### ISSUE THREAD

**Issue by arashAndroid** [rafaelsetragni/awesome_notifications#40]
Hi. Thanks for this awesome package. I created a notification with InputField as NotificationActionButton. I want the user type something and hit send. I have been using this package with my android 8 device and it is working without any problem. But when I tried it on android 6 and android 5.1 devices, the InputField did not work. I is showing the notification AND the InputField, but when I click on it, it does not let me put any text and just runs the AwesomeNotifications().actionStream with an empty (null) string. 

I am using 0.0.5+2 version with flutter 1.22.0

My Code:

    AwesomeNotifications().initialize(
          'resource://drawable/app_icon',
          [
            NotificationChannel(
                channelKey: 'seller_channel',
                channelName: 'seller notifications',
                channelDescription: 'Notification channel for basic tests',
                importance: NotificationImportance.Max,
                defaultPrivacy: NotificationPrivacy.Public,
                defaultColor: Color(0xFF9D50DD),
                ledColor: Colors.orange)
          ]);

And The method to show the notification:

    void showAwesomeNotification(String product) {
        AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
          if (!isAllowed) {
        AwesomeNotifications().requestPermissionToSendNotifications();
      }
      AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 10,
            channelKey: 'seller_channel',
            title: '$product',
            payload: {'name': product},
            autoCancel: false,
            color: primaryColor,
            body: 'my body'),
        actionButtons: [
          NotificationActionButton(
              buttonType: ActionButtonType.InputField,
              autoCancel: false,
              key: 'inputPrice',
              icon: "images/logo.png",
              label: 'Enter Price...')
        ],
      );
    });
      }

Please help me on this.

**Comment by rafaelsetragni** [comment]
Sorry, but I won't be able to check this until tomorrow.

In the meantime, try to reproduce the error in your application by attaching the visual studio debug. this way you will be able to see if any exceptions are being thrown in the plugin's native code.

**Comment by rafaelsetragni** [comment]
The oldest Android version that i tested whas 7.0 Nougat. Apparently, this input button in notifications has been around since android 4.0, but until 6.0 they worked differently. Im trying to figure out what is the correct way to do on older devices.

You can also try to change it in your local sources. The method that construct all Android notification actions is this one:

https://github.com/rafaelsetragni/awesome_notifications/blob/b3e4da96f0302fef43f4c801d819dad044021332/android/src/main/java/me/carda/awesome_notifications/notifications/NotificationBuilder.java#L384

**Comment by arashAndroid** [comment]
Thanks for the reply. For now I have put my code in try catch to see if the payload is null. So I can show a dialog on catch to enter the payload. So basically I am showing a dialog if the android version does not support the textfield in notifications.

**Comment by rafaelsetragni** [comment]
Android documentation is confusing. On some pages, he informs that RemoteInput has been available since Android 20 (4.4), but in other places, he informs that RemoteInput is only available from Android 22 (7.0).

[RemoteInput documentation (Android 4.4 - API 20)](https://developer.android.com/reference/android/app/RemoteInput)
[Notification actions (Android 7.0)](https://developer.android.com/guide/topics/ui/notifiers/notifications#Actions)

I tried everything to make it work on Android 6 and below, but nothing worked. I'm not able to make it work in versions before Android 7.0 Nougat. Sorry.
