### ISSUE TITLE
android:exported

### ISSUE THREAD

**Issue by dmrcierhn** [rafaelsetragni/awesome_notifications#404]
First of all, thanks for this great package! I have a problem with android:exported. I get an error when I want to install my application even though I have added it to my manifest file. 

"You have uploaded an APK or Android App Bundle with an event, event alias, service, or broadcast receiver with an intent filter, but not set to "android:exported". This file cannot be installed on Android 12 or later. Check it out at: developer.android.com/about/versions/12/behavior-changes-12#exported"

I use latest version.

How can I fix this? Thanks!

**Comment by rafaelsetragni** [comment]
> "You have uploaded an APK or Android App Bundle with an event, event alias, service, or broadcast receiver with an intent filter, but not set to "android:exported". This file cannot be installed on Android 12 or later. Check it out at: developer.android.com/about/versions/12/behavior-changes-12#exported"

This rule is valid for your AndroidManifest.xml application file, and every Flutter project, inside Android folder, there is a AndroidManifest.xml file that has an activity with intent-filter. This activity must contains `android:exported` property for Android 12+

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
