### ISSUE TITLE
Invalid notification (no valid small icon):

### ISSUE THREAD

**Issue by Nazarii77** [rafaelsetragni/awesome_notifications#407]
I get Invalid notification (no valid small icon):
FROM EXAMPLE

**Comment by rafaelsetragni** [comment]
Probably the file has being erased in your machine. 

Whatch this video, this issue is kid stuff:
https://github.com/rafaelsetragni/awesome_notifications#video-tutorial

**Comment by NightSkyDev** [comment]
If you used the example from the README, then you'll notice the comment that says "set the icon to null".  If you use the example as is,  you'll need to have the 'res_app_icon' in your assets.  If you change it to pass null instead, you won't get that error as it will use the default app icon.

//######### Pasted from Example ##########
AwesomeNotifications().initialize(
  // set the icon to null if you want to use the default app icon
  'resource://drawable/res_app_icon',
  [
    NotificationChannel(
        channelGroupKey: 'basic_channel_group',
        channelKey: 'basic_channel',
        channelName: 'Basic notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white)
  ],
  // Channel groups are only visual and are not required
  channelGroups: [
    NotificationChannelGroup(
        channelGroupkey: 'basic_channel_group',
        channelGroupName: 'Basic group')
  ],
  debug: true
);

**Comment by Miedziaq** [comment]
why resource://drawable this is android specific? what with ios?????

my app build with flutter has his own icon but this library stil shows the flutter original one..

**Comment by rafaelsetragni** [comment]
Take a look at this video tutorial:

https://youtu.be/JAq9fVn3X7U

**Comment by husen313** [comment]
![Screenshot 2022-08-20 at 9 32 52 PM](https://user-images.githubusercontent.com/86182263/185755946-9f521f25-59b4-4c36-b18d-c81bcb343bf4.png)
after adding `defaultIcon` null my issue is Solved

**Comment by eav-solution** [comment]
> ![Screenshot 2022-08-20 at 9 32 52 PM](https://user-images.githubusercontent.com/86182263/185755946-9f521f25-59b4-4c36-b18d-c81bcb343bf4.png) after adding `defaultIcon` null my issue is Solved in android

You are my sunsine!

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by rochelryu** [comment]
it's because you're trying it on your emulator.
try it on a real phone
