### ISSUE TITLE
best way to persist a timer notification

### ISSUE THREAD

**Issue by MiguelSOliveira** [rafaelsetragni/awesome_notifications#409]
I'm trying to implement a stop watch in a persistent like notification.

I'm using this method call:

```

The channel:

NotificationChannel(
      channelDescription: 'Tracking Activities Channel',
      channelKey: TRACKING_CHANNEL_KEY,
      channelName: TRACKING_CHANNEL_NAME,
      importance: NotificationImportance.Low,
      enableVibration: false,
      playSound: false,
      channelShowBadge: Platform.isIOS ? false : true,
    ),

.......

await awesomeNotifsInstance.createNotification(
    content: NotificationContent(
      id: 2,
      channelKey: TRACKING_CHANNEL_KEY,
      title: 'Friendly Reminder ${Emojis.smile_slightly_smiling_face}',
      body: timeEllapsed,
      notificationLayout: NotificationLayout.Default,
      displayOnBackground: false,
      displayOnForeground: false,
      autoDismissible: false,
      wakeUpScreen: false,
      category: NotificationCategory.StopWatch,
    ),
  );
```

And this createNotification method is called every second, but when the app is minimized (this does not happen when the app is opened), the notifications just keep appearing on the foreground, one after the other. I would like for the notification to appear only the first time, and then would just change the text.

Is it possible? Thanks !

**Comment by cs-mac** [comment]
@MiguelSOliveira Did you find a way to do this?

**Comment by MiguelSOliveira** [comment]
I did not. In the meantime, I've changed my requirements.

**Comment by rafaelsetragni** [comment]
Its a question of priority. If you set a higher priority it will behaves like that. So, try to lower the priority.

**Comment by cs-mac** [comment]
@rafaelsetragni Is there a way to only update the notification without constantly creating a new notification?
I've seen apps where, at least, visually it looks like the notification only gets updated without the creation of a new notification.

**Comment by rafaelsetragni** [comment]
It seems to be a custom layout notification, and inside the layout the notification refreshes it own state, without the app interference. But I did not implemented anything related to custom notification layouts and I didn't dig it deep to confirm to you that this is the case.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
