### ISSUE TITLE
iOS FCM Notifications - Received Invalid Message Content

### ISSUE THREAD

**Issue by ffaridi1** [rafaelsetragni/awesome_notifications#414]
Firstly,
Awesome Plugin !! Very useful and flexible. 
I have same issue as reported several times here (I am sorry to re-report it) however I have followed everything mentioned in these threads and used Postman to send test notification, iOS can show the notification but when I click on it actionStream never get fired and I see the "Invalid content received" message in Xcode.
My notification is as follows , please let me know what am I doing wrong here ?
For Android, everything works as expected.

{
    "to": "/topics/[TOPIC]",
    "notification": {
        "body": "Test Program",
        "OrganizationId": "2",
        "priority": "high",
        "subtitle": "New Program",
        "title": "Test Program Title",
        "click_action": "FLUTTER_NOTIFICATION_CLICK"
    },
    "data": {
        "body": "Test Program body",
        "title": "Test Title",
        "msgId": "000001",
        "subtitle": "New Program",
        "update_type": "",
        "notification_type": "UPDATE_PR",
        "salat_title": "",
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
        "content": {
            "id": 323,
            "channelKey": "basic_channel",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "notificationLayout": "BigPicture",
            "largeIcon": "https://media.fstatic.com/kdNpUx4VBicwDuRBnhBrNmVsaKU=/full-fit-in/290x478/media/artists/avatar/2013/08/neil-i-armstrong_a39978.jpeg",
            "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
            "showWhen": true,
            "autoDismissible": true,
            "privacy": "Private"
        }
    },
    "notification_priority": "PRIORITY_MAX",
    "visibility": "PUBLIC"
}

**Comment by ffaridi1** [comment]
Just to add, display stream is getting fired without any issues , action stream however is not fired.
Looks like there is something in the FCM notification which AwesomeNotification does not like. Please help me figure out , I am almost giving up on the plugin as this feature is a must for my App.
Thanks

**Comment by rafaelsetragni** [comment]
You should not use fcm notification content, only data, and this is because of firebase_messaging plugin limitations. So, the fcm plugin only accepts integration through push data. That's why im creating the companion plugins. 

To know more about it, get into our discord chat server.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
