### ISSUE TITLE
Adding a startDateTime or startInterval to NotificationCalendar and NotificationInterval

### ISSUE THREAD

**Issue by Pilpin** [rafaelsetragni/awesome_notifications#420]
Hello,

Would you consider adding a startDateTime and/or startInterval to NotificationCalendar and NotificationInterval ? It would allow developers to create a notification starting at a specified date or after a specified interval and then acting as NotificationCalendar and NotificationInterval would.

Thanks for the great work on this amazing plugin !

**Comment by StefanDimov** [comment]
Yes, this will be very useful. I have a need for this in my app as well. Hope it makes it in!

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
