### ISSUE TITLE
Screen lock / power button triggers fullScreenIntent notification

### ISSUE THREAD

**Issue by bogdanmarinescu** [rafaelsetragni/awesome_notifications#421]
If I'm showing a `fullScreenIntent = true` notification and when I press the Power button to close the screen, the app opens.

```
AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: id,
      channelKey: 'basic_channel',
      title: 'title',
      body: 'body',
      category: NotificationCategory.Call,
      fullScreenIntent: true,
      autoDismissible: true,
    ),
    actionButtons: [
      NotificationActionButton(
        key: 'ANSWER',
        label: 'Answer',
        autoDismissible: true,
      ),
      NotificationActionButton(
        key: 'DECLINE',
        label: 'Decline',
        autoDismissible: true,
        buttonType: ActionButtonType.DisabledAction,
      ),
    ],
  );
```
Is there any way to dismiss notification when the user closes the screen?

```
awesome_notifications: ^0.6.21
Flutter stable, 2.8.1
Android SDK version 31.0.0
```

**Comment by rafaelsetragni** [comment]
This behavior seems to be intended by Android team for Android 12. Its like a shortcut for incoming calls. And I don't know if its possible to disable or change it. What I suggest you to do is to make the notification body as a shortcut to the calling page preview. This way the power button will work as intended for Android 12.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
