### ISSUE TITLE
Platform Exception when sending basic notification.

### ISSUE THREAD

**Issue by TomasWard1** [rafaelsetragni/awesome_notifications#422]
I followed reso coder's guide on how to set up everything. When I try creating a new notification, this error is called:
`flutter: PlatformException(exception, Unknow error, The operation couldn’t be completed. (awesome_notifications.AwesomeNotificationsException error 1.), null)`

I don't know what to fix as there is no description.

Please Help! Thanks!

**Comment by HSCOGT** [comment]
In my case, it was the wrong **channelKey**. 

I don't know if you were able to fix it, but maybe it can help someone else.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
