### ISSUE TITLE
Change background color of default notification layout.

### ISSUE THREAD

**Issue by lukiinhas1616** [rafaelsetragni/awesome_notifications#424]
I would like to display the notification with a color other than gray, but the background color property only works in NotificationLayout.MediaPlayer.

My notification has an action button and it doesn't show in media player mode, is there anything that can be done?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
