### ISSUE TITLE
Alarm does not sound or vibrate on silent mode.

### ISSUE THREAD

**Issue by lukiinhas1616** [rafaelsetragni/awesome_notifications#425]
I need to create an alarm app, the notifications schedule is displayed correctly, but the sound is not triggered.

Initialization
`
AwesomeNotifications()
        .initialize(
            null,
            [
              NotificationChannel(
                  channelGroupKey: 'basic_channel_group',
                  channelKey: 'wakkeup',
                  channelName: 'Basic notifications',
                  channelDescription: 'Notification channel for basic tests',
                  defaultColor: ColorUtils.purple,
                  ledColor: ColorUtils.white,
                  playSound: true,
                  enableVibration: true,
                  defaultRingtoneType: DefaultRingtoneType.Alarm,
                  importance: NotificationImportance.High,
                  defaultPrivacy: NotificationPrivacy.Public,
                  onlyAlertOnce: false,
                  criticalAlerts: true)
            ],
            channelGroups: [
              NotificationChannelGroup(
                  channelGroupkey: 'basic_channel_group',
                  channelGroupName: 'Basic group')
            ],
            debug: true)
        .then((value) => createNotification)
`

My current notification content.
`NotificationContent(
            id: DateTime.now().hashCode,
            channelKey: 'sample',
            title: 'Sample title',
            body: 'This is a example',
            fullScreenIntent: true,
            criticalAlert: true,
            wakeUpScreen: true,
            autoDismissible: false,
            locked: true,
            displayOnBackground: true,
            displayOnForeground: true,
            color: ColorUtils.purple,
            backgroundColor: ColorUtils.white,
            notificationLayout: NotificationLayout.Default)`

My android manifest permissions
`<activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:showWhenLocked="true"
            android:showOnLockScreen="true"
            android:turnScreenOn="true"
            android:exported="true">`

Is there any additional step for notifications to be triggered with sound even in silent mode?
Natural behavior of alarms.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
