### ISSUE TITLE
Close progress notification when app is terminated

### ISSUE THREAD

**Issue by aitinsan** [rafaelsetragni/awesome_notifications#431]
I used appLyfecycle to clear notifications when app is terminated, but it doesn't worked. How 
![image](https://user-images.githubusercontent.com/57362967/155980111-dcf02336-b29c-496f-b476-761e23673810.png)
![image](https://user-images.githubusercontent.com/57362967/155980656-216e2e19-cfe0-47aa-a408-02db69ffbacd.png)

**Comment by rafaelsetragni** [comment]
Try to use await, because these methods return future.

**Comment by aitinsan** [comment]
I tried but it is not  worked

**Comment by rafaelsetragni** [comment]
Paste your log here

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
