### ISSUE TITLE
Performance issue on using cancelAll 

### ISSUE THREAD

**Issue by ahmed2hamy** [rafaelsetragni/awesome_notifications#432]
Using `cancelAllSchedules` or `cancelAll` is taking so long on the main thread and causing a lag specially on low end devices![Screen Shot 2022-03-01 at 3 03 38 PM](https://user-images.githubusercontent.com/35851365/156174082-56aa0776-cb3e-44d9-a577-96fc6a2f2853.png)

**Comment by rafaelsetragni** [comment]
Ive implemented a different way to cancel schedules. How you did to track the calling events as you did in this print screen?

**Comment by ahmed2hamy** [comment]
@rafaelsetragni Using android studio profiler in native android environment. What is that way you mentioned ?

**Comment by rafaelsetragni** [comment]
Is on the beta branch. You gonna need to move to the beta and paste this reference into your pubspec.yaml to use it:

```yaml
  awesome_notifications: #^0.6.21 
    git:
      ref: "b0dd136"
      url: https://github.com/rafaelsetragni/awesome_notifications
```

Then, you gonna need to change your listeners from streams to static methods. Below is the step by step of how to use awesome notifications 0.7.0:
https://github.com/rafaelsetragni/awesome_notifications/tree/release-0-7-0#how-to-show-local-notifications

In case you find a issue with pub get with different versions of awesome, delete all awesome notifications folders in `flutter/.pub-cache/git` including cache and then run: `git config --system core.longpaths true` and then run pub get.

I did not implement any concurrency handling for these methods and do not replicate the improvements on iOS yet. But you can already test if the performance was improved.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
