### ISSUE TITLE
Notification is not using app icon

### ISSUE THREAD

**Issue by Miedziaq** [rafaelsetragni/awesome_notifications#433]
Hello, 

i have icons in flutter changed to my own, app is installing with my icon, but notification still using flutter default icons, i tried to change it in NotificationChannel  icon property but not works....

why there is always used  resource://drawable  in examples? this is android specific :|

**Comment by rafaelsetragni** [comment]
Take a look at this video tutorial;

https://youtu.be/JAq9fVn3X7U

**Comment by remymumoh** [comment]
Do something like this
 ```
 AwesomeNotifications().initialize(
        'resource://drawable/app_icon', // icon for your app notification
        [
          NotificationChannel(
              channelKey: 'key1',
              channelName: 'VaxCEM Care',
              channelDescription: "VaxCEM Care",
              ledColor: Colors.white,
              importance: NotificationImportance.High,
              playSound: true,
              enableLights: true,
              enableVibration: true)
        ]);
```

**Comment by Miedziaq** [comment]
thanks, I found this kind of configurations in examples tutorials and so on, but will it work on IOS too?

**Comment by remymumoh** [comment]
from what I tested, yes it works

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
