### ISSUE TITLE
how to disable banner notification on ios?

### ISSUE THREAD

**Issue by Miedziaq** [rafaelsetragni/awesome_notifications#440]
Do we have possibility to disable banner notification on ios for notification?

**Comment by rafaelsetragni** [comment]
What is banner notification? Try to decrease the notification's priority.

**Comment by Miedziaq** [comment]
generally if you google this phrase you will see. because its strangely named :)

on android the notifications coming is visible by icon appearing on topbar, but in ios there is banner on top of everything. 
user can deactivate it or influence in settings, but i am asking if there is some way to setup notification settings for android/ios in this library or not?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
