### ISSUE TITLE
NotificationAndroidCrontab schedule doesn't work as expected

### ISSUE THREAD

**Issue by xennygrimmato** [rafaelsetragni/awesome_notifications#441]
My crontab schedule is: `0 * 11 * * ? *`

As per [[1]](https://bradymholt.github.io/cron-expression-descriptor/), I expect to see a notification at every minute between 11:00 AM and 11:59 AM. However I only see the first notification and none afterwards.

Is there something wrong with my interpretation of the cron schedule?

**Comment by haaris94** [comment]
I am also having the same problem

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
