### ISSUE TITLE
iOS Badge Numbers High, when using cancel(id)

### ISSUE THREAD

**Issue by clockwork189** [rafaelsetragni/awesome_notifications#444]
Hello, I love this plugin and it is all round amazing. However, I am running into this issue on iOS where the notification numbers are un-usually high. I decided to check out the example app and try to replicate and I think I figured out what is causing the issue. 

What I did was that I scheduled 62 notifications to go off every day at 7am for the next 62 days, then I cancelled each of the 62 notifications, then I re-scheduled the notifications for the next 62 days, again for 8am. 

Following this I backed out and went on the device time settings, and changed the time to tomorrow 9am and while i got the push notification for the correct time, the number showed 61. I also tried cancelling and dismissing it by Id, or using cancelSchedule instead of cancel, and I still got this error. 
![Image from iOS (1)](https://user-images.githubusercontent.com/949323/157767821-48e4195d-7bd4-4452-a0f6-d134d148f95e.png)

The only workaround that worked for me, was to use cancelAll() instead, which works for me, but I still wanted to make a note of this. Perhaps I am not cancelling individual notifications correctly? My use case in my project is that by default people get a notification at 8am and 10pm every day for the next 31 days, however they may wish to change their morning time to a different time, eg: 9am, but keep their evening time to 10am, which is why I do the individual cancel(id) method to cancel only the 8am future notifications. The workaround with cancelAll works for me, but I still wanted to make a note of this issue
<img width="746" alt="Screen Shot 2022-03-10 at 5 47 45 PM" src="https://user-images.githubusercontent.com/949323/157767872-fa020fb0-74d0-4767-a65a-7a6e6139543e.png">
.

**Comment by rafaelsetragni** [comment]
First thing first, thanks! I appreciate your feedback and im happy to hear that people are enjoying it. It's what I believe how everything should work.

Then, you need to clear the badge by yourself using the badge methods. I did that to allow you to decide what is the best strategy on use these badge counters.

For example, maybe you wish to clear all the badges as soon you enter on the notification's page. Or as soon you open the app. Or just to decrease the badge number when you tap over notification. You decide what is the best for you.

The only thing which is automatic is the badge increments, because you can't do it while the app is terminated.

Al the necessary methods to manipulate badges are available with Awesome and they are more efficient than implement it on dart. And also exists some Android distributions who use badge numbers, as samsung. Awesome manage everything to do the same in any platform.

**Comment by clockwork189** [comment]
Thank you for your reply and your insight. I took your feedback and after cancelling my notifications I also called resetGlobalBadge method and this did the trick! 

<img width="672" alt="Screen Shot 2022-03-11 at 12 04 22 PM" src="https://user-images.githubusercontent.com/949323/157913610-5456282f-1f68-4783-a2b2-7e7c15573902.png">
