### ISSUE TITLE
Customizable notification with buttons

### ISSUE THREAD

**Issue by mtc-jed** [rafaelsetragni/awesome_notifications#446]
Hi, I just wanted to know doing something close to this (disregarding the background) is possible ? It would seem to be with `MediaPlayer`, but I'm not sure and can't find any documentation relating to this on `awesome_notifications`'s Github and pub.dev pages.

![image](https://user-images.githubusercontent.com/91450931/158633489-bdb8f67d-f948-48d5-8a13-6b0e45a111c0.png)

Thanks.

Edit : Damn this wasn't clear.
I want to be able to customize "whatever" I want in the notification : where are the buttons, what are their colors... I suppose I need SVG files if I want to use the NotificationActionButton.color property ?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
