### ISSUE TITLE
Example app notification with custom sound does not work with android API 29

### ISSUE THREAD

**Issue by PoeMcMoe** [rafaelsetragni/awesome_notifications#447]
Tested the example app on emulator with android API 29 and the custom sound did not work.

**Comment by rafaelsetragni** [comment]
For Android 8+ the sound are defined by channels and can only be set once. What you can try is to do no set any sound on channel and set it later by custom sound.

**Comment by hasnainusti** [comment]
> 

Same issue. Custom sound is working fine on ios but not in android. Already setting the custom sound in create notification method.

**Comment by PoeMcMoe** [comment]
Also notification buttons do not work on android 12, I have not tested this thoroughly though, because I stopped using this plugin.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
