### ISSUE TITLE
Error when build on Xcode - dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by DVCStudioX** [rafaelsetragni/awesome_notifications#450]
I have an error when using awesome_notifications packages to build on Xcode (android is fine):
```
dyld: Library not loaded: @rpath/libswiftCore.dylib

  Referenced from: /private/var/containers/Bundle/Application/724552E2-C199-41D1-8835-8050C20F970F/Runner.app/Runner

  Reason: image not found

dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) 
```

My MacOS version 11.3.1
Xcode version 12.5.1
added @executable_path/Frameworks" to the Linking -> Runpath Search Path

So anyone can help me?

**Comment by rafaelsetragni** [comment]
Try this one:
https://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib

**Comment by DVCStudioX** [comment]
I converted Objective-C AppDelegate to Swift then it works, thanks anyway :D

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
