### ISSUE TITLE
Doesn't work on Android 12 while app is terminated or in background

### ISSUE THREAD

**Issue by Dimilkalathiya** [rafaelsetragni/awesome_notifications#452]
![Uploading Screenshot_2022-03-26-10-14-03-062_com.miui.home.jpg…]()

While code works perfectly fine when with Android 11 or below using fcm in all conditions (foreground, background, terminated) but in Android 12 and 13 app crashes on tested on multiple devices same problem Android just crash the app in terminated and background state works fine while foreground and since it's Android os error it doesn't leave any logs with it

**Comment by Dimilkalathiya** [comment]
![Uploading Screenshot_2022-03-26-10-14-03-062_com.miui.home.jpg…]()

**Comment by Dimilkalathiya** [comment]
![Screenshot_2022-03-26-10-14-03-062_com miui home](https://user-images.githubusercontent.com/102401667/160225515-92f636e2-c9ce-40d1-8441-dcda91ae72ed.jpg)

**Comment by rafaelsetragni** [comment]
Errors always leave logs. Check Android Studio's LogCat to get all error messages from all apps on any Android device.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
