### ISSUE TITLE
use firebase_messaging with version 0.7.0

### ISSUE THREAD

**Issue by mhdaslam790** [rafaelsetragni/awesome_notifications#453]
hey I saw that firebase messaging is discontinued in latest beta. but my application is completely dependent on firebase messaging.is there any method to make it functional with latest beta

**Comment by mhdaslam790** [comment]
it is working somehow but the problem is the app gets terminated if actiontype is SilentBackgroundAction.

**Comment by rafaelsetragni** [comment]
About the app gets terminated, paste  here your logs.
And about firebase_messaging, the new version is 0% dependent of it. Its fully integrated with another awesome plugin that was not released yet.

**Comment by mhdaslam790** [comment]
i have sent logs in discord

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
