### ISSUE TITLE
Question: Action button limit

### ISSUE THREAD

**Issue by jmccaull** [rafaelsetragni/awesome_notifications#455]
Is there a limit to the number of buttons we can put in a notification? 
Using reminder category and default layout it seems like the limit is 3, is there some limitation in IOS or Android I'm unaware of? Any config that will get me to 4?
Any info would be appreciated, I'm fairly new to mobile development.
Thanks for all the hard work!

**Comment by jmccaull** [comment]
After a bit of Googling I found some stack overflow posts about needing to implement a custom view to have more than three actions in Android. They are a bit dated but I assume that is what is happening here.

**Comment by rafaelsetragni** [comment]
Yes, awesome doesn't have custom layouts yet, and I don't know when it will be done. Sorry.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
