### ISSUE TITLE
[IOS] Autodismissible and locked behavior 

### ISSUE THREAD

**Issue by ViniOkamoto** [rafaelsetragni/awesome_notifications#457]
Hi guys,

First of all, i would like to thank you for the package, it's really "awesome" haha.

So, I have a question about the behavior of locked and auto dismissible parameters on IOS Devices. These parameters are'nt returning the expected behavior like they do on Android. Am I doing something wrong, or is the behavior really different?

**Comment by rafaelsetragni** [comment]
Unfortunately, there is no locked notifications on iOS but autoDismissible should work equal in both platforms. What different behavior have you found on autoDismissible?

**Comment by ViniOkamoto** [comment]
I'm setting autodismissible to my notification and my button, so the expected behavior is don't dismiss the notification, right? On Android the behavior works good, but when i test in IOS devices and i click on notification or button the notification is dismissed
![image](https://user-images.githubusercontent.com/53801461/160963069-5353d99d-92e7-4489-9933-57280a467b77.png)

**Comment by rafaelsetragni** [comment]
Yes, your are right. This behavior is not available on iOS either. Awesome always try to use the maximum features available and, if the resource is not available, it uses the default. This is the main philosophy behind awesome, described at the first topic on our README file. And this is not a question about iOS and Android, but about all other Android distributions as well.

So, what I believe that you need is just to set the features that you wanna use. If the device doesn't have that feature, is pretty fine. That device was designed to work that way and i dont recommend you to try to change it.

**Comment by daniloteamflow** [comment]
Is it possible to have a not dismissible notification for iOS using `awesome_notifications` like this one from Spotify? I'm also struggling with that. 

And thanks for the package!

![IMG_6007E3CE9CF0-1](https://user-images.githubusercontent.com/108285389/180028504-d9a1bbad-9527-4da7-a83f-aa30c7c18fbe.jpeg)

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
