### ISSUE TITLE
Is it possible to receive Data Notification when app terminated?

### ISSUE THREAD

**Issue by jan-koz** [rafaelsetragni/awesome_notifications#458]
Hello, I'm sending push notification from my server to device, and I need to change the title before displaying it to user. Can it be done using this package? FCM notifications are being always delivered when property "notification" != null.

**Comment by rafaelsetragni** [comment]
There is some ways to do it, but I recommend you to do it more simple, already sending the personalized title from your sever. What you can do is to send a silent data and construct a local notification, but it will bring you some problems. The most recommended is to send the notification already done.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
