### ISSUE TITLE
doesn't work in background ios flutter (when app is terminated) 

### ISSUE THREAD

**Issue by htahirov** [rafaelsetragni/awesome_notifications#461]
Hi, awesome_notifications is very useful and great package. But when ios flutter app is terminated, notification doesn't show. Not working in background on ios flutter when app is terminated. How can I do? in android it is okay, but ios is problem. Please help me

**Comment by rafaelsetragni** [comment]
How are you creating notifications while the app is terminated? Have you tried the beta version?

**Comment by htahirov** [comment]
awesome_notifications: ^0.6.21. I used this version. And I used beta 1 version. it didn't work. Can you give some example for get ios flutter notifications in background terminated? I use firebase cloud message. I send request with postman. Android works, but ios flutter app doesn't. I also use iphone 11 real device

**Comment by rafaelsetragni** [comment]
There's two things: first, you need to use beta 2, is the last one. And second, you need to take a look at the extra steps on iOS, on documentation for 6.21.

Im currently dropping the support for firebase_messaging, because the only way to integrate with it is through silent data message. Im pretty close to release the companion plugins to solve it, and you can check it by beta documentation and in our discord channel.

**Comment by htahirov** [comment]
Okay, thanks for response. Good luck!

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
