### ISSUE TITLE
SwiftAwesomeNotificationsPlugin can't find in the scope error swift xcode flutter, incorrect argument label in call (have 'with:', expected 'withRegistry:')

### ISSUE THREAD

**Issue by htahirov** [rafaelsetragni/awesome_notifications#464]
I got error in xcode flutter ios for awesome notifications. Please help me
SwiftAwesomeNotificationsPlugin can't find in the scope error swift xcode flutter, incorrect argument label in call (have 'with:', expected 'withRegistry:')

import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

      SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in          
          SwiftAwesomeNotificationsPlugin.register(
            with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)          
          FLTSharedPreferencesPlugin.register(
            with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
      }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  
  override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {

       Messaging.messaging().apnsToken = deviceToken
       super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
     }
}

**Comment by rafaelsetragni** [comment]
The first error is self explanatory. You need to replace the parameter name `with:` for  `withRegistry:` on GeneratedPluginRegistrant.register method. But the funny part is that function call is automatically generated. I don't know how this parameter name isn't matching.

Then the second one, I haven't recommended to modify `didRegisterForRemoteNotificationsWithDeviceToken`. If you did, please, remove it to avoid any unexpected behavior.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
