### ISSUE TITLE
can't update playSound on Android

### ISSUE THREAD

**Issue by janwol** [rafaelsetragni/awesome_notifications#471]
Trying to update the playSound-Property of a channel (without channelShowBadge) throws a java.lang.ArrayIndexOutOfBoundsException, because of:

https://github.com/rafaelsetragni/awesome_notifications/blob/5f8bc11ffdbdd20bd5c280ce37030a3e5e28634f/android/src/main/java/me/carda/awesome_notifications/awesome_notifications_core/managers/ChannelManager.java#L118

**Comment by rafaelsetragni** [comment]
Yes, you're right. The correct would be:

```Java
channelModel.playSound = androidChannel.getSound() != null;
```

I copied and paste the line above and forgot to change it. This fix will be available at next beta version.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
