### ISSUE TITLE
ios 15 communication notifications support

### ISSUE THREAD

**Issue by zombie6888** [rafaelsetragni/awesome_notifications#474]
it's a very limited information about this notification type [here](https://medium.com/orion-innovation-turkey/whats-new-in-ios-15-notifications-7486e712df40) and [here](https://developer.apple.com/documentation/usernotifications/implementing_communication_notifications)

I have a chat application and for ios i want to show user avatar in notification instead of application icon. 

Is it supported by this plugin? Does it require specific payload or notification type? Because we are using third party service which is sending notifications via FCM

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by fullflash** [comment]
some please confirm does this plugin has communication notifications support. ?
