### ISSUE TITLE
0.7.0-beta.1 Navigating after app killed

### ISSUE THREAD

**Issue by jmccaull** [rafaelsetragni/awesome_notifications#476]
I've been testing with the beta and noticed when the app is killed, I'm not able to navigate using the global key method on a default button type. When the app comes to the foreground, my home from the material app is displayed and not the page I pushed to the current state. Doing some research it seems like this may have something to do with needing to adjust the initial route of the material app based on if the app was started from a notification. Is there currently a way to get this?

**Comment by jmccaull** [comment]
I've been trying to get this working for a while now on beta 2 and the only thing I've gotten to work is wrapping the call to the navigator in Future.delay like so: to:`Future.delayed(Duration(milliseconds: 1), () => MyApp.navigatorKey.currentState?.pushNamedAndRemoveUntil(...`
It works at least but I feel its not a great solution

**Comment by jmccaull** [comment]
I'm also having another issue where my app is now recreating the notification that was just shown because its recreating the app state before processing the user input from the notification. Previously I was using all currently schedule notifications to prevent duplicates. If anyone has a good way to debug the app after it is killed I would appreciate any info there as well.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
