### ISSUE TITLE
How to stop listening to stream when the User Logout/Switched?

### ISSUE THREAD

**Issue by globalwebforce** [rafaelsetragni/awesome_notifications#478]
I have an App, that contains different exercise app, user can choose what they want to notified of e.g yoga every monday 5:30pm.
I want to stop that notification once the user logsout, specialyy on switch account since the new user should not see the yoga notification.

**Comment by jatin-web** [comment]
I am having the same issue

**Comment by RobertHeim** [comment]
During logout you just need to cancel all notifications.
```
await AwesomeNotifications().cancelAll();
```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
