### ISSUE TITLE
How to modify non-data-notification before displaying?

### ISSUE THREAD

**Issue by RobertHeim** [rafaelsetragni/awesome_notifications#481]
When using FCM to send a **data** message to an Android device, it is easy to customize the displayed notification on the device. But given the iOS limitations for data messages it is impossible to implement it reliably (e.g. a use case is an end-to-end encrypted notification).

The native way to implement it on iOS is to not send a data message but a normal notification with an alert string that then is modified (e.g. decrypted) using [UNNotificationServiceExtension](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension) before the notification is displayed to the user.

I am not sure, if a similar mechanism (modifying a non-data-notification before it is displayed) is available on android.

How could the plugin support developers with this? The desired developer experience is, that there is a cross-platform guide on how to implement modifying a notification before displaying it while keeping all code in flutter. A solution could guide the developer to use a data message for Android but set the `alert` for APN/iOS. Currently the plugin does use a `UNNotificationServiceExtension` on iOS but it remains unclear how to employ it. Here, awesome should give more information on how the callbacks for the `didReceive` and `serviceExtensionTimeWillExpire` hooks use a flutter engine. This effectively would allow to modify the notification to the desired information.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
