### ISSUE TITLE
Background color of notification icon 

### ISSUE THREAD

**Issue by prakasharyaman** [rafaelsetragni/awesome_notifications#484]
I get  just a black background on my notification icon in notification bar . is there any way to set color to the background of a notification icon 
i have already tried this : 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/63445447/166187514-8e258929-3565-4252-8916-677401e59c2f.png">
 also tried a few other ways but they are all showing a background as black .

**Comment by rafaelsetragni** [comment]
You can use the color notification property and you mus use an icon with transparent background.

**Comment by prakasharyaman** [comment]
where ?
 i am not able to find notification color property anywhere 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/63445447/166435712-123ff1e2-b038-4432-88b6-ea9f0223e91e.png">
Do you mean through json or someplace else ?

**Comment by ScottishRoss** [comment]
Is it defaultColor?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by Mamasodikov** [comment]
Same issue here
