### ISSUE TITLE
DateUtils.swift fatal error on line 65

### ISSUE THREAD

**Issue by tomas-zeman** [rafaelsetragni/awesome_notifications#485]
Hi, sometimes I get this error that prevents my app from launching:

`awesome_notifications/DateUtils.swift:65: Fatal error: Unexpectedly found nil while unwrapping an Optional value
`

To be able to get the app working again (even start) I must remove the app and install again.

To be honest I don't know how to debug it. Is it a known issue? Could it be for example caused by a badly created notification?
It happens everywhere (simulator, device, testflight)

**Comment by rafaelsetragni** [comment]
Try to switch to the last 0.7.0 beta version and join in our discord server to receive updates.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
