### ISSUE TITLE
Background App Not coming up to foreground

### ISSUE THREAD

**Issue by pagolina** [rafaelsetragni/awesome_notifications#487]
I was able to implement AwesomeNotifications().createdStream.listen successfully, in it am loading a second screen, However, I observed that when app is in background, it invoked _firebaseMessagingBackgroundHandler, Notification is created and received in AwesomeNotifications().createdStream.listen screen navigation is successful BUT the app remain in background, Please how do i bring the app to foreground ?

**Comment by pagolina** [comment]
Am still hoping to get feedback/response on this issue, is 3 days already

**Comment by rafaelsetragni** [comment]
Move to the last beta version. Only the version 0.7.0 is ready to work with background tasks.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
