### ISSUE TITLE
Excessive startup time and too many "Scheduled created" in log

### ISSUE THREAD

**Issue by apoleo88** [rafaelsetragni/awesome_notifications#488]
```
Flutter 2.10.4 • channel stable
Tools • Dart 2.16.2
```
```
  awesome_notifications: ^0.6.21
```

Everytime, the app is open, in the log I can see too many `Scheduled created` logs, like 100-300:
```
D/NotificationScheduler(20026): Scheduled created
D/NotificationScheduler(20026): Scheduled created
D/NotificationScheduler(20026): Scheduled created
```
I have 30 one-time notifications already active instead. 
The problem is that the startup time increases by 10-30 seconds.

Can you give more information about this behavior?

**Comment by rafaelsetragni** [comment]
Yes, this was improved for beta 0.7.0. Move to the beta and check if the problem persists.

**Comment by apoleo88** [comment]
Can I have more information about this issue?
Is there a temporary fix?
Is there an older stable version?

Thank you

**Comment by apoleo88** [comment]
I found out that one problem was that `removeChannel` does not remove the notifications of that channel

**Comment by Subarekha** [comment]
The plugin awesome_notifications doesn't have a main class defined in ..\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\awesome_notifications-0.7.0-beta.3+2\android\src\main\java\me\carda\awesome_notifications

The plugin awesome_notifications doesn't have a main class defined in ..\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\awesome_notifications-0.7.0-beta.3+2\android\src\main\java\me\carda\awesome_notifications\AwesomeNotificationsPlugin.java or ..\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\awesome_notifications-0.7.0-beta.3+2\android\src\main\kotlin\me\carda\awesome_notifications\AwesomeNotificationsPlugin.kt. This is likely to due to an incorrect androidPackage: me.carda.awesome_notifications or mainClass entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the androidPackage entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile



I'm also facing this issue. Can u pls tell me how did u solve this ?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
