### ISSUE TITLE
Chat Notifications Layout

### ISSUE THREAD

**Issue by iosephmagno** [rafaelsetragni/awesome_notifications#494]
Hello guys,
Is it possible for you to provide also the common layout used in chat apps? We need the possibility to display user avatar on the left of the notification tile as whatsapp/telegram do on both ios and android. Layout changes between the two platforms but user’s avatar is there.

**Comment by iosephmagno** [comment]
Attaching examples of required layouts
![3926622C-5135-4878-834E-A1BAC7900A2B](https://user-images.githubusercontent.com/83366073/170420928-5724bd60-c6ff-428d-8969-ae116eaef908.jpeg)
![2B2EED6D-EDDF-48C2-AE73-F815C2DB22EB](https://user-images.githubusercontent.com/83366073/170420932-b08eb40d-a35f-40fc-bbe4-3da63fcbf1b4.jpeg)

**Comment by rafaelsetragni** [comment]
On Android there is already a dedicated layout for chat apps, but on the Awesome plugin for iOS it doesn't yet, although there is already the equivalent for iOS. For now, iOS will group messages as it did before the new iOS chat layout feature. This new iOS layout will not be available for version 0.7.0, but will be implemented shortly right after, in a version 0.7.1.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
