### ISSUE TITLE
futures never complete after requesting provisional permission on IOS

### ISSUE THREAD

**Issue by schultek** [rafaelsetragni/awesome_notifications#498]
Version `0.7.0-beta.4`

When requesting provisional notification permissions on IOS, the request itself and all other calls to some notification methods never complete.

The below call catches a timeout after 30 sec:

```dart
var success = await AwesomeNotifications().requestPermissionToSendNotifications(permissions: [
        NotificationPermission.Alert,
        NotificationPermission.Sound,
        NotificationPermission.Badge,
        NotificationPermission.Vibration,
        NotificationPermission.Light,
        NotificationPermission.Provisional,
      ]).timeout(Duration(seconds: 30));
```

However I still get the following log statement:

> D/Swift: [AWESOME NOTIFICATIONS] Permissions enabled successfully (PermissionManager:503)

After that, all calls to these methods never complete and always time out (even after restarting the app)

```dart
AwesomeNotifications().isNotificationAllowed().timeout(Duration(seconds: 30));
AwesomeNotifications().checkPermissionList().timeout(Duration(seconds: 30));
AwesomeNotifications().requestPermissionToSendNotifications().timeout(Duration(seconds: 30));
AwesomeNotifications().createNotification().timeout(Duration(seconds: 30));
```

**Comment by rafaelsetragni** [comment]
Try to take a look at the example app to see if the same issue happens.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
