### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by amdarshini** [rafaelsetragni/awesome_notifications#500]
Specific page navigation is not working when app is killed.

**Comment by reachcodemed** [comment]
Yes, I am having the same issue. The specific navigation works when clicking on the notification when the app is live, but when the app is killed it doesn't. Any thoughts and guidance would be hugely appreciated :-)

**Comment by rafaelsetragni** [comment]
Guys, what version are you using? Have you tried the last beta version available?

**Comment by reachcodemed** [comment]
@rafaelsetragni sorry I was not using the beta, I have switched and it works a treat! Thank you. @amdarshini if you implement the beta, it will work!

**Comment by minhdanh** [comment]
@reachcodemed can you please share your approach? I used the example like in readme of the latest beta version, but clicking the notification when the app has been killed just show the home route, not my desired route.

**Comment by rafaelsetragni** [comment]
I guess this is because youre running that code inside another isolate, not the main one. You can only have access to an valid context inside the main isolate (which runs your app). You need to use isolate ports to send the message to be processed in the main isolate.

**Comment by niravchavda99** [comment]
> @rafaelsetragni sorry I was not using the beta, I have switched and it works a treat! Thank you. @amdarshini if you implement the beta, it will work!

Doesn't work even when using beta :(

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
