### ISSUE TITLE
Progress notification is not syncing with in app progress

### ISSUE THREAD

**Issue by elmoiv** [rafaelsetragni/awesome_notifications#505]
I am trying to show the user a real-time downloading progress but the notification is not syncing with in-app progress by about 1 second lag.

Here is my code:
- Creating and removing channel
```dart
Future<void> removeProgressChannel() async {
  AwesomeNotifications().removeChannel('progress_channel');
}

Future<void> createProgressChannel() async {
  AwesomeNotifications().setChannel(
    NotificationChannel(
      channelKey: 'progress_channel',
      channelName: 'Progress notifications',
      channelDescription: 'Progress while downloading',
      defaultColor: THM.elmClr,
      ledColor: THM.elmClr,
    ),
  );
}
```
- Download function with notification updater
```dart
Future<bool> download({
  String? fileUrl,
  String? fileName,
  String? type,
  Notifications? notifier,
}) async {
  int old = 0;
  totalSize.value = 0;
  receivedSize.value = 0;

  try {
    await dio.download(
      fileUrl!,
      '$savePath/$fileName',
      onReceiveProgress: (rcv, tot) async {
        receivedSize.value = rcv;
        totalSize.value = tot;
        progress.value = (rcv / tot) * 100;

        if (progress.value.toInt() > old)
          await notifier!.createProgressNotification(
            'Downloading $type'.tr,
            '${progress.value.toInt()}%',
            progress.value.toInt(),
          );

        old = progress.value.toInt();
      },
      deleteOnError: true,
    );
  } catch (e) {
    return false;
  }
  return true;
}
```
- Main process
```dart
Notifications notifier = Notifications();
Downloader downloader = Get.put(Downloader());

bool downloadProcessStatus = true;

await notifier.createProgressChannel();
downloader.activateFlag();

String _type = widget.isGif! ? 'GIF' : 'Video';
String _tmpVid = 'video${Uuid().v4()}.mp4';
String _tmpAud = 'audio${Uuid().v4()}.mp4';

downloadProcessStatus = await downloader.download(
  fileName: widget.isGif! ? widget.mediaName! : _tmpVid,
  fileUrl: widget.mediaUrl,
  type: _type,
  notifier: notifier,
);

await notifier.removeProgressChannel();
```

If you have any idea about the problem here, I would appreciate your help.

**Comment by rafaelsetragni** [comment]
Yes, i have. You are bombarding the Android O.S. With notifications requests. You can't do it too often. The minimum time recommended between each update is 1 second.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by elmoiv** [comment]
The issue was solved by reporting progress every second. Thank you
