### ISSUE TITLE
Icon colour in notification is black

### ISSUE THREAD

**Issue by ScottishRoss** [rafaelsetragni/awesome_notifications#506]
Hi all,

For the notification icon, I have a PNG with a white icon and transparent background. The background of the icon is set with defaultColor and that works fine, but the icon is black even though the image is white?

![Screenshot_20220611-145206](https://user-images.githubusercontent.com/25175556/173190866-e17b8c3b-6ad1-4ba3-9e38-373c2ea2cfc7.png)

Does anyone have any idea why this is happening? Note: this has only been tested on Android 12 so far.

**Comment by ScottishRoss** [comment]
Has anyone else encountered this issue? I haven't been able to solve it yet.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
