### ISSUE TITLE
[Awesome Notifications](13476): null (NotificationThread:58)

### ISSUE THREAD

**Issue by elsystm** [rafaelsetragni/awesome_notifications#512]
I'm getting the following error every time the app receives a push notification in the background state

[Awesome Notifications](13476): null (NotificationThread:58)
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(NOTIFICATION_THREAD_EXCEPTION, null, unexpectedError, null)
#0      StandardMethodCodec.decodeEnvelope
#1      MethodChannel._invokeMethod
#2      AwesomeNotifications.createNotification

The package version I'm using is 0.7.0-beta.4

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
