### ISSUE TITLE
Flutter awesome notifications Background Listen and Save to local Db like hive, Sqlite

### ISSUE THREAD

**Issue by tonmooy** [rafaelsetragni/awesome_notifications#517]
Hello Sir,

I setup Awesome notification on my flutter apps and its work well.

But I have also e notification page like facebook where I store my firebase push. notification offline   when it's appear.

but I don't know how can I save Awesome notification  data offline after notification appear on notification bar.

I want to save notification on hive db,  when my app is on background or closed state but When notification appear I want to save it offline

how can I listen Awesome notification background like firebase push notification.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
