### ISSUE TITLE
Flutter all scheduled notifications come at once

### ISSUE THREAD

**Issue by AbdullahAli1993** [rafaelsetragni/awesome_notifications#518]
I show a notification every 15 minutes, but when the device is idle for a while no notifications come, and when I open the device all notifications come at once

**Comment by rafaelsetragni** [comment]
This happens because of a battery save mode enabled in your device. Also, this behavior changes between each Android distribution. But in general, you must consider that notifications can be delayed or even denied, in all platforms. What you can do is to set correctly the notification's category and educate your users with rationale messages informing then of what your app needs to display notifications properly.

**Comment by reachcodemed** [comment]
I have the same problem on iOS. I have correctly set the notification category. I have set  Time Sensitive Capability and switched off the Notification Grouping in the Notifications settings. The first notification comes at the correct time. Subsequent notifications are grouped with the most recent notification. I am not clear why this is happening

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
