### ISSUE TITLE
Dismissed stream not working on iOS?

### ISSUE THREAD

**Issue by misteroak** [rafaelsetragni/awesome_notifications#519]
I am not getting event from for the dismissed stream, while all other streams work well. I'm doing the following on the iOS simulator on Mac:

1. Notification is displayed: displayedStream is returning a new event
2. Notification is clicked on: actionStream is returning a new event
3. But when I swipe up on the notification when it is displayed at the top section of the screen - I'm expecting dismissedStream stream to fire an event, but nothing happens.

Is there a different gesture that is considered as "dismissed" on iOS?

**Comment by rafaelsetragni** [comment]
This is not a dismiss event, because the notification keeps existing in the notification stack. A dismiss event on iOS is when you swipe left the notification. But iOS do not delivery the dismiss events all the times. To know more about it please check our README documentation.

**Comment by misteroak** [comment]
Got you. Thanks for the prompt response. 
Perhaps worth adding that to the README? Couldn't find that information there.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
