### ISSUE TITLE
Same groupKey but notifications were in different groups

### ISSUE THREAD

**Issue by nvtphong-Executionlab** [rafaelsetragni/awesome_notifications#522]
When I initialize group key like this 

> await AwesomeNotifications().initialize(
>         null,
>         [
>           NotificationChannel(
>               // channelGroupKey: 'basic_channel_group',
>               channelKey: 'basic_channel',
>               channelName: 'Basic notifications',
>               channelDescription: 'Notification channel for basic tests',
>               defaultColor: Color(0xFF9D50DD),
>               ledColor: Colors.white)
>         ],
>         channelGroups: [
>           NotificationChannelGroup(
>               channelGroupkey: 'group_1',
>               channelGroupName: 'Basic group 1'),
>           NotificationChannelGroup(
>               channelGroupkey: 'group_2',
>               channelGroupName: 'Basic group 2')
>         ],
>         debug: false
>     );

Then I use these:

> await AwesomeNotifications().createNotification(content: NotificationContent(
>           id: DateTime.now().microsecond,
>           channelKey: 'basic_channel', title: title , body: body, groupKey: 'group_1'),
>           actionButtons: [
>             NotificationActionButton(key: 'REPLY', label: 'REPLY', buttonType: ActionButtonType.InputField, autoDismissible: true)
>       ]
>       );
>       await AwesomeNotifications().createNotification(content: NotificationContent(
>           id: DateTime.now().microsecond,
>           channelKey: 'basic_channel', title: title , body: body, groupKey: 'group_2'),
>           actionButtons: [
>             NotificationActionButton(key: 'REPLY', label: 'REPLY', buttonType: ActionButtonType.InputField, autoDismissible: true)
>           ]
>       );

For groupKey = 'group_2' they were in the same noti group but for groupKey = 'group_1' they were in different noti group. 
I also tried with groupKey = 'group_3' and it worked as expected but not for groupKey = 'group_1'

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
