### ISSUE TITLE
Scheduled local notification with dynamic content

### ISSUE THREAD

**Issue by lukertaylor** [rafaelsetragni/awesome_notifications#523]
I have a use case where I need the user to be able to configure to receive a daily notification at a time of their choosing. The content of the notification will be retrieved from an external API.

Is this possible with local notifications? Or must I use push notifications? The issue with push notifications is that it is difficult to ensure the user receives their scheduled notification according to their current time zone. So, my preference would be to use local notifications, but not sure if dynamic notification content is possible?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
