### ISSUE TITLE
Notification disappeared/vanish randomly  On the ios side

### ISSUE THREAD

**Issue by mehulTank** [rafaelsetragni/awesome_notifications#527]
I am using this package to display local notifications.
I am getting one issue in this package, especially the ios side. 
in notification center multiple notifications i.e 8 10 notifications from my application. 
I am tapping any notification, and other notifications also disappeared/vanished. 
This issue generates at random times, not every time. anyone can suggest a solution for this issue

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
