### ISSUE TITLE
Toggle notification sound from app settings

### ISSUE THREAD

**Issue by qasim90** [rafaelsetragni/awesome_notifications#529]
I want to allow the user to opt for notification sound from app settings but apparently there's no property in `createNotification` method to enable/disable sound per notification basis. Currently this can only be done per channel via `playSound` property which means channel would need to be recreated for this purpose. Is it possible to make this option per notification?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
