### ISSUE TITLE
Android notifications are always persistent/locked

### ISSUE THREAD

**Issue by qasim90** [rafaelsetragni/awesome_notifications#531]
Since recent versions notifications on android are persistent and can't be dismissed/removed from notifications center. This used to be fine before. Looks like a regression bug. Does anyone face this issue or is it only me?

**Comment by qasim90** [comment]
Just found out this happens since v0.6.19 and onward. Works fine in v0.6.18+2

**Comment by albertshrpv** [comment]
Having the same issue. All dimiss methods not working.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
