### ISSUE TITLE
When Android app is terminated

### ISSUE THREAD

**Issue by dndeus** [rafaelsetragni/awesome_notifications#537]
Hello there, So far I have no issues except one

When I have scheduled notifications and the android app is terminated completely the notifications stop to dispatch

Any suggestions on that? thank you

**Comment by rafaelsetragni** [comment]
Can be the battery save mode of your device disabling background process.

**Comment by dndeus** [comment]
Let me show you my config

`AwesomeNotifications().initialize(
    // set the icon to null if you want to use the default app icon
    'resource://drawable/ic_stat_icon_01',
    [
      NotificationChannel(
        channelGroupKey: 'basic_channel',
        channelKey: 'basic_channel',
        channelName: 'notifications',
        channelDescription: 'notifications',
        defaultColor: Colors.black,
        importance: NotificationImportance.High,
        channelShowBadge: false,
        criticalAlerts: true,
        ledColor: Colors.white
      )
    ],
    // Channel groups are only visual and are not required
    channelGroups: [
      NotificationChannelGroup(
        channelGroupkey: 'basic_channel_group',
        channelGroupName: 'Basic group',
      )
    ],
    debug: true
  );`


`AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: createUniqueId(),
            autoDismissible: true,
            channelKey: 'basic_channel_quiz',
            title: tr(context)?.notification_title,
            category: NotificationCategory.Reminder,
            criticalAlert: true
            // body: 'Simple body'
          ),
          schedule: NotificationInterval(
            interval: 60 * selectedValue,
            timeZone: localTimeZone,
            repeats: true,
            allowWhileIdle: true
          )
      );`

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
