### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by adrianvintu** [rafaelsetragni/awesome_notifications#541]
When FCM-ing a notification, the code would go into infinite loop.

This https://github.com/rafaelsetragni/awesome_notifications/issues/299 fixed it. ie, commenting out
```
    // if #available(iOS 10.0, *) {
    //     UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    // }
```

**Questions to developer**

1.  I also commented out 
```
// application.registerForRemoteNotifications()
```
Is this correct?

2.  Can you add this much necessary change of code on the pub.dev main page? It seems like a very important thing to do.

3. The below code is my `AppDelegate.swift` code. Is it correct?
```
import UIKit
import Flutter
import Firebase
import FirebaseMessaging

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
      
    //https://stackoverflow.com/questions/64014893/my-flutter-firebase-app-is-showing-no-app-has-been-configured-yet
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    
      //https://stackoverflow.com/questions/58246620/apns-device-token-not-set-before-retrieving-fcm-token-for-sender-id-react-nati
    // if #available(iOS 10.0, *) {
    //     UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    // }
    // application.registerForRemoteNotifications()
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
    //https://stackoverflow.com/questions/60350461/flutter-firebase-messaging-not-working-on-ios-when-app-running-in-background-or
    override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {

   Messaging.messaging().apnsToken = deviceToken
   super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
 }
}

```

Thank you so much on your amazing work!

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
