### ISSUE TITLE
NSInvalidArgumentException', reason: 'Attempt to insert non-property list object 

### ISSUE THREAD

**Issue by adrianvintu** [rafaelsetragni/awesome_notifications#542]
My app crashed on iOS 13 with this message  `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object`

The log shows something like this:

```
2022-08-23 17:24:37.808686+0300 Runner[956:37034] [User Defaults] Attempt to set a non-property-list object {
    pendingList =     {
        1661264680 =         {
            1233215 =             {
                autoDismissible = 1;
                body = sd;
                channelKey = "sound_channel_community";
                  ...
                payload =                 {
                    body = sd;
                    dataInt = 0;
                    dataString = "<null>";
                    ...
                };
            };
        };
} as an NSUserDefaults/CFPreferences value for key scheduledDisplayed
```

The piece of code failing is `dataString = "<null>";` It seems iOS does not like null here.

Maybe you can put this in the documentation - if it's not already there?

Please close this ticket, I just entered it to help others in need.

Thank you for your wonderful work!

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
