### ISSUE TITLE
Delay when creating a new notification

### ISSUE THREAD

**Issue by jsfsarkis** [rafaelsetragni/awesome_notifications#546]
I am using this package to create a notification media player, and when I click pause/play I am firing a new notification to display the right buttons.

But there is a delay of more than 1 second and that kind of creates a bad UX, would appreciate any input on how to solve this or maybe I'm going about updating the buttons the wrong way and there's a better way to change the play/pause button other than creating a new notification. 

Thanks.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
