### ISSUE TITLE
Android OS 13 | Push Notification Permission alert not visible on first App launch

### ISSUE THREAD

**Issue by ajaysharmalike** [rafaelsetragni/awesome_notifications#550]
While running application on Android OS 13, application fails to ask the permission for Push Notifications on first app launch. 
But on next app launch, application is asking the system generated Push permission dialog.

Instead of asking the permission on first launch, application ask the notification permission on second app launch. 

**Other information :**
- Flutter Version : 3.0.1
- Awesome Notification Version : 0.6.21
- Android - Target Version SDK : 32
- Android - Compile SDK Version : 32

@rafaelsetragni Could you please help us to know, if `Awesome Notifications` is tested & supported on Android OS 13. It's quite crucial from release perspective as if OS 13 is already released in the market.

**Comment by rafaelsetragni** [comment]
The 6.19 version was built previously Android 13, and because of it, does not contain the last updates. But the request notification permission is done by the same way as the previous Android version, redirecting the user to the notification configuration page.

If you prefer, you can use `permission_handler` plugin to handle it. The permissions are global and Awesome is compatible with it.

For last, Android 13 will be only fully suported on version 0.7.0 and beyond.

**Comment by ajaysharmalike** [comment]
As suggested by you, we have verified the above behaviour on v0.7.0 which is in beta right now but application behaves in the same manner. 
System Permission alert is not shown on first app launch but only get shown on second app launch.

**Other information :**
Awesome Notification Version : 0.7.0
Android - Target Version SDK : 32
Android - Compile SDK Version : 32

Please refer the screenshot for the same.
<img width="600" alt="Screenshot 2022-07-14 at 4 35 38 PM" src="https://user-images.githubusercontent.com/388989/189286083-f95b535c-f7ab-4129-b2fa-3b66e1f1190a.png">

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
