### ISSUE TITLE
Two notifications are shown in the background

### ISSUE THREAD

**Issue by kryakushin666** [rafaelsetragni/awesome_notifications#551]
When I receive notifications, two notifications are shown: Awesome Notification and standard Android. How to disable the standard?

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (!PlatformInfo().isDesktopOS()) {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
    init();
    FirebaseMessaging.onMessage.listen(_firebaseMessagingBackgroundHandler);
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    getLocalUser().then((value) => {
          if (value.id != "0")
            {
              FirebaseMessaging.instance.subscribeToTopic(value.id!),
              print(value.id)
            }
        });
  }
  
 

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {

  //await Firebase.initializeApp();
  AwesomeNotifications().createNotification(
      content: NotificationContent(
    id: 10,
    wakeUpScreen: true,
    channelKey: 'Perspective_chat_chn',
    body: message.notification?.body,
    summary: message.notification?.title,
    //roundedLargeIcon: true,
    //largeIcon: getUserAvatar(message.data['largeIcon']),
    notificationLayout: NotificationLayout.Messaging,
  ));
}

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
