### ISSUE TITLE
open custom screen on incoming call  

### ISSUE THREAD

**Issue by kumawat1990** [rafaelsetragni/awesome_notifications#552]
Not able to open custom screen, i can't found any code/example to display custom screen,  
 need to show custom screen when incoming call on lock screen 
 is there is any mistake in the below code or i missed some thing 
 
![Screenshot 2022-09-12 at 4 31 50 PM](https://user-images.githubusercontent.com/113350131/189637715-02a962dd-35c0-4acc-b718-5166d7c02b4c.png)

**Comment by rafaelsetragni** [comment]
On the example app in our Git repository there is a full example on how to show incoming call notifications:
![image](https://user-images.githubusercontent.com/40064496/192816314-bcf08df7-29ec-42b3-9fe9-5799d0ea1fa5.png)
![image](https://user-images.githubusercontent.com/40064496/192816441-5db43085-5626-42a3-8730-ff6a66ca9ccf.png)

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
