### ISSUE TITLE
[firebase_messaging] EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by abhijeet-navgire** [rafaelsetragni/awesome_notifications#559]
App crashes on receiving push notification in foreground (at least, that's what I think it is, might also be a stream update from Firestore, which happens simultaneously), with the following stack trace:

* thread #1, queue = 'com.google.firebase.messaging.database.rmq', stop reason = EXC_BAD_ACCESS (code=2, address=0x16b453fa0)
    frame #0: 0x0000000192bb11a0 libsystem_malloc.dylib`nanov2_allocate + 4
libsystem_malloc.dylib`nanov2_allocate:
->  0x192bb11a0 <+4>:  stp    x28, x27, [sp, #-0x60]!
    0x192bb11a4 <+8>:  stp    x26, x25, [sp, #0x10]
    0x192bb11a8 <+12>: stp    x24, x23, [sp, #0x20]
    0x192bb11ac <+16>: stp    x22, x21, [sp, #0x30]
Target 0: (Runner) stopped.
Lost connection to device.

Once I remove awesome notification from my packages, it works.

**Comment by eduardo-and** [comment]
Hi, this worked for me:
https://github.com/firebase/flutterfire/issues/8065#issuecomment-1087062719

 using versions:
-  firebase_messaging: 12.0.3
-  awesome_notifications: 0.6.21
or last versions

**Comment by jonasPfeifhofer** [comment]
> 

If this completely solves the issue, then it should be mentioned in the documentation.
For now, I also have the same issue as @abhijeet-navgire.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
