### ISSUE TITLE
Not working in foreground but not working in background in release mode. Everything working well in debug mode

### ISSUE THREAD

**Issue by umangkejriwal1122** [rafaelsetragni/awesome_notifications#564]
Please help

**Comment by rafaelsetragni** [comment]
Sorry, but i can know whats going on with just the informations that you provided. Give me more details as possible, such as:
* Plugin version
* If theres another notification plugin in use
* Result of `Flutter doctor` command
* An example of how are you creating channels and the notification

**Comment by rafaelsetragni** [comment]
@umangkejriwal1122 please, can you recreate your issue? I created a template to guide you on how to report your issue.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of awesome_notifications and awesome_notifications_fcm and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
