### ISSUE TITLE
Android: scheduled notification is not working when app is killed or in the background

### ISSUE THREAD

**Issue by ValeriusGC** [rafaelsetragni/awesome_notifications#616]
Hi! I need to realize as simple as possible task - make scheduled notification with badge on app icon. So i tried to thoroughly copy just needed code from your example and result is that notification fires (without badge yet) but only when application in foreground.

Where is that key point to make it work in background or when killed? 
Manifest has more then enough things
```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT"/>
```
channels copied too
```
          NotificationChannel(
              channelGroupKey: 'basic_tests',
              channelKey: 'basic_channel',
...
              importance: NotificationImportance.High),
          NotificationChannel(
            channelGroupKey: 'schedule_tests',
            channelKey: 'scheduled',
...
```
dunno what to do yet.
It would be very useful to have alongside not so "God example"  but  just simple one with minimalistic but yet frequently occurring case as mentioned above - simply firing scheduled notification with badge on icon, as starting point to learn more complex tasks in future. 
Thanks in advance.

**Comment by rafaelsetragni** [comment]
> dunno what to do yet. It would be very useful to have alongside not so "God example" but just simple one with minimalistic but yet frequently occurring case as mentioned above - simply firing scheduled notification with badge on icon, as starting point to learn more complex tasks in future. Thanks in advance.

Yes. I did it. You can find a more simple example in the pub.dev example page. Take a look:
https://pub.dev/packages/awesome_notifications/example

> So i tried to thoroughly copy just needed code from your example and result is that notification fires (without badge yet) but only when application in foreground.

Maybe this is about the notification channel not being able to change after installing the app and creating the channel. You need to uninstall and reinstall your app for your channel changes to take effect on Android 8+. Take a look at:

https://pub.dev/packages/awesome_notifications#-important-notes
... and search for all important notes topics. There is one about Schedules and another about Notification Channels that you must be aware of.

But, the most important: How are you creating these schedules in the background and while the app is killed, and even while your app is on foreground? Is that what you want to do? Create schedules in background or while your app is killed?
OBS: That's why I avoid expressions like "it's not working", they can mean literally anything and don't provide any useful information.

**Comment by rafaelsetragni** [comment]
Also, im planning to launch some entire example apps for each aspect, like: schedules, calls, media player, chat app, progress bar, etc.

**Comment by ValeriusGC** [comment]
Hi there, @rafaelsetragni. 
Thanx a lot for your kindly quick replies. It helps a lot.

> But, the most important: How are you creating these schedules in the background and while the app is killed, and even while your app is on foreground? Is that what you want to do? Create schedules in background or while your app is killed?

I just want simplest functionality: to tap scheduled button, set time, close app and get notification somewhere in time. 
![photo_2022-10-28_08-20-00](https://user-images.githubusercontent.com/3320861/198495177-6892ef3e-1971-4437-a4a8-1c871a342a35.jpg)

The key is `close app`, i.e. when app is removed from memory.
![photo_2022-10-28_08-24-20](https://user-images.githubusercontent.com/3320861/198495193-302ebcb3-2850-43e4-8c19-b4807a7a3fa9.jpg)

Your `extended` example works well. 
https://user-images.githubusercontent.com/3320861/198495449-b4454f71-7d9b-4f16-9d6c-202bd44682b4.mp4

But when i tried to repeat steps from documentation my notifications fired only when my application is in memory.

Well, i did some more specific steps. I thoroughly copied your code from your example to mine - not full but only with desired notifications and buttons as i wrote in the previous post. It did not help me - killed application did not fired notifications. So i supposed that i missed something due to huge size of example. I understand it is my problem, but i really like your library and want to use it. That's why i write here ))

> OBS: That's why I avoid expressions like "it's not working", they can mean literally anything and don't provide any useful information.
Agree totally, but i seemed i wrote enough information [here](https://github.com/rafaelsetragni/awesome_notifications/issues/616#issue-1423441544). I mentioned that i'd like `make scheduled notification with badge on app icon`. I mentioned about manifest and channels. 
To be more specific what i'd like to get:

1. Open calendar and set date/time for notification
2. Close application and forget about it at all ))
3. In set time get notification and badge on app icon (like this)
![photo_2022-10-28_08-47-48](https://user-images.githubusercontent.com/3320861/198498054-a95a163a-2c16-4abb-a454-d886d14c5460.jpg)

Very, very simple and modest needs.

**Comment by ValeriusGC** [comment]
I'll try my best again, there is another idea )). Thanx for your replies.

**Comment by ValeriusGC** [comment]
Hi, @rafaelsetragni.

With your kindly help and my patience I made it ))
First, I copied full of your code into my project, then I was peeling unnecessary functions one by one checking after every step ))
When only the right one remained, I repeated this one in my standalone test project just on my own.

IMHO there is a lack of documentation and use-case simple samples. I see - your masterpiece is huge and covers everything and  all business cases. But sample project some cumbersome and minimalistic in terms of documentation.

But your patience and quick answers helped me a lot so thank you very much!

**Comment by rafaelsetragni** [comment]
> Hi, @rafaelsetragni.
> 
> With your kindly help and my patience I made it )) First, I copied full of your code into my project, then I was peeling unnecessary functions one by one checking after every step )) When only the right one remained, I repeated this one in my standalone test project just on my own.

Nice! Im glad that you made it!

> IMHO there is a lack of documentation and use-case simple samples. I see - your masterpiece is huge and covers everything and all business cases. But sample project some cumbersome and minimalistic in terms of documentation.
> 
> But your patience and quick answers helped me a lot so thank you very much!

Yes. I will do exactly that and publish each example app in the new awesome's web portal.

**Comment by rrnicolay** [comment]
@ValeriusGC Could you kindly post your working code for scheduled notifications?
I'm having trouble with scheduled ones in a real device (Android 13).

**Comment by ValeriusGC** [comment]
> @ValeriusGC Could you kindly post your working code for scheduled notifications? I'm having trouble with scheduled ones in a real device (Android 13).

Hi, [here is the link](https://disk.yandex.ru/d/NHQs94kxsPXAxw).

- Code is based on ordinal `Flutter Counter Sample Project`. 
- Read carefully [documentation](https://pub.dev/packages/awesome_notifications#-configuring-android)'s part "Configuring Android"
- Keep your attention to AndroidManifest
```
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
```
And keep in mind that on new Android OS versions  scheduled notification work well only in release mode so try to create release apk.

**Comment by michael-wang** [comment]
I know it's been a while but I want to leave some message for people who still encounter this issue and end up here.

I encountered this issue and later realized it only happens during development, here's the steps:

1. With vscode, run app on real device.
2. Schedule notification.
3. Terminate app from vscode (because I want to see if notification show up even after app killed).
4. Notification never show up.

How do I fix this? No, I don't.

This issue disappears when I run App like normal user (launch App from device instead of vscode). I can receive notification when App is in foreground, in background, or even when I killed App through launcher (swipe-up from bottom of screen and swipe the App to kill it).

So the real issue is what's difference between killing App by Android launcher and vscode, which can be of interest by developer of this package.

My point is, as App developer, you are good, your App is working as expected (well beside during development). Just remember to verify notification like normal user instead of you'd normal do (with vscode).
