### ISSUE TITLE
scheduling notifications on Android without USE_EXACT_ALARM permission

### ISSUE THREAD

**Issue by jweidner-mbible** [rafaelsetragni/awesome_notifications#635]
Is it possible to schedule a notification at an inexact time so that you don't have to add either the android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM permission to your AndroidManifest.xml file?

https://github.com/rafaelsetragni/awesome_notifications#-scheduling-a-notification discusses needing this permission for precise notification times, but I did not find details on how to schedule a notification for an imprecise time.

Currently, when I use AwesomeNotifications().createNotification specifying
`schedule: NotificationCalendar.fromDate(
          preciseAlarm: false, date: DateTime(now.year, now.month, now.day, now.hour, now.minute+1))`
I get an error saying my project "needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms."

**Comment by rafaelsetragni** [comment]
Can you share here how are you creating your schedules?

**Comment by jweidner-mbible** [comment]
I'm testing with your example app.  I've removed the `   <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>` from the Android Manifest and trying to tap on the second button which calls your scheduleNewNotification() method.

**Comment by rafaelsetragni** [comment]
Im currently implementing a new feature to set the delayTolerance, and for these cases the schedule will not be exact. It will be available on next release.

**Comment by rafaelsetragni** [comment]
Hi @floriandootz and @jweidner-mbible, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
