### ISSUE TITLE
Remove "supported" platforms from pub.dev

### ISSUE THREAD

**Issue by Noahbanderson** [rafaelsetragni/awesome_notifications#637]
PROBLEM: 

Without actual support for Web or Desktop environments in your most recent release, it is misleading and irresponsible to claim you support every platform on the awesome_notifications pub.dev webpage.

SOLUTION: 

Add some dialog at the top of your README indicating support will soon come to Web and Desktop, and remove the Linux, Macos, Web, and Windows badges.

**Comment by rafaelsetragni** [comment]
> PROBLEM:
> 
> Without actual support for Web or Desktop environments in your most recent release, it is misleading and irresponsible to claim you support every platform on the awesome_notifications pub.dev webpage.
> 
> SOLUTION:
> 
> Add some dialog at the top of your README indicating support will soon come to Web and Desktop, and remove the Linux, Macos, Web, and Windows badges.

But that was EXACTLY what i did! 😆😆😆
Take a look:

![image](https://user-images.githubusercontent.com/40064496/199820394-5f11591b-d58c-4e5f-855e-56f6e22aa719.png)

**Comment by rafaelsetragni** [comment]
These badges are generated automatically since I implemented the PlatformInterface class in the source code to support all future platforms. Without it, projects with awesome_notifications that contain web/desktop versions will not compile. And PlatformInterface is MANDATORY to start implementing other platforms now in version 0.7.X.

I cannot downgrade the platform supports, reverting all improvements done until now to update this plugin into the new Flutter's standard, and break all projects that contains desktop and web support just to remove the badges in pub.dev page.

**Comment by Noahbanderson** [comment]
You're right, projects won't compile for web and desktop if you removed support. Which is exactly what **_should_** happen. No existing web/desktop projects will break because those projects won't depend on something that doesn't work in the first place. 

What improvements would need to reverted? There is nothing but placeholder and stub code in the web/desktop implementations. So why exactly can't you downgrade platform support? I would recommend removing the web/desktop support from the master branch, and move them to a feature branch where development work can take place.

**Comment by rafaelsetragni** [comment]
Let me check if i understood you:

What you're suggesting is to me to implement the new PlatformInterface architecture, removing and redone all the work that i had to make in all these classes:

![image](https://user-images.githubusercontent.com/40064496/200357698-59a9ad30-3f55-472b-a6c0-ef678192b69a.png)

...and then make all the projects that are already using awesome_notifications successfully on Android and iOS and that have now been expanded to work with web and desktop just BREAK, forcing these projects to REMOVE awesome_notifications TOTALLY and REWRITE ALL LOGIC to display local notifications with other plugins?

Yep, this sounds like a `pretty bad idea`...

Why instead of just wasting my time with such a clever suggestion like that, don't you fork this project, implement the web and desktop version, and send it back to me? This is a solution to your problem that I fully support.

If you do that, i will lovely receive with my arms open your pull request. Otherwise you can read that HUGE banner about the development stage and wait for the new releases to come.

**Comment by Noahbanderson** [comment]
That's not what I'm suggesting at all. And I'm not criticizing the hard work you've put into this project.

Let's make a couple of things clear: 1) removing support for web and desktop should NOT break iOS/Android builds. 2) If a web or desktop project does depend on this plugin, then it doesn't work to begin with; So removing support is benign.

Perhaps the solution is a more simple, what would happen if you removed [these lines](https://github.com/rafaelsetragni/awesome_notifications/blob/master/pubspec.yaml#L46-L54)? It would seem reasonable that pub.dev is using the `pubspec.yaml` to generate the platform badges.

Side note: Chill out. If you want individuals, like myself who want to provide feedback and improve the incredible work you've set out to do, it would be wise to control your temper and sarcasm. "You catch more bees with honey than vinegar".

**Comment by Noahbanderson** [comment]
Tested on - 

Android: Working
iOS: Working
MacOS: No longer supported
Web: No longer supported

**Comment by AAverin** [comment]
Totally agree with this ticket. As a new user of the plugin, I was very confused first seeing that MacOS is supported and then learning then it's not.
@rafaelsetragni  Could you please remove confusing claims of Desktop support from pub.dev until implementation is finished and tested?

**Comment by AAverin** [comment]
@lijy91 already built of https://github.com/leanflutter/local_notifier for desktop local notifications. Maybe there can be collaboration with `awesome_notifications` do bring desktop functionality?

**Comment by rafaelsetragni** [comment]
Yes @@AAverin, this looks a good idea. And i will implement the basic support for other platforms pretty soon.
