### ISSUE TITLE
Badge works incompatible in release and debug modes.

### ISSUE THREAD

**Issue by tyypgzl** [rafaelsetragni/awesome_notifications#665]
Each time the createNotification function is run in debug mode, the badge increases automatically. In release mode, this does not work properly.

I was not sure whether it was a bug or a quest because there was not enough information to use the badge.

**Comment by rafaelsetragni** [comment]
@tyypgzl you erased the issue form with some crutial questions that i need to know about your issue, because the badge behaves differently on each platform and Android distribution. I just can't help you.

I suggest you to recreate this issue and answer all the questions propertly. This way i can understand better your case.
I will mark this issue as invalid as it violates the community guidelines to post issues.
