### ISSUE TITLE
cant update notification through AndroidForegroundService.startAndroidForegroundService

### ISSUE THREAD

**Issue by Ravensof** [rafaelsetragni/awesome_notifications#680]
Hi, im using `AndroidForegroundService.startAndroidForegroundService` for player to keep my app in background and control it via notification.
when i call first time `AndroidForegroundService.startAndroidForegroundService` all is ok
but when i call it second time notification dissappear
when i call it 3d time it shows again
4d dissappear.

it worked fine in v0.6.x.

notification update works if i replace `AndroidForegroundService.startAndroidForegroundService` to `<AwesomeNotifications>.createNotification` but i need to keep app in background

**Comment by SupremeDeity** [comment]
Ran into a similar issue, i'm not sure if a fix can be applied to `AndroidForegroundService.startAndroidForegroundService()` since starting a service takes more times compared to notification.

I tried doing something like this: #682. I'm not sure if this is the correct way but from i have seen, updating a service notification is done in a similar manner when working with native android dev.

**Comment by Ravensof** [comment]
@SupremeDeity thanks, that's can be useful while waiting for fix
