### ISSUE TITLE
Set a duration for notifications

### ISSUE THREAD

**Issue by Lachlan24** [rafaelsetragni/awesome_notifications#7]
Hey, i know this is a sort of an usually feature request. But is it possible to set a duration for notification's in which after the duration is complete the notification will cancel it's self and in the event the notification was never triggered (i.e the users phone was off) then dont trigger in the first instance if the duration has already passed. Or alternatively schedule a cancellation of a notification for a specific time, this would achieve the same effect.

**Comment by rafaelsetragni** [comment]
Its a intressting idea!

The problem always falls on iOS side. iOS is terrible with processing when your app is terminated (killed). On android this can be easly acchieved using AlarmManager, but on iOS you dont have a feature like this.

But, as soon as i discover how to run small tasks programaticaly on iOS, such as android does, with sure ill go implement this feature. Thank you for your suggestion!

**Comment by rafaelsetragni** [comment]
Ive put your suggestion on "Next Improvements" on README page. I hope soon we could find a way to put your suggestion working.

One of possible solutions is to create a extra option to cancel your past notifications with a silent push command. What do you think about it?

**Comment by dudizimber** [comment]
@rafaelsetragni 
I've implemented the silent push, and it works perfectly when the app is in the foreground or background. But it does not work when the app is killed.
The way I did that was by defining that the ID -13 is the delete command, and using the `cancel()` function in the callback of the `displayedStream` stream. I believe that it is not working because the callback will only be triggered once the app is opened.

Can you think of a solution to delete the notification even when the app is killed?

**Comment by rafaelsetragni** [comment]
Using the new version you can do anything with the firebase method onBackgroundMessage.

**Comment by dudizimber** [comment]
@rafaelsetragni 
The documentation for the new version is not complete.
I tested it but I did not find a way to prevent firebase from showing the notification before this plugin.

The workaround was to use `cancelAll` in the `onBackgroundMessage` method, and then show the AwesomeNotification. The problem is that I cannot remove only the Firebase notification, as the ID is a String, while the `cancel` method expects an Integer.

**Comment by rafaelsetragni** [comment]
The data standard to send push notifications also changed. Is not necessary to send push with empty title.

**Comment by Wizzel1** [comment]
Maybe https://pub.dev/packages/workmanager
can help here?

**Comment by rafaelsetragni** [comment]
The iOS is the big problem. Is not possible to ensure the execution time in iOS to use for special notification handling cases, such as complex schedules, etc. The minimum time between each background run is 15 min,  but apple algorithms could for misterious reasons put your application in background suspend mode for undetermined amount of time. 

If i cannot ensure the correct execution for some plugin function, i cannot release it to the public. I have a really powerful crontab functionality to schedule notifications, in a very efficient  way, but i cannot use it because Apple does not allow any script to run in precise mode while in background.

Because of that, since version 0.0.6 i have had to downgrade the Awesome Notification's schedule capabilities. Unfortunaly.
