### ISSUE TITLE
Minimal macOS and Linux support exist?

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#704]
In readme it is written that 

> Awesome Notifications **contains all features available in flutter_local_notifications plugin** and more, so you can replace totally flutter_local_notifications in your project.

`flutter_local_notifications` supports macOS and Linux but in our package it is written that we have 0% support for them

![image](https://user-images.githubusercontent.com/9304740/212336851-ff9a7506-ba92-43a1-9544-5b776b36d1b5.png)

So I am not sure which one is it, if we can push simple notifications to mac and Linux like `flutter_local_notifications`  then it is more than 0% support for macOS and Linux

**Comment by rafaelsetragni** [comment]
Yes, the support was added in the last plugin update, and that turns possible to compile your app for linux, windows, web and mac, even if the implementations for those platforms wasnt done yet. But they definetely will be done i some near versions. That's why the plugin supports all platforms, but the development stage for the other platforms are still 0%.

**Comment by guyluz11** [comment]
Ok thanks for the clarification.

If you want to keep it open for organization feel free, if not I leaving it to you to close this issue :D
