### ISSUE TITLE
in iOS, my app shutdown when click the notification

### ISSUE THREAD

**Issue by longvhv** [rafaelsetragni/awesome_notifications#72]
I turn off the app, when my iphone receive a new notification, I click to the notification to open the app, the app open but shutdown immediately.
When I test on the simulator, or in android phone, that error is not appeared.
I compile app use version 0.0.5+4.
Thank you!

**Comment by rafaelsetragni** [comment]
Start the application in debug mode, hut open the android folder, instead the project one. After that, click on attach to process and type your app name to start to debug since it wake up. So click on your notification to catch the error.

You also can inspect the app logs with LogCat panel in your Android Studio.
