### ISSUE TITLE
Incompatible with intl: ^0.18.0

### ISSUE THREAD

**Issue by Elemenopeee** [rafaelsetragni/awesome_notifications#735]
I tried upgrading the intl package in my project to intl: ^0.18.0 from intl: ^0.17.0 but I am getting the message ->

Because awesome_notifications >=0.7.0-beta.7+3 depends on intl ^0.17.0 and my_app depends on intl ^0.18.0, awesome_notifications >=0.7.0-beta.7+3 is forbidden.
So, because my_app depends on awesome_notifications ^0.7.4+1, version solving failed.

A recent version upgrade will be great I think. Thanks!

**Comment by stukdev** [comment]
Same problem, an upgrade is necessary.

**Comment by kevinyyykc** [comment]
Please upgrade. Thanks

**Comment by doublegarts** [comment]
Can someone fix it please?

**Comment by rafaelsetragni** [comment]
Hi everyone!
You just need to use dependency_overrides on `pubspec.yaml` file:

https://dart.dev/tools/pub/dependencies#dependency-overrides
```yaml
dependency_overrides:
  intl: ^0.18.0
```

**Comment by GiulioWecove** [comment]
An update will be great!!

**Comment by guyluz11** [comment]
This pr is for that (but has conflicts)
https://github.com/rafaelsetragni/awesome_notifications/pull/727

**Comment by nuno84** [comment]
Same problem here.

**Comment by rafaelsetragni** [comment]
Hi @Elemenopeee, @nuno84, @GiulioWecove, @kevinyyykc, @stukdev and @doublegarts, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by mbfakourii** [comment]
temporary

```
  awesome_notifications:
    git:
      url: https://github.com/mbfakourii/awesome_notifications.git
      ref: ef2eb8a766fb12bf1fe1a8f49dc0ce333272abf5
```

**Comment by ynsmrkrds** [comment]
> 

Hi @rafaelsetragni. The release versions of 0.7.5-dev.2+1 still not working. Can you release a version with intl version 0.18.0?

**Comment by guyluz11** [comment]
> > 
> 
> Hi @rafaelsetragni. The release versions of 0.7.5-dev.2+1 still not working. Can you release a version with intl version 0.18.0?

There is newer prerelease version [0.7.5-dev.3](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.3), test with

**Comment by ynsmrkrds** [comment]
> > > 
> > 
> > 
> > Hi @rafaelsetragni. The release versions of 0.7.5-dev.2+1 still not working. Can you release a version with intl version 0.18.0?
> 
> There is newer prerelease version [0.7.5-dev.3](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.3), test with

Hi @guyluz11. I tried this version, but not worked. Version 0.7.5-dev.3 is compatible with intl version 18.0.1. Must be a version of awesome notifications compatible with intl version 18.0.0. The error I get is as follows:

**Resolving dependencies...
Because awesome_notifications >=0.7.5-dev.1 depends on intl ^0.18.1 and every version of flutter_localizations from sdk depends on intl 0.18.0, awesome_notifications >=0.7.5-dev.1 is incompatible with flutter_localizations from sdk.
So, because tabularasa depends on both flutter_localizations from sdk and awesome_notifications 0.7.5-dev.3, version solving failed.**

I temporarily resolved the error with dependency_overrides. I am waiting for your support to resolve the error. Thanks.

```
dependency_overrides:
  intl: ^0.18.0
```

**Comment by guyluz11** [comment]
Should stay open
