### ISSUE TITLE
NotificationInterval difference from Android and iOS

### ISSUE THREAD

**Issue by Dancas93** [rafaelsetragni/awesome_notifications#746]
## **1 - Describe the bug**

if I created a notification Interval with the following code 
``` schedule: NotificationInterval(interval: 60, timeZone: localTimeZone, repeats: true, allowWhileIdle: true));```
on iOS the interval was interpreted as seconds (so 60 is equal to 1 minute) instead in Android it is interpreted differently so 60 is equal to 6 seconds.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by razfazz** [comment]
having the same issue

**Comment by rafaelsetragni** [comment]
Hi @Dancas93 and @razfazz, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
