### ISSUE TITLE
ReceivedNotification add intendedTime function

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#764]
**Is your feature request related to a problem? Please describe.**
I am getting a new notification and with it ReceivedNotification object and I want to know for what time it was intended to appear.
Saw 2 similar methods that retrieve DateTime objects but I think they don't do what I am searching for.
We have [createdDate](https://pub.dev/documentation/awesome_notifications/latest/awesome_notifications/ReceivedNotification/createdDate.html) which is the date the notification got created for the first time (not intended to be displayed),
we have [displayedDate](https://pub.dev/documentation/awesome_notifications/latest/awesome_notifications/ReceivedNotification/displayedDate.html) which I am imagining could be different time then the intended date if the device was off when the notification was supposed to arrive.

**Describe the solution you'd like**
A function named `intendedTime` retrieved the original time the notification was planned for.

**Describe alternatives you've considered**
Saving this time with some local database like shared preference.

**Comment by rafaelsetragni** [comment]
Unfortunately, its not possible to get the exact time when a notification is displayed on iOS devices because isn't possible to execute any code at this moment. On Android the displayedDate behaves exactly as you described, but on iOS due this limitation this value is calculated, and may not match with the exact time when it happened as you described.

**Comment by guyluz11** [comment]
intendedTime  != firedTime 

So the iOS limitation does not affect this value as it is pre-known when the notification got created.

Currently I am adding it manually to the payload

**Comment by rafaelsetragni** [comment]
Now i got it. This can be trick to implement on iOS. I will need to study how to do it in near future. So, for now i will let this opened as a future implementation on roadmap.

**Comment by rafaelsetragni** [comment]
Because i cant execute code to update these values between each app execution. So, if for example has passed 3  notifications displayed times and the app goes back to live, i gonna need to calculate these respective values and i need to ensure the correct one. And the same thing is valid for Android, where i need to be very efficient at background execution and the background execution also can be denied.

**Comment by rafaelsetragni** [comment]
This is not true. I can have one created event and unlimited displayed events, each one with a different date.

**Comment by guyluz11** [comment]
I think we are talking about 2 different values.
This is what I think about it, tell me if it is the same

Created date = the date the notification got created. This date is always in the past.

Intended time = the date the notification should arrive. The intended date the notification should trigger

Fired time = the actual time the notification got triggered and got showed to the user. Probably will be hard to extract in ios since it is problematic to run code in the background


The first 2 "Created date" and "Intended time" never change and is pre-known.
I talked about only the first 2.

**Comment by rafaelsetragni** [comment]
> The first 2 "Created date" and "Intended time" never change and is pre-known. I talked about only the first 2.

No, its not. The displayed date is calculated by OS and its not pre-known. I gonna need to calculate it for every event delivered to onDisplayMethod.

**Comment by guyluz11** [comment]
.

**Comment by guyluz11** [comment]
.

**Comment by guyluz11** [comment]
.
