### ISSUE TITLE
removeFromActionEvents: true does not work

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#766]
## **1 - Describe the bug**

`removeFromActionEvents: true` in ```AwesomeNotifications().getInitialNotificationAction(removeFromActionEvents: true)``` does not do anything.

I will keep it short as I see that this already got resolved in master but not in the version from pub dev. So next version it will probably get fixed and I open the issue is just to keep track of that.

This line is missing in the version from pub.dev, so the value of `removeFromActionEvents` does not being transferred to `AwesomeNotificationsPlatform.instance.getInitialNotificationAction()`
https://github.com/rafaelsetragni/awesome_notifications/blob/5e9e2b6b5cc31b463cdda709bc2ef17cb44559b9/lib/awesome_notifications.dart#L194

## This issue seems to be fixed in the master branch so it is only open to keep track until it arrives to pub.dev

package version -  `awesome_notifications: ^0.7.4+1`

**Comment by rafaelsetragni** [comment]
Hi @guyluz11, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by guyluz11** [comment]
Thanks
