### ISSUE TITLE
Getting package incompatible Error 

### ISSUE THREAD

**Issue by mrwebbeast** [rafaelsetragni/awesome_notifications#774]
Because awesome_notifications >=0.6.20 <0.7.5-dev.1 depends on intl ^0.17.0 and awesome_notifications >=0.7.5-dev.1 depends on intl ^0.18.1,
  awesome_notifications >=0.6.20 requires intl ^0.17.0 or ^0.18.1.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_localizations from sdk is incompatible with
  awesome_notifications >=0.6.20.
So, because mrwebbeast depends on both awesome_notifications ^0.7.4+1 and flutter_localizations from sdk, version solving failed.

**Comment by guyluz11** [comment]
Same, I think ^0.7.4+1 version somehow got changed.

You can solve it for now until the new version will come out with the following line in the `pubspec.yaml` file

```
dependency_overrides:
  intl: ^0.18.1
```

**Comment by Maatteogekko** [comment]
flutter sdk depends on intl 0.18.0, so the constraint on awesome_notifications should be lowered to match that.
Otherwise the override will be needed until the next stable flutter release

**Comment by rafaelsetragni** [comment]
Hi @Maatteogekko, @guyluz11 and @mrwebbeast , i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by hasnaintt** [comment]
@rafaelsetragni  When I use the following combinations:

intl: ^0.18.1
awesome_notifications: ^0.7.5-dev.2+1

I'm getting the following error:

"Because appName depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because appName depends on intl ^0.18.1, version solving failed."

And when I use these combination: 

intl: ^0.18.0
awesome_notifications: ^0.7.5-dev.2+1

I'm getting the following error:

"Because awesome_notifications >=0.7.5-dev.1 depends on intl ^0.18.1 and every version of flutter_localizations from sdk depends on intl 0.18.0, awesome_notifications >=0.7.5-dev.1 is incompatible with flutter_localizations from sdk.
So, because daffi_wallet depends on both flutter_localizations from sdk and awesome_notifications ^0.7.5-dev.2+1, version solving failed."

**Comment by rafaelsetragni** [comment]
So, you gonna need to use dependency_override to update the intl dependency to ^0.18.1

**Comment by krosiek** [comment]
@rafaelsetragni So we solved problem by introducing exactly the same problem :D

**Comment by rafaelsetragni** [comment]
The last version is 0.18.1. Im using the last one. This is what i can do about it.

**Comment by guyluz11** [comment]
Let's keep this issue open

**Comment by guyluz11** [comment]
.
