### ISSUE TITLE
target user segment only avaliable via firebase console 

### ISSUE THREAD

**Issue by Ali1Ammar** [rafaelsetragni/awesome_notifications#82]
i see that if we use this plugin with firebase_messaging 
firebase_messaging will not work
 is there any way to disable this 
use awesome for local notifications 
and use firebase_messaging for push notifications
or maybe  add some field in request to select  with which package  procces the  notifications

what i want to do is use the target user segment tabs inside firebase console 
i search and it is only avaliable via console

![image](https://user-images.githubusercontent.com/18378766/103811270-b697ef80-506d-11eb-90f5-30d039e058fd.png)

i also try to sent the content from console and it is work sometime but i have limit of 200 char so i couldn't write big text or add url 
edit::
**this not always work i things if the  App in Foreground will work**
![image](https://user-images.githubusercontent.com/18378766/103812562-bac50c80-506f-11eb-9f69-7aa0f053077e.png)

**Comment by Ali1Ammar** [comment]
i also noticed that if we put "Notification image (optional)" from console the notifications processed via firebase_messaging but only image shows without title and body

we need this to be a feature but without deleteing title and body 😁😁

**Comment by rafaelsetragni** [comment]
If i disable firebase connection for this plugin to be used  with firebase_messaging, how do you gonna use all the resources from awesome local notification combined with push while your app is killed?

This plugin is built to dismiss the necessity to use firebase_messaging. You don't need to use it because firebase messagin was already implemented on native code by this plugin.

Are you using iOS? Empty title and body is caused by target extensions not corretly configured. Take a look at this topic:

[IOS - getting "receiveNotification: notification discarted" if i send notification from FCM](https://github.com/rafaelsetragni/awesome_notifications/issues/41)

**Comment by Ali1Ammar** [comment]
no i am only using android 
I now the benefit of this package it is awesome very very awesome 
but someplace we need to use firebase console like i describe above when we need to target by user segments it can't be set by the api.

i will  remove firebase and try again 
thanks for answering

**Comment by rafaelsetragni** [comment]
Try to use this plugin deactivated.

Go to FCMService.java and erase this content. Now awesome_notification will not work with firebase any more.

But i dont have any idea how do you gonna create the local notifications from a push notification while your app is terminated. If you achieve this, please, tell me how you did it because this can let this plugin more flexible.

**Comment by Ali1Ammar** [comment]
thank you so much i will try 
i don't use this plugin with push notifications 
i used with workmanger 
i schedule background jobs every two hour 
then get some data from local db
and create notifications with buttons based on this data
