### ISSUE TITLE
Dismiss button

### ISSUE THREAD

**Issue by myrkgard** [rafaelsetragni/awesome_notifications#83]
I need a 'dismiss' button in a notification. Use case goes as follows: The app is closed or in the background. A scheduled notification is shown. It says: 'Do you want to open the app?  YES   NO'. The YES button is of ```buttonType: ActionButtonType.Default``` and pressing it will activate the app. The NO button shall close the notification and remove it from the screen's notification bar without activating the app. Is this already possible with the current implementation?

**Comment by myrkgard** [comment]
My app behaves different from what seems to be expected from the documentation. Doc says:

> DisabledAction [with] App Terminated (Killed) [=>] keeps the app terminated 

Instead, for me, it activates the app, both with ```autoCancel``` being ```true``` or ```false```.

It also says:

> KeepOnTop: after user taps, the notification bar is not closed

It works for ```autoCancel: false```,  but closes the notification bar with ```autoCancel: true```. 

So ```KeepOnTop``` with ```autoCancel: true``` gives the desired 'dismiss' button, but I wonder if this is the intended behavior. Maybe I'm just misunderstanding the documentation?

**Comment by rafaelsetragni** [comment]
But you are not trying to do something that the notification already does since the begining? Because if the user want to not open the app, he just swipe out the notification. There is no need to implement this functionality.

And if he want to go to your app, he just tap the notification. Or, you can just add a button "go to X", like a shortcut to go to a specific place inside your app.

**Comment by myrkgard** [comment]
> swipe out the notification or do nothing swiping the tray

Well, that's a good point. Many apps have a dismiss button but one could indeed omit it. 

Anyways: What I described in my second post: Is that how you want it to behave, is the text from the documentation outdated, is this a bug, or am I missing something?

**Comment by rafaelsetragni** [comment]
Yes, its a bug. I could not find yet how to click on button, close the tray and do not call the app while is terminated. Or the app does not call the app and do not close the tray or it call the app and close the tray.

**Comment by myrkgard** [comment]
Okay, thank you for confirming that it's a bug. And also a big 'thank you' for all your great work here in general!

**Comment by husen-hn** [comment]
@myrkgard  I need this feature to reject a calling notification.
for now, I use this snippet code:
```Dart
AwesomeNotifications().actionStream.listen((receivedNotification) {
      if (receivedNotification.buttonKeyPressed == 'Reject') {
        SystemNavigator.pop();
        return null;
      }
    });

**Comment by rafaelsetragni** [comment]
Try to use the `disableAction` button type

**Comment by P-B1101** [comment]
Just like android reminder notification. we need action button type that trigger event and close notification and do not open app.

**Comment by saaimbiz** [comment]
use `autoCancel`, this will clear notification on tap of a button

```
NotificationActionButton(
     // ...
     autoCancel: true
)
```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of awesome_notifications and awesome_notifications_fcm and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
