### ISSUE TITLE
app icon any size not support 

### ISSUE THREAD

**Issue by kapilsharma-gts** [rafaelsetragni/awesome_notifications#848]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:awesome_notifications/src/awesome_notifications_core.dart': Failed assertion: line 169 pos 13: 'BitmapUtils().getMediaSource(defaultIcon!) == MediaSource.Resource': is not true.
awesome_notifications_core.dart:169
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AwesomeNotifications.initialize
awesome_notifications_core.dart:169
#3      LocalNotificationService.initialize
localnotifiction.dart:19
#4      main

**Comment by Bernardo-Junior** [comment]
so you can insert another icon, at least on Android I did it like this: I removed all "ic_launcher.png", because I wasn't using it as the default for my app's icon and it was precisely that that didn't let the resource:// work. After that, I reinstalled the application and set the directory for another icon that I wanted to use, for example: `resource://drawable/icon_app`, then it worked, I didn't test it for icons in the lib/assets folder, but it probably also works.
