### ISSUE TITLE
Schedule notifications does not fire up when app is killed (Android)

### ISSUE THREAD

**Issue by Inihood1** [rafaelsetragni/awesome_notifications#863]
Good day, How can I show notifications even when app is killed. And also, How do I dismiss or clear the notification?

**Comment by hamadaoussama** [comment]
i had same issue with xiaomi Note 8 phone when the app is closed the notification disappear

**Comment by hamadaoussama** [comment]
i think u need to set locked=false when its true didn't work

**Comment by Inihood1** [comment]
Thanks I'll try it

**Comment by hamadaoussama** [comment]
try it and tell me if it's work for you

**Comment by Inihood1** [comment]
It's not working after I set lock to false

**Comment by Natuuduck** [comment]
Hi, I also have this issue. While app is running, every scheduled notification works, but when app is terminated, no scheduled notifications show up. Setting locked to false or true don't fix this.

**Comment by hamadaoussama** [comment]
Schedules may be delayed or denied if the device/application is in battery saver mode or locked to perform background tasks. Educate your users on why it's important to avoid these modes and the potential consequences of using them. Also, some battery saving modes may differ between manufacturers, such as Samsung and Xiaomi, which automatically enable battery saving mode for newly installed apps. from https://pub.dev/packages/awesome_notifications i think that's why didnt work

**Comment by rhanifrizal** [comment]
got any answer anyone? the notification does fire up while in foreground and background but not when the app is killed

**Comment by Abdulbasheer095** [comment]
Thanks for ur valuable feedback Boss
Once resolved please let us know and we are also trying to sort out.
