### ISSUE TITLE
Failures on Production App (IOS / Android)

### ISSUE THREAD

**Issue by thize** [rafaelsetragni/awesome_notifications#90]
This is the failures graph of my app (Android) (on the blue arrow, that's when I started I launched the first version with this plugin):

![image](https://user-images.githubusercontent.com/10541221/104513481-7df89880-55ce-11eb-842e-354348713204.png)
 
This is the failures graph of my app (IOS) (on the blue arrow, that's when I started I launched the first version with this plugin):

![image](https://user-images.githubusercontent.com/10541221/104513690-cc0d9c00-55ce-11eb-9dc0-1402b307af0f.png)

I had to remove the plugin because the failure rate was very high, decreasing the visibility of the app in the store.

**Comment by rafaelsetragni** [comment]
Welcome a board! Now open the plugin, inspect the code and discovery whats going on. The dart is entirely open source.
If you wanna share your project with us ill be able to help you. Otherwise only you can discovery whats happened.

**Comment by rafaelsetragni** [comment]
Since seems youll not provide any valid information about it, i gonna assume that what happened was due to yours bad implementation, as you did not followed the instructions in the README file, inspected the example projects or even combined the use of this plugin with others that we have already been warned to not to do.

In case of someday you decide to help us with something more useful than just complain about a free code, that you just not even helped to build or payed for, we can open this topic again.
